---
title: "sandbox-01"
author: "Joshua Rosenberg"
date: "12/27/2017"
output: html_document
---

# Sandbox - 01 

This is a sandbox for exploring the data, in preparation for adding to the results section.

# 1. Processing data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning =T, echo = T, cache = F)
```

```{r, loading-packages}
library(tidyverse)
library(lmerTest)
library(lme4)
library(corrr)
library(jmRtools)
```

```{r, loading-data, eval = F}
esm <- read_csv("/Volumes/SCHMIDTLAB/PSE/data/STEM-IE/STEM-IE-esm.csv")
pre_survey_data_processed <- read_csv("/Volumes/SCHMIDTLAB/PSE/data/STEM-IE/STEM-IE-pre-survey.csv")
post_survey_data_partially_processed <- read_csv("/Volumes/SCHMIDTLAB/PSE/data/STEM-IE/STEM-IE-post-survey.csv")
video <- read_csv("/Volumes/SCHMIDTLAB/PSE/data/STEM-IE/STEM-IE-video.csv")
pqa <- read_csv("/Volumes/SCHMIDTLAB/PSE/data/STEM-IE/STEM-IE-pqa.csv")
attendance <- read_csv("/Volumes/SCHMIDTLAB/PSE/data/STEM-IE/STEM-IE-attendance.csv")
class_data <- read_csv("/Volumes/SCHMIDTLAB/PSE/data/STEM-IE/STEM-IE-class-video.csv")
demographics <- read_csv("/Volumes/SCHMIDTLAB/PSE/data/STEM-IE/STEM-IE-demographics.csv")
pm <- read_csv("/Volumes/SCHMIDTLAB/PSE/Data/STEM-IE/STEM-IE-program-match.csv")
```

```{r}
# save.image("~/desktop/sandbox-01.Rdata")
load("~/desktop/sandbox-01.Rdata")
```

```{r, processing-some-data}
attendance <- rename(attendance, participant_ID = ParticipantID)
attendance <- mutate(attendance, prop_attend = DaysAttended / DaysScheduled, 
                     participant_ID = as.integer(participant_ID))
attendance <- select(attendance, participant_ID, prop_attend)

demographics <- filter(demographics, participant_ID!= 7187)
demographics <- left_join(demographics, attendance)

esm$overall_engagement <- jmRtools::composite_mean_maker(esm, hard_working, concentrating, enjoy, interest)
```

```{r, joining-df}
df <- left_join(esm, pre_survey_data_processed, by = "participant_ID") # df & post-survey
df <- left_join(df, video, by = c("program_ID", "response_date", "sociedad_class", "signal_number")) # df & video
df <- left_join(df, demographics, by = c("participant_ID", "program_ID")) # df and demographics
```

```{r, proc-variables, echo = F}
df$participant_ID <- as.factor(df$participant_ID)
df$program_ID <- as.factor(df$program_ID)
df$beep_ID <- as.factor(df$beep_ID)
df$beep_ID_new <- as.factor(df$beep_ID_new)

df$youth_activity_rc <- ifelse(df$youth_activity == "Off Task", "Not Focused", df$youth_activity)

df$youth_activity_rc <- ifelse(df$youth_activity_rc == "Student Presentation" | df$youth_activity_rc == "Problem Solving", "Creating Product", df$youth_activity_rc)

df$youth_activity_rc <- ifelse(df$youth_activity_rc == "Showing Video", "Program Staff Led", df$youth_activity_rc)

df$youth_activity_rc <- as.factor(df$youth_activity_rc)

df$youth_activity_rc <- forcats::fct_relevel(df$youth_activity_rc, "Not Focused")

df$relevance <- jmRtools::composite_mean_maker(df, use_outside, future_goals, important)
```

```{r processing-demographics, echo = F, eval = F}
df$urm <- ifelse(df$race %in% c("White", "Asian"), 0, 1)
df$race <- as.factor(df$race)
df$race <- fct_lump(df$race, n = 2)
df$race_other <- fct_relevel(df$race, "Other")
df$gender_female <- as.factor(df$gender) # female is comparison_group
df$gender_female <- ifelse(df$gender_female == "F", 1, 
                           ifelse(df$gender_female == "M", 0, NA))
```

```{r}
pqa <- mutate(pqa, 
              active = active_part_1 + active_part_2,
              ho_thinking = ho_thinking_1 + ho_thinking_2 + ho_thinking_3,
              belonging = belonging_1 + belonging_2,
              agency = agency_1 + agency_2 + agency_3 + agency_4,
              youth_development_overall = active_part_1 + active_part_2 + ho_thinking_1 + ho_thinking_2 + ho_thinking_3 + belonging_1 + belonging_2 + agency_1 + agency_2 + agency_3 + agency_4,
              making_observations = stem_sb_8,
              data_modeling = stem_sb_2 + stem_sb_3 + stem_sb_9,
              interpreting_communicating = stem_sb_6,
              generating_data = stem_sb_4,
              asking_questions = stem_sb_1,
              stem_sb = stem_sb_1 + stem_sb_2 + stem_sb_3 + stem_sb_4 + stem_sb_5 + stem_sb_6 + stem_sb_7 + stem_sb_8 + stem_sb_9)

# pqa <- rename(pqa, sixth_math_sociedad = sixth_math)
# pqa <- rename(pqa, seventh_math_sociedad = seventh_math)
# pqa <- rename(pqa, eighth_math_sociedad = eighth_math)
# pqa <- rename(pqa, dance_sociedad = dance)
# pqa <- rename(pqa, robotics_sociedad = robotics)

pqa$sociedad_class <- ifelse(pqa$eighth_math == 1, "8th Math",
                             ifelse(pqa$seventh_math == 1, "7th Math",
                                    ifelse(pqa$sixth_math == 1, "6th Math",
                                           ifelse(pqa$robotics == 1, "Robotics",
                                                  ifelse(pqa$dance == 1, "Dance", NA)))))

pqa <- rename(pqa, 
              program_ID = SiteIDNumeric,
              response_date = resp_date,
              signal_number = signal)

pqa$program_ID <- as.character(pqa$program_ID)

df <- left_join(df, pqa, by = c("response_date", "program_ID", "signal_number", "sociedad_class"))
```

```{r}
df <- df %>% 
    mutate(youth_activity_three = case_when(
        youth_activity_rc == "Creating Product" ~ "Creating Product",
        youth_activity_rc == "Basic Skills Activity" ~ "Basic Skills Activity",
        TRUE ~ "Other"
    ))

df$youth_activity_three <- fct_relevel(df$youth_activity_three, 
                                       "Other")
```

### Creating composites

<!-- Cognitive engagement	As you were signaled, were you learning anything or getting better at something? -->
<!-- Behavioral engagement	As you were signaled, how hard were you working? -->
<!-- Affective engagement	As you were signaled, did you enjoy what you are doing? -->
<!-- Perceived challenge	As you were signaled, how challenging was the main activity? -->
<!-- Perceived competence	As you were signaled, were you good at the main activity? -->

```{r}
df <- df %>% 
    mutate(dm_cog_eng = learning,
           dm_beh_eng = hard_working,
           dm_aff_eng = enjoy,
           dm_challenge = challenge,
           dm_competence = good_at) %>% 
    rename(ssb_predict = stem_sb_1,
           ssb_model = stem_sb_2 ,
           ssb_analyze = stem_sb_3,
           ssb_measure = stem_sb_4,
           ssb_tools = stem_sb_5,
           ssb_precision = stem_sb_6,
           ssb_vocabulary = stem_sb_7,
           ssb_classification = stem_sb_8,
           ssb_symbols = stem_sb_9)
```

```{r}

out <- df %>% 
    group_by(program_ID) %>% 
    select(contains("ssb")) %>% 
    summarize_all(sum, na.rm = T)

out

out1 <- pqa %>% 
    select(contains("stem"), -sum_stem_sb, -stem_sb) %>% 
    summarize_all(sum, na.rm = T) / 236

names(out1) <- df %>% select(contains("ssb")) %>% names()

round(out1, 3)

pqa_out <- pqa %>% 
    group_by(program_ID) %>% 
    select(contains("stem"), -sum_stem_sb, -stem_sb) %>% 
    summarize_all(sum, na.rm = T)

names(pqa_out) <- names(out)

pqa_out
```

# 2. Descriptives

### Correlations

```{r}
df %>% 
    select(contains("dm")) %>% 
    correlate() %>% 
    shave() %>% 
    fashion() %>% 
    knitr::kable()

df %>% 
    select(contains("stem_sb"), -sum_stem_sb, -stem_sb) %>% 
    correlate() %>% 
    shave() %>% 
    fashion() %>% 
    knitr::kable()
```

### Descriptives

```{r}
library(skimr)

df %>% 
    select(contains("dm"), -sum_stem_sb, -stem_sb) %>% 
    skim() 

df %>% 
    select(contains("stem_sb"), -sum_stem_sb, -stem_sb) %>% 
    skim() 
```

# 3. Mixture Models

### tidyLPA

```{r}
library(tidyLPA)

df %>%
    select(contains("dm")) %>% 
    mutate_all(scale) %>% 
    compare_models_lpa(contains("dm"))

df %>% 
    create_profiles_lpa(contains("dm"), n_profiles = 3) %>% 
    plot_profiles_lpa(to_center = T)

df %>% 
    create_profiles_lpa(contains("dm"), n_profiles = 4) %>% 
    plot_profiles_lpa(to_center = T)

df %>% 
    create_profiles_lpa(contains("dm"), n_profiles = 5) %>% 
    plot_profiles_lpa(to_center = T)
```

### MPlus

```{r}
library(MplusAutomation)
```
