# Abstract {#abstract}

This study will examine how 203 early adolescent learners work with data, or engage in activities focused on constructing measures of and modeling data, in the context of STEM summer enrichment programs. Video recordings of programs will be coded to identify the presence of five aspects of learners’ work with data: asking questions or identifying problems, constructing measures, collecting data, accounting for variability or uncertainty, and interpreting and communicating findings. Additionally, measures of instructional support for such practices will be used, so codes for work with data with instructional support are also created. Youth’s responses to the Experience Sampling Method (ESM) will be used to examine their cognitive, behavioral, and affective engagement as well as their perceptions of challenge and competence. A person-oriented analytic approach will be used to identify profiles of engagement that will help us to understand how learners engage in work with data. Examining work with data in terms of contemporary engagement theory can help us to understand these key STEM activities in terms of learner's experience, which past research suggests impacts student learning, yet which has not been brought to bear on the topic of work with data. Knowing more about students’ engagement can help us to design activities and interventions around work with data that are highly engaging to students and that support their capabilities to work with data. 