# Introduction {#intro-placemarker}

Socializing, working, and even teaching and learning are increasingly impacted by data. These sources of data are created by us, for us, and about us. Work with data in education may be a valuable context for teaching and learning because it reverses the role that teachers and especially learners commonly find themselves in, namely, as the targets of the work of data analysts and policymakers. In particular, work with data empowers learners to--themselves--use data to ask and answer questions. In turn, work with data promotes learners to create new knowledge, too, in addition to learning about the key ideas and practices of a subject matter domain.

Work with data includes broad processes of collecting, creating, modeling data, and even asking questions that can be answered with data. This work, then, is more than just crunching numbers. It is also more than interpreting a figure created by someone else. Instead, work with data is about making sense of phenomena in the world--or solving problems in the world. This focus on phenomena is particularly relevant to those designing and enacting learning opportunities focused on work with data (Lee & Wilkerson, 2018; Singer, Hilton, & Schweingruber, 2006; Wild & Pfannkuch, 1999). 

Despite not being very prevalent, aspects of work with data cut across STEM (science, technology and computer science, engineering, and mathematics) domains: Aspects of work with data are recognized as core competencies across recent curricular documents. They are found, for example, in the *Next Generation Science Standards*  (NGSS Lead States, 2013) and the *Common Core State Standards* (in mathematics; National Governors Association Center for Best Practices, Council of Chief State School Officers, 2010). Both of these standards highlight the role of authentic work with data. Thus, work with data can be empowering not only because it positions learners as creators of new knowledge about the world, but also because it can support the development of capabilities that learners can use across subject areas. These capabilities may be particularly useful in STEM domains because advanced coursework in these domains often involves demanding and abstract work with data, work that may be more accessible to more learners when they encounter it earlier in their education.

Past research on work with data has mostly been set in mathematics contexts and has focused on mathematical practices, like generating measures of phenomena and creating data models (English, 2012; Lehrer & Romberg, 1996; Lesh, Middleton, Caylor, & Gupta, 2008). It has often focused on specific cognitive outcomes (e.g., Gelman & Markman, 1987), strategies to support work with data (Petrosino, Lehrer, & Schauble, 2003), and some opportunities and challenges facing both teachers and learners when working with data (e.g., Konold & Pollatsek, 2002). There has been some research about work with data in science settings (Lee & Wilkerson, in press; National Research Council, 2012), though this work varies greatly concerning the nature of work with data (McNeill & Berland, 2017). Findings from this past research broadly suggest that engaging in work with data is powerful concerning learning both about and how to do mathematics and science. Lehrer and Schauble (2015), summarizing past research on the use of mathematical practices in science contexts, note that work with data “has an exceptionally high payoff in terms of students’ scientific reasoning” (Lehrer & Schauble, 2015, p. 696).

To date, past research shows that using a framework from contemporary engagement theory to characterize students’ experiences has been informative both in research and to practicing educators. Work with data might be engaging to youth because past research has shown hands-on, laboratory work, to which work with data is similar—to be (Schmidt, Rosenberg, & Beymer, 2018). In addition, work with data is demanding and requires sustained effort and focus (Lehrer & Schauble, 2015; National Research Council, 2015), and past work has shown that when learners are more challenged (and competent), they are more likely to be engaged (Schneider et al., 2016; Shernoff et al., 2016). Knowing more about how youth engage in work with data is valuable as engagement is a meaningful outcome for STEM learners in its own right (Sinatra, Heddy, & Lombardi, 2015). It may also be an antecedent of changes in other outcomes, such as their well-being, achievement, and the pursuit of an area of study or career (Wang, Chow, Hofkens, & Salmela-Aro, 2015; Wang & Eccles, 2012). However, research has not examined engagement in work with data. Because engaging in work with data seems to be so potentially beneficial to learners, better understanding the nature of work with data and learners' engagement in such practices is needed. 

The purpose of this study, then, is to examine youth engagement in a variety of learning activities that involve work with data. I explore youths' engagement in the context of outside-of-school STEM enrichment programs carried out during the summer, and I consider work with data through the lens of specific aspects identified from past research, such as asking questions and generating and modeling data. Such settings (in outside-of-school programs) are an especially useful context for exploring work with data because they can be designed around youths' interests (Lauer, Akiba, Wilkerson, Apthorp, Snow, & Martin-Glenn, 2006). One promise of work with data in outside-of-school settings is that data can be inherently interesting to learners and can be used as a context for learning about the world, allowing youth to ask and answer personally and socially meaningful questions, whereas many outside-of-school programs are focused around commercial aims, such as developing mobile device applications. Knowing more about how youth engage can also provide a foundation for subsequent work to explore how particular curricula and engaging experiences for youth spark their interest in work with data, including hobbies and occupations related to data science, but also in STEM domains in general. 
