--- 
title: "Understanding Work With Data in Summer STEM Programs Through An Experience Sampling Method Approach"
always_allow_html: yes
author: "Joshua M. Rosenberg"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: jrosen48/dissertation
description: "This is Joshua Rosenberg's dissertation"
---

# Preamble

## Abstract

Data-rich activities provide an opportunity to develop core competencies in both science and mathematics identified in curricular standards. Perhaps even more importantly work with data puts learners in the position to use data to ask and answer questions, a potentially empowering capability. Research on work with data has focused on cognitive outcomes and the development of specific practices at the student and classroom levels, and yet, little research has considered learners’ engagement. The present study explores learners engagement in work with data in the context of summer STEM programs. The aspects of work with data that are the focus of this study are: asking questions, observing phenomena, constructing measures and generating data, data modeling, and interpreting findings. Data from measures of learners' engagement was collected through the Experience Sampling Method (ESM) that involves asking learners at random intervals to answer short questions about their engagement to discover profiles of learners' engagement.

Data was collected from nine summer STEM programs over four weeks in the Northeastern United States. 203 learners reported 2,970 responses via short ESM surveys of how engaged they were (cognitively, behaviorally, and affectively, assessed through separate items) and of their perceptions of themselves (their competence) and the activity (its challenge).  These data were used to examine five specific research questions: 1) What is the frequency and nature of opportunities for youth to engage in each of the five aspects of work with data in summer STEM programs? 2) What profiles of engagement emerge from data collected via ESM in the programs? 3) What are sources of variability for the profiles of engagement? 4) How do the five aspects of work with data relate to profiles of engagement? 5) How do youth characteristics relate to profiles of engagement?

Findings show that aspects of work with data were fairly common overall, but that work with data was enacted out in varying ways, including some that were possibly highly engaging. Six profiles of youth engagement were identified, representing distinct configurations of the five indicators of engagement. Substantial variability in the profiles was present at the youth level, with less explained by the program youth were in or the nature of the particular instructional episode present at the times when youth were signaled. Relations between the profiles of engagement and each of the aspects of work with data were somewhat small: Notable exceptions were the generating data and data modeling were significantly associated with full engagement. Youth with higher pre-program interest in STEM were more likely to be engaged and competent but not challenged, though other youth characteristics were not highly related to the profiles.

I discuss key findings as regards work with data in summer STEM programs and other informal learning environments, the nature of youths' engagement, and what factors can predict engagement. The design and goals of summer STEM programs, which are not (necessarily) focused on activities related to work with data, as well as other limitations including the measures for work with data used and the analytic approach, are identified and described. The role of generating data and modeling data as well as attention to the specifics of how work with data are enacted are presented as implications for practice. I highlight aspects of the findings and the implications for practice with respect to work with data in general and to engagement in informal learning environments, such as summer STEM programs, in both cases with an emphasis on how work with data can serve as a promising context for learning in STEM subject areas.

## Acknowledgments

I would like to acknowledge Matthew Koehler and Jennifer Schmidt. I am fortunate to have learned how to become a scholar through Matt, who has been my advisor since I entered my Ph.D. program. I could not ask for a better advisor. Thanks, Matt! Matt and Jen provided support for me to pursue the study reported in this dissertation. They gracefully and skillfully co-directed my dissertation, and I am grateful for that. I am also grateful to Jen for  not only as a co-director of my dissertation but also for being a mentor and a trusted source of advice related to my development as a scholar, especially during the process of my academic job search. Thank you, Jen!

I would also like to acknowledge Lisa Linnenbrink-Garcia and Christina Schwarz as members of my dissertation committee. In addition to serving as committee members, I am grateful for the opportunity to develop as a scholar through working and learning from both. Thank you to my mentors and peers in the Educational Psychology and Educational Technology program at MSU. Thank you to collaborators Lee Shumow and Neil Naftzger for their work on the STEM Interest and Engagement project (National Science Foundation DRL-1421198), of which this project is a secondary analysis. Thank you to participating youth activity leaders and youth.

Please note that this material is based upon work supported by the National Science Foundation under Grant No. DRL-1421198. Any opinions, findings, conclusions, or recommendations expressed in this material are those of the authors and do not reflect the views of the National Science Foundation.

Understanding Work With Data in Summer STEM Programs Through An Experience Sampling Method Approach is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.

## Dedication

This dissertation is dedicated to Katie and to Jonah, who (mostly) happily slept through most of its writing.
