<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Engaging in Data Practices in Summer STEM Programs: A Person-in-Context Approach</title>
  <meta name="description" content="This is Joshua Rosenberg’s dissertation">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Engaging in Data Practices in Summer STEM Programs: A Person-in-Context Approach" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is Joshua Rosenberg’s dissertation" />
  <meta name="github-repo" content="jrosen48/dissertation" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Engaging in Data Practices in Summer STEM Programs: A Person-in-Context Approach" />
  
  <meta name="twitter:description" content="This is Joshua Rosenberg’s dissertation" />
  

<meta name="author" content="Joshua M. Rosenberg">


<meta name="date" content="2018-04-21">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="references.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />










<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Engaging in Data Practices in Summer STEM Programs: A Person-in-Context Approach</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="intro-placemarker.html"><a href="intro-placemarker.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="literature-review.html"><a href="literature-review.html"><i class="fa fa-check"></i><b>2</b> Literature Review</a><ul>
<li class="chapter" data-level="2.1" data-path="literature-review.html"><a href="literature-review.html#defining-work-with-data"><i class="fa fa-check"></i><b>2.1</b> Defining Work With Data</a></li>
<li class="chapter" data-level="2.2" data-path="literature-review.html"><a href="literature-review.html#what-we-know-and-do-not-know-about-engagement-in-work-with-data"><i class="fa fa-check"></i><b>2.2</b> What We Know (And Do Not Know) About Engagement in Work with Data</a></li>
<li class="chapter" data-level="2.3" data-path="literature-review.html"><a href="literature-review.html#engagement-in-stem-domains"><i class="fa fa-check"></i><b>2.3</b> Engagement in STEM Domains</a></li>
<li class="chapter" data-level="2.4" data-path="literature-review.html"><a href="literature-review.html#using-esm-to-study-the-dynamics-of-engagement"><i class="fa fa-check"></i><b>2.4</b> Using ESM to Study the Dynamics of Engagement</a></li>
<li class="chapter" data-level="2.5" data-path="literature-review.html"><a href="literature-review.html#a-person-oriented-approach-to-engagement"><i class="fa fa-check"></i><b>2.5</b> A Person-Oriented Approach to Engagement</a></li>
<li class="chapter" data-level="2.6" data-path="literature-review.html"><a href="literature-review.html#need-for-the-present-study"><i class="fa fa-check"></i><b>2.6</b> Need for the Present Study</a></li>
<li class="chapter" data-level="2.7" data-path="literature-review.html"><a href="literature-review.html#conceptual-framework"><i class="fa fa-check"></i><b>2.7</b> Conceptual Framework</a></li>
<li class="chapter" data-level="2.8" data-path="literature-review.html"><a href="literature-review.html#research-questions"><i class="fa fa-check"></i><b>2.8</b> Research Questions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="method.html"><a href="method.html"><i class="fa fa-check"></i><b>3</b> Method</a><ul>
<li class="chapter" data-level="3.1" data-path="method.html"><a href="method.html#context"><i class="fa fa-check"></i><b>3.1</b> Context</a></li>
<li class="chapter" data-level="3.2" data-path="method.html"><a href="method.html#procedure"><i class="fa fa-check"></i><b>3.2</b> Procedure</a></li>
<li class="chapter" data-level="3.3" data-path="method.html"><a href="method.html#data-sources-and-measures"><i class="fa fa-check"></i><b>3.3</b> Data Sources and Measures</a><ul>
<li class="chapter" data-level="3.3.1" data-path="method.html"><a href="method.html#esm-measures-of-learners-engagement-and-its-conditions"><i class="fa fa-check"></i><b>3.3.1</b> ESM measures of learners’ engagement and its conditions</a></li>
<li class="chapter" data-level="3.3.2" data-path="method.html"><a href="method.html#survey-measures-of-pre-interest"><i class="fa fa-check"></i><b>3.3.2</b> Survey measures of pre-interest</a></li>
<li class="chapter" data-level="3.3.3" data-path="method.html"><a href="method.html#codes-for-instructional-support-for-work-with-data-from-the-video-recordings"><i class="fa fa-check"></i><b>3.3.3</b> Codes for instructional support for work with data from the video-recordings</a></li>
<li class="chapter" data-level="3.3.4" data-path="method.html"><a href="method.html#demographic-variables"><i class="fa fa-check"></i><b>3.3.4</b> Demographic variables</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="method.html"><a href="method.html#data-analysis"><i class="fa fa-check"></i><b>3.4</b> Data Analysis</a><ul>
<li class="chapter" data-level="3.4.1" data-path="method.html"><a href="method.html#preliminary-analyses"><i class="fa fa-check"></i><b>3.4.1</b> Preliminary analyses</a></li>
<li class="chapter" data-level="3.4.2" data-path="method.html"><a href="method.html#analysis-for-research-question-1"><i class="fa fa-check"></i><b>3.4.2</b> Analysis for Research Question #1</a></li>
<li class="chapter" data-level="3.4.3" data-path="method.html"><a href="method.html#analysis-for-research-question-2"><i class="fa fa-check"></i><b>3.4.3</b> Analysis for Research Question #2</a></li>
<li class="chapter" data-level="3.4.4" data-path="method.html"><a href="method.html#analysis-for-research-question-3"><i class="fa fa-check"></i><b>3.4.4</b> Analysis for Research Question #3</a></li>
<li class="chapter" data-level="3.4.5" data-path="method.html"><a href="method.html#analysis-for-research-question-4"><i class="fa fa-check"></i><b>3.4.5</b> Analysis for Research Question #4</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="method.html"><a href="method.html#power-analysis"><i class="fa fa-check"></i><b>3.5</b> Power Analysis</a></li>
<li class="chapter" data-level="3.6" data-path="method.html"><a href="method.html#sensitivity-analysis"><i class="fa fa-check"></i><b>3.6</b> Sensitivity Analysis</a></li>
<li class="chapter" data-level="3.7" data-path="method.html"><a href="method.html#limitations"><i class="fa fa-check"></i><b>3.7</b> Limitations</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="preliminary-results.html"><a href="preliminary-results.html"><i class="fa fa-check"></i><b>4</b> Preliminary results</a><ul>
<li class="chapter" data-level="4.1" data-path="preliminary-results.html"><a href="preliminary-results.html#preliminary-analysis"><i class="fa fa-check"></i><b>4.1</b> Preliminary analysis</a><ul>
<li class="chapter" data-level="4.1.1" data-path="preliminary-results.html"><a href="preliminary-results.html#descriptive-statistics-for-study-variables"><i class="fa fa-check"></i><b>4.1.1</b> Descriptive statistics for study variables</a></li>
<li class="chapter" data-level="4.1.2" data-path="preliminary-results.html"><a href="preliminary-results.html#correlations-among-study-variables"><i class="fa fa-check"></i><b>4.1.2</b> Correlations among study variables</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="preliminary-results.html"><a href="preliminary-results.html#statistical-software-developed"><i class="fa fa-check"></i><b>4.2</b> Statistical software developed</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="results-for-research-question-1.html"><a href="results-for-research-question-1.html"><i class="fa fa-check"></i><b>5</b> Results for Research Question #1</a><ul>
<li class="chapter" data-level="5.1" data-path="results-for-research-question-1.html"><a href="results-for-research-question-1.html#frequency-of-work-with-data"><i class="fa fa-check"></i><b>5.1</b> Frequency of work with data</a></li>
<li class="chapter" data-level="5.2" data-path="results-for-research-question-1.html"><a href="results-for-research-question-1.html#nature-of-work-with-data"><i class="fa fa-check"></i><b>5.2</b> Nature of work with data</a><ul>
<li class="chapter" data-level="5.2.1" data-path="results-for-research-question-1.html"><a href="results-for-research-question-1.html#coding"><i class="fa fa-check"></i><b>5.2.1</b> Coding</a></li>
<li class="chapter" data-level="5.2.2" data-path="results-for-research-question-1.html"><a href="results-for-research-question-1.html#findings"><i class="fa fa-check"></i><b>5.2.2</b> Findings</a></li>
<li class="chapter" data-level="5.2.3" data-path="results-for-research-question-1.html"><a href="results-for-research-question-1.html#how-instructional-support-for-work-with-data-was-measured"><i class="fa fa-check"></i><b>5.2.3</b> How instructional support for work with data was measured</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="results-for-research-question-2.html"><a href="results-for-research-question-2.html"><i class="fa fa-check"></i><b>6</b> Results for Research Question #2</a><ul>
<li class="chapter" data-level="6.1" data-path="results-for-research-question-2.html"><a href="results-for-research-question-2.html#results-for-research-question-2-what-profiles-of-youth-engagement-and-its-conditions-emerge-from-experiential-data-collected-in-the-programs"><i class="fa fa-check"></i><b>6.1</b> Results for Research Question #2: What profiles of youth engagement and its conditions emerge from experiential data collected in the programs?</a><ul>
<li class="chapter" data-level="6.1.1" data-path="results-for-research-question-2.html"><a href="results-for-research-question-2.html#examination-of-specific-candidate-models"><i class="fa fa-check"></i><b>6.1.1</b> Examination of specific candidate models</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="results-for-research-question-3.html"><a href="results-for-research-question-3.html"><i class="fa fa-check"></i><b>7</b> Results for Research Question #3</a><ul>
<li class="chapter" data-level="7.1" data-path="results-for-research-question-3.html"><a href="results-for-research-question-3.html#results-for-research-question-3-how-do-data-practices-relate-to-youth-engagement-in-the-programs"><i class="fa fa-check"></i><b>7.1</b> Results for Research Question #3: How do data practices relate to youth engagement in the programs?</a><ul>
<li class="chapter" data-level="7.1.1" data-path="results-for-research-question-3.html"><a href="results-for-research-question-3.html#null-models"><i class="fa fa-check"></i><b>7.1.1</b> Null models</a></li>
<li class="chapter" data-level="7.1.2" data-path="results-for-research-question-3.html"><a href="results-for-research-question-3.html#models-with-variables-for-aspects-of-instructional-support-for-work-with-data-added-separately"><i class="fa fa-check"></i><b>7.1.2</b> Models with variables for aspects of instructional support for work with data added separately</a></li>
<li class="chapter" data-level="7.1.3" data-path="results-for-research-question-3.html"><a href="results-for-research-question-3.html#models-with-the-composite-added"><i class="fa fa-check"></i><b>7.1.3</b> Models with the composite added</a></li>
<li class="chapter" data-level="7.1.4" data-path="results-for-research-question-3.html"><a href="results-for-research-question-3.html#summary-of-findings-for-research-question-2"><i class="fa fa-check"></i><b>7.1.4</b> Summary of findings for research question #2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="results-for-research-question-4.html"><a href="results-for-research-question-4.html"><i class="fa fa-check"></i><b>8</b> Results for Research Question #4</a><ul>
<li class="chapter" data-level="8.1" data-path="results-for-research-question-4.html"><a href="results-for-research-question-4.html#results-for-research-question-4-how-do-youth-characteristics-relate-to-their-engagement-in-summer-stem-programs"><i class="fa fa-check"></i><b>8.1</b> Results for Research Question #4: How do youth characteristics relate to their engagement in summer STEM programs?</a><ul>
<li class="chapter" data-level="8.1.1" data-path="results-for-research-question-4.html"><a href="results-for-research-question-4.html#models-with-pre-interest-gender-and-under-represented-minority-urm-status"><i class="fa fa-check"></i><b>8.1.1</b> Models with pre interest, gender, and under-represented minority (URM) status</a></li>
<li class="chapter" data-level="8.1.2" data-path="results-for-research-question-4.html"><a href="results-for-research-question-4.html#models-with-pre-interest-gender-and-urm-status-and-the-aspects-of-work-with-data"><i class="fa fa-check"></i><b>8.1.2</b> Models with pre interest, gender, and URM status and the aspects of work with data</a></li>
<li class="chapter" data-level="8.1.3" data-path="results-for-research-question-4.html"><a href="results-for-research-question-4.html#models-with-pre-interest-gender-and-urm-status-and-work-with-data-composite"><i class="fa fa-check"></i><b>8.1.3</b> Models with pre-interest, gender, and URM status and work with data composite</a></li>
<li class="chapter" data-level="8.1.4" data-path="results-for-research-question-4.html"><a href="results-for-research-question-4.html#models-with-interactions-between-pre-interest-gender-and-urm-status-and-work-with-data-composite"><i class="fa fa-check"></i><b>8.1.4</b> Models with interactions between pre interest, gender, and URM status and work with data composite</a></li>
<li class="chapter" data-level="8.1.5" data-path="results-for-research-question-4.html"><a href="results-for-research-question-4.html#summary-of-findings-for-research-question-3"><i class="fa fa-check"></i><b>8.1.5</b> Summary of findings for research question #3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="discussion.html"><a href="discussion.html"><i class="fa fa-check"></i><b>9</b> Discussion</a><ul>
<li class="chapter" data-level="9.0.1" data-path="discussion.html"><a href="discussion.html#key-findings"><i class="fa fa-check"></i><b>9.0.1</b> Key Findings</a></li>
<li class="chapter" data-level="9.0.2" data-path="discussion.html"><a href="discussion.html#limitations-of-the-study"><i class="fa fa-check"></i><b>9.0.2</b> Limitations of the Study</a></li>
<li class="chapter" data-level="9.0.3" data-path="discussion.html"><a href="discussion.html#recommendations-for-future-research"><i class="fa fa-check"></i><b>9.0.3</b> Recommendations for Future Research</a></li>
<li class="chapter" data-level="9.0.4" data-path="discussion.html"><a href="discussion.html#implications-for-practice"><i class="fa fa-check"></i><b>9.0.4</b> Implications for Practice</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>10</b> References</a></li>
<li class="chapter" data-level="11" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>11</b> Appendix</a><ul>
<li class="chapter" data-level="11.1" data-path="appendix.html"><a href="appendix.html#appendix-stem-pqa-alignment"><i class="fa fa-check"></i><b>11.1</b> Appendix: STEM-PQA alignment</a></li>
<li class="chapter" data-level="11.2" data-path="appendix.html"><a href="appendix.html#appendix-method-additional-materials"><i class="fa fa-check"></i><b>11.2</b> Appendix: Method additional materials</a><ul>
<li class="chapter" data-level="11.2.1" data-path="appendix.html"><a href="appendix.html#statistical-software-developed-1"><i class="fa fa-check"></i><b>11.2.1</b> Statistical software developed</a></li>
<li class="chapter" data-level="11.2.2" data-path="appendix.html"><a href="appendix.html#appendix-descriptive-statistics-additional-materials"><i class="fa fa-check"></i><b>11.2.2</b> Appendix: Descriptive statistics additional materials</a></li>
<li class="chapter" data-level="11.2.3" data-path="appendix.html"><a href="appendix.html#appendix-program-descriptions"><i class="fa fa-check"></i><b>11.2.3</b> Appendix: Program descriptions</a></li>
<li class="chapter" data-level="11.2.4" data-path="appendix.html"><a href="appendix.html#appendix-research-question-1-additional-materials"><i class="fa fa-check"></i><b>11.2.4</b> Appendix: Research Question #1 additional materials</a></li>
<li class="chapter" data-level="11.2.5" data-path="appendix.html"><a href="appendix.html#model-specifications-details"><i class="fa fa-check"></i><b>11.2.5</b> Model specifications details</a></li>
<li class="chapter" data-level="11.2.6" data-path="appendix.html"><a href="appendix.html#model-1-candidate-solutions"><i class="fa fa-check"></i><b>11.2.6</b> Model 1 candidate solutions</a></li>
<li class="chapter" data-level="11.2.7" data-path="appendix.html"><a href="appendix.html#model-2-candidate-solutions"><i class="fa fa-check"></i><b>11.2.7</b> Model 2 candidate solutions</a></li>
<li class="chapter" data-level="11.2.8" data-path="appendix.html"><a href="appendix.html#exploration-of-a-wide-range-of-models-a"><i class="fa fa-check"></i><b>11.2.8</b> Exploration of a wide range of models a</a></li>
<li class="chapter" data-level="11.2.9" data-path="appendix.html"><a href="appendix.html#in-depth-statistics-for-particular-models"><i class="fa fa-check"></i><b>11.2.9</b> In-depth statistics for particular models</a></li>
<li class="chapter" data-level="11.2.10" data-path="appendix.html"><a href="appendix.html#comparison-of-model-1-and-model-2-type-solutions"><i class="fa fa-check"></i><b>11.2.10</b> Comparison of model 1 and model 2 type solutions</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="appendix.html"><a href="appendix.html#appendix-models-for-research-question-2-and-3-with-the-seven-profile-solution"><i class="fa fa-check"></i><b>11.3</b> Appendix: Models for research question #2 and #3 with the seven-profile solution</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Engaging in Data Practices in Summer STEM Programs: A Person-in-Context Approach</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="appendix" class="section level1">
<h1><span class="header-section-number">Chapter 11</span> Appendix</h1>
<div id="appendix-stem-pqa-alignment" class="section level2">
<h2><span class="header-section-number">11.1</span> Appendix: STEM-PQA alignment</h2>
<pre><code>## Error: &lt;text&gt;:2:200: unexpected symbol
## 1: tibble::tribble(
## 2:   ~Work.With.Data.Codes.Originally.Proposed,                                                                                                    ~Description, ~Categories.from.STEM-PQA.(Already
##                                                                                                                                                                                                           ^</code></pre>
</div>
<div id="appendix-method-additional-materials" class="section level2">
<h2><span class="header-section-number">11.2</span> Appendix: Method additional materials</h2>
<div id="statistical-software-developed-1" class="section level3">
<h3><span class="header-section-number">11.2.1</span> Statistical software developed</h3>
<p>The functions in tidyLPA dynamically generate MPlus syntax, so that, for example, a user can simply provide a data frame with variables to be used in the analysis, the specification for one of six models, the number of profiles to be estimated as part of the analysis, and a number of fine-grained options concerning the estimation and the output generated. From these inputs, a data file for MPlus is prepared and saved, the model syntax is created and saved in a model input file, the model is run, and the output, including the “savedata”, or the data with its associated posterior probabilities and profile assignments, is returned to R for use plots or in subsequent analyses.</p>
<p>Because of the considerable time that it takes to generate MPlus model syntax (i.e., when choosing to specify a model with different parameters or when changing the number of profiles to be estimated as part of the solution), this package makes it easier to carry out LPA in a flexible way, while retaining the power of the MPlus software. While this functionality makes it considerably easier to carry out LPA, it requires that MPlus be purchased and installed. Because of this, the R package I developed also includes wrapper functions to an open-source tool, mclust (Scrucca, Fop, Murphy, &amp; Raftery, 2016). This is a very widely-used package for mixture modeling. While some authors have suggested that it can be used to carry out LPA (Oberski, 2016), a key challenge for analysts using it concerns specifying the models. This is because the models are described in terms of the geometric properties of the multivariate distributions being estimated (i.e., “spherical, equal volume”), rather than in terms of whether and how the means, variances, and covariances are estimated. This R package corresponds LPA models to the mclust models and provides the same functionality that the functions that use MPlus provide, namely, preparing data, running the model, and returning the output or use in subsequent analyses. As part of incorporating the mclust functionality, the functions that use MPlus and those that use mclust have been benchmarked (Rosenberg, 2018). Despite leading to identical results (in most cases) for small datasets, because of differences in how the E-M algorithm is initialized as well as other estimation-related differences, output will likely not be identical for many analyses.</p>
</div>
<div id="appendix-descriptive-statistics-additional-materials" class="section level3">
<h3><span class="header-section-number">11.2.2</span> Appendix: Descriptive statistics additional materials</h3>
<p>The Spearman rank (because the data were dichotomous) correlations among the aspects of instructional support for work with data are presented. The variables were moderately correlated, with <em>rho</em> values between .18 and .50. These suggest that signals are assocaited</p>
<table>
<caption><span id="tab:unnamed-chunk-15">Table 11.1: </span>Correlations among codes for instructional support for work with data (and composite of all codes)</caption>
<thead>
<tr class="header">
<th align="left">rowname</th>
<th align="left">Asking.Questions</th>
<th align="left">Making.Observations</th>
<th align="left">Generating.Data</th>
<th align="left">Data.Modeling</th>
<th align="left">Communicating.Findings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Asking Questions</td>
<td align="left"></td>
<td align="left">.38</td>
<td align="left">.28</td>
<td align="left">.43</td>
<td align="left">.73</td>
</tr>
<tr class="even">
<td align="left">Making Observations</td>
<td align="left">.38</td>
<td align="left"></td>
<td align="left">.24</td>
<td align="left">.18</td>
<td align="left">.55</td>
</tr>
<tr class="odd">
<td align="left">Generating Data</td>
<td align="left">.28</td>
<td align="left">.24</td>
<td align="left"></td>
<td align="left">.30</td>
<td align="left">.65</td>
</tr>
<tr class="even">
<td align="left">Data Modeling</td>
<td align="left">.43</td>
<td align="left">.18</td>
<td align="left">.30</td>
<td align="left"></td>
<td align="left">.67</td>
</tr>
<tr class="odd">
<td align="left">Communicating Findings</td>
<td align="left">.73</td>
<td align="left">.55</td>
<td align="left">.65</td>
<td align="left">.67</td>
<td align="left"></td>
</tr>
</tbody>
</table>
</div>
<div id="appendix-program-descriptions" class="section level3">
<h3><span class="header-section-number">11.2.3</span> Appendix: Program descriptions</h3>
<table>
<caption><span id="tab:unnamed-chunk-16">Table 11.2: </span>STEM Enrichment Program Names and Their Descriptions</caption>
<thead>
<tr class="header">
<th align="left">Program.Name</th>
<th align="left">Program.Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Island Explorers</td>
<td align="left">A science-focused program that aims to help youth develop expertise on one species found in the local ecosystem by reading and writing about related content for up to an hour per day; undertaking data collection and analysis tasks to learn about the local ecosystem and how to communicate scientific data; developing vocabulary about the local ecosystem; using art to learn and communicate information; and publishing a book illustrating important elements of the species being studied. Located in both the classroom and local ecosystem. 27 students who are rising 6th graders. Youth spend the morning in more academically-oriented sessions in a classroom setting, while afternoon sessions involved STEM-oriented enrichment sessions taking place outside (the program was associated with Outward Bound) with an emphasis on exploration of the local ecosystem.</td>
</tr>
<tr class="even">
<td align="left">The Ecosphere</td>
<td align="left">A science-focused program that aims to help youth to explore the marine life of Narragansett Bay. Efforts were undertaken to build youth content knowledge in the areas of ecosystem preservation, marine biology, and water quality, and related skills, such as questioning, showing initiative, data collection, measuring, maintaining an ecosystem, and analyzing water samples. Located in a classroom setting, shoreline, and science education center. 27 youth who are rising 6th to 9th graders. Youth attended programming in a classroom at an area middle school and in a field-based setting on alternating days. Field-based settings included a science education center at a community-based organization and field trips to sites in the community related to the program’s focus.</td>
</tr>
<tr class="odd">
<td align="left">Zoology Partners</td>
<td align="left">A science-focused program that aims to support youth’s development of content knowledge related to the issue of endangered species, including how species become endangered, processes for monitoring ecosystem viability and population levels, solutions to prevent species from becoming endangered, and approaches to reviving populations that are currently endangered. Located in the classroom as well as zoos, parks, and other natural areas. 25 youth who are rising 6th to 9th graders. Youth attended programming in a classroom at an area middle school and in a field-based setting on alternating days. Field-based settings included a local zoo and field trips to sites in the community related to the program’s focus.</td>
</tr>
<tr class="even">
<td align="left">Marine Investigators</td>
<td align="left">A science-focused program that aims to provide youth with opportunities to learn about and experience Narragansett Bay; examine human impacts on the local ecosystem, including how the geography of the Bay helped influence human history and how the history of humans along the shoreline has impacted the Bay, and begin the process of cultivating a sense of stewardship among participating youth for caring for and protecting the Bay in the future. Located in the classroom, shoreline along the bay, ship on the bay, and various field locations associated with bay health. 19 youth who are rising 7th to 9th graders. Youth attended programming in a classroom at an area middle school and in a field-based setting on alternating days. Field-based settings included the local bay shoreline, a voyage on a marine education ship researching in the Bay, and field trips to sites in the community related to the program’s focus. During the span of the program, youth had the opportunity to participate in both a water quality research study.</td>
</tr>
<tr class="odd">
<td align="left">Comunidad de Aprendizaje</td>
<td align="left">A STEM-focused program that aims to help youth improve basic skills in mathematics and develop an interest in STEM content and entrepreneurship. Primarily in the classroom setting. 33 students who are rising 5th to 8th graders. Morning sessions are characterized by direct instruction in mathematics for individual grade levels and mixed grade level afternoon enrichment sessions in either robotics or dance. The direct instruction component of the programs was organized around a theme of promoting entrepreneurship with the goal of helping participating youth better see the relevance of mathematics to future career goals and opportunities.</td>
</tr>
<tr class="even">
<td align="left">Jefferson House</td>
<td align="left">A STEM-focused program that aims to support youth’s development of basic math skills, the program was primarily focused on helping youth develop problem solving, self-improvement, and critical thinking skills. Located in a classroom. 11 youth who are rising 7th graders. The youth spent the morning in more academically-oriented sessions in a classroom setting focusing on basic skill development, while afternoon sessions involved STEM-oriented enrichment sessions involving media, art, and nutrition. Enrichment offerings varied by day, with math sessions occurring twice per week, alternating with academically oriented sessions in the am that were oriented at supporting skill development in English/language arts.</td>
</tr>
<tr class="odd">
<td align="left">Uptown Architecture</td>
<td align="left">An engineering-focused program that aims to support youth’s participation in a process to design and build an outdoor learning space for use at the middle school where the program was housed. A key focus of the program was to provide youth with the opportunity to use design thinking as a problem-solving tool and have the experience of affecting their community positively through the design/build process. Located in a classroom, building shop, and various field locations. 18 youth who were rising 6th to 9th graders. Youth attended programming in a classroom at an area middle school and in a building shop located at a community-based organization on alternating days, while also taking field trips to locations associated with the program’s overall theme.</td>
</tr>
<tr class="even">
<td align="left">Building Mania</td>
<td align="left">An engineering-focused program that aims to provide youth with the opportunity to experiment with designing and using simple machines. A goal of the program is to have youth engage in the engineering design process by determining a need, brainstorming possible designs, selecting a design, planning and drawing out the design, creating and testing and revising it, and producing a final machine. Located in the classroom, design labs, and other local locations. 24 youth who are rising 6th to 9th graders. Youth attended programming in a classroom at an area middle school and a field-based setting on alternating days. Field-based settings included a design lab at a community-based organization and field trips to sites in the community related to the program’s focus.</td>
</tr>
<tr class="odd">
<td align="left">Adventures in Mathematics</td>
<td align="left">A mathematics-focused program that aims to help youth to develop the basic math skills and prevent summer learning loss among participating youth through direct instruction and participation in math-related games. Located primarily in the classroom. 20 youth who are rising 8th to 10th graders. Youth participated in direct instructions in mathematics and math-related games in small groups. Program content was aligned with the state’s standards in mathematics.</td>
</tr>
</tbody>
</table>
</div>
<div id="appendix-research-question-1-additional-materials" class="section level3">
<h3><span class="header-section-number">11.2.4</span> Appendix: Research Question #1 additional materials</h3>
</div>
<div id="model-specifications-details" class="section level3">
<h3><span class="header-section-number">11.2.5</span> Model specifications details</h3>
<p>Here, the six models that are possible to specify in LPA are described in terms of how the variables used to create the profiles are estimated. Note that <em>p</em> represents different profiles and each parameterization is represented by a 4 x 4 covariance matrix and therefore would represent the parameterization for a four-profile solution. In all of the models, the means are estimated freely in the different profiles. Imagine that each row and column represents a different variable, i.e., the first row (and column) represents broad interest, the second enjoyment, the third self-efficacy, and the fourth another variable, i.e., future goals and plans. Models 1 and 3 meet the assumption of independence, that is, that, after accounting for their relations with the profile, the variables used to estimate the profiles are independent (Collins &amp; Lanza, 2010). They estimate variable variances but do not estimate covariances (i.e., as can be seen, the covariance matrices are “diagonal,” without any off-diagonal parameters that are estimated). These models are estimated by default in MPlus, although these assumptions can be relaxed (Muthen &amp; Muthen, 2017). Importantly, this does not mean the variables used to create the profile are assumed to be not related; as Collins and Lanza (2010) explain:</p>
<blockquote>
<p>The local independence assumption refers only to conditioning on the latent variable. It does not imply that in a data set that is to be analyzed, the observed variables are independent. In fact, it is the relations among the observed variables that are explained by the latent classes. An observed data set is a mixture of all the latent classes. Independence is assumed to hold only within each latent class, which is why it is called “local”.</p>
</blockquote>
<p>Despite the assumption of independence, as Collins and Lanza (2010), Muthen and Muthen (2017), and others (i.e., Pastor et al., 2007; Vermunt &amp; Magidson, 2002) note, it can be lifted to improve model fit, though these models without the assumption of independence may be better described as general or Gaussian mixture models (Fraley et al., 2017).</p>
<div id="varying-means-equal-variances-and-covariances-fixed-to-0-model-1" class="section level4">
<h4><span class="header-section-number">11.2.5.1</span> Varying means, equal variances, and covariances fixed to 0 (model 1)</h4>
<p>In this model, which corresponds to the mclust model wit the name “EEI”, the variances are estimated to be equal across profiles, indicated by the absence of a p subscript for any of the diagonal elements of the matrix. The covariances are constrained to be zero, as indicated by the 0’s between every combination of the variables. Thus, this model is highly constrained but also parsimonious: the profiles are estimated in such a way that the variables’ variances are identical for each of the profiles, and the relationships between the variables are not estimated. In this way, less degrees of freedom are taken used to explain the observations that make up the data. However, estimating more parameters–as in the other models–may better explain the data, justifying the addition in complexity that their addition involves (and their reduction in degrees of freedom).</p>
<p><span class="math display">\[
\left[ \begin{matrix} { \sigma  }_{ 1 }^{ 2 } &amp; 0 &amp; 0 &amp; 0 \\ 0 &amp; { \sigma  }_{ 2 }^{ 2 } &amp; 0 &amp; 0 \\ 0 &amp; 0 &amp; { \sigma  }_{ 3 }^{ 2 } &amp; 0 \\ 0 &amp; 0 &amp; 0 &amp; { \sigma  }_{ 4 }^{ 2 } \end{matrix} \right] 
\]</span></p>
</div>
<div id="varying-means-equal-variances-and-equal-covariances-model-2" class="section level4">
<h4><span class="header-section-number">11.2.5.2</span> Varying means, equal variances, and equal covariances (model 2)</h4>
<p>This model corresponds to the mclust model “EEE”. In this model, the variances are still constrained to be the same across the profiles, although now the covariances are estimated (but like the variances, are constrained to be the same across profiles). Thus, this model is the first to estimate the covariance (or correlations) of the variables used to create the profiles, thus adding more information that can be used to better understand the characteristics of the profiles (and, potentially, better explain the data).</p>
<p><span class="math display">\[
\left[ \begin{matrix} { \sigma  }_{ 1 }^{ 2 } &amp; { \sigma  }_{ 21 } &amp; { \sigma  }_{ 31 } &amp; { \sigma  }_{ 41 } \\ { \sigma  }_{ 12 } &amp; { \sigma  }_{ 2 }^{ 2 } &amp; { \sigma  }_{ 23 } &amp; { \sigma  }_{ 24 } \\ { \sigma  }_{ 13 } &amp; { \sigma  }_{ 12 } &amp; { \sigma  }_{ 3 }^{ 2 } &amp; { \sigma  }_{ 33 } \\ { \sigma  }_{ 14 } &amp; { \sigma  }_{ 12 } &amp; { \sigma  }_{ 12 } &amp; { \sigma  }_{ 4 }^{ 2 } \end{matrix} \right] 
\]</span></p>
</div>
<div id="varying-means-varying-variances-and-covariances-fixed-to-0-model-3" class="section level4">
<h4><span class="header-section-number">11.2.5.3</span> Varying means, varying variances, and covariances fixed to 0 (model 3)</h4>
<p>This model corresponds to the mclust model “VVI” and allows for the variances to be freely estimated across profiles. The covariances are constrained to zero. Thus, it is more flexible (and less parsimonious) than model 1, but in terms of the covariances, is more constrained than model 2.</p>
<p><span class="math display">\[ 
\left[ \begin{matrix} { \sigma  }_{ 1p }^{ 2 } &amp; 0 &amp; 0 &amp; 0 \\ 0 &amp; { \sigma  }_{ 2p }^{ 2 } &amp; 0 &amp; 0 \\ 0 &amp; 0 &amp; { \sigma  }_{ 3p }^{ 2 } &amp; 0 \\ 0 &amp; 0 &amp; 0 &amp; { \sigma  }_{ 4p }^{ 2 } \end{matrix} \right] 
\]</span></p>
</div>
<div id="varying-means-varying-variances-and-equal-covariances-model-4" class="section level4">
<h4><span class="header-section-number">11.2.5.4</span> Varying means, varying variances, and equal covariances (model 4)</h4>
<p>This model, which specifies for the variances to be freely estimated across the profiles and for the covariances to be estimated to be equal across profiles, extends model 3. Unfortunately, this model cannot be specified with mclust, though it can be with MPlus; this model <em>can</em> be used with the functions to interface to MPlus described below.</p>
<p><span class="math display">\[
\left[ \begin{matrix} { \sigma  }_{ 1p }^{ 2 } &amp; { \sigma  }_{ 21 } &amp; { \sigma  }_{ 31 } &amp; { \sigma  }_{ 41 } \\ { \sigma  }_{ 12 } &amp; { \sigma  }_{ 2p }^{ 2 } &amp; { \sigma  }_{ 23 } &amp; { \sigma  }_{ 24 } \\ { \sigma  }_{ 13 } &amp; { \sigma  }_{ 12 } &amp; { \sigma  }_{ 3p }^{ 2 } &amp; { \sigma  }_{ 33 } \\ { \sigma  }_{ 14 } &amp; { \sigma  }_{ 12 } &amp; { \sigma  }_{ 12 } &amp; { \sigma  }_{ 4p }^{ 2 } \end{matrix} \right] 
\]</span></p>
</div>
<div id="varying-means-equal-variances-and-varying-covariances-model-5" class="section level4">
<h4><span class="header-section-number">11.2.5.5</span> Varying means, equal variances, and varying covariances (model 5)</h4>
<p>This model specifies the variances to be equal across the profiles, but allows the covariances to be freely estimated across the profiles. Like model 4, this model cannot be specified with mclust, though it can be with MPlus. Again, this model <em>can</em> be used with the functions to interface to MPlus described below.</p>
<p><span class="math display">\[
\left[ \begin{matrix} { \sigma  }_{ 1 }^{ 2 } &amp; { \sigma  }_{ 21p } &amp; { \sigma  }_{ 31p } &amp; { \sigma  }_{ 41p } \\ { \sigma  }_{ 12p } &amp; { \sigma  }_{ 2 }^{ 2 } &amp; { \sigma  }_{ 23p } &amp; { \sigma  }_{ 24p } \\ { \sigma  }_{ 13p } &amp; { \sigma  }_{ 12p } &amp; { \sigma  }_{ 3 }^{ 2 } &amp; { \sigma  }_{ 33p } \\ { \sigma  }_{ 14p } &amp; { \sigma  }_{ 12p } &amp; { \sigma  }_{ 12p } &amp; { \sigma  }_{ 4 }^{ 2 } \end{matrix} \right] \quad 
\]</span></p>
</div>
<div id="varying-means-varying-variances-and-varying-covariances-model-6" class="section level4">
<h4><span class="header-section-number">11.2.5.6</span> Varying means, varying variances, and varying covariances (model 6)</h4>
<p>This model corresponds to the mclust model “VVV”. It allows the variances and the covariances to be freely estimated across profiles. Thus, it is the most complex model, with the potential to allow for understanding many aspects of the variables that are used to estimate the profiles and how they are related. However, it is less parsimonious than all of the other models, and the added parameters should be considered in light of how preferred this model is relative to those with more simple specifications.</p>
<p><span class="math display">\[
\left[ \begin{matrix} { \sigma  }_{ 1p }^{ 2 } &amp; { \sigma  }_{ 21p } &amp; { \sigma  }_{ 31p } &amp; { \sigma  }_{ 41p } \\ { \sigma  }_{ 12p } &amp; { \sigma  }_{ 2p }^{ 2 } &amp; { \sigma  }_{ 23p } &amp; { \sigma  }_{ 24p } \\ { \sigma  }_{ 13p } &amp; { \sigma  }_{ 12p } &amp; { \sigma  }_{ 3p }^{ 2 } &amp; { \sigma  }_{ 33p } \\ { \sigma  }_{ 14p } &amp; { \sigma  }_{ 12p } &amp; { \sigma  }_{ 12p } &amp; { \sigma  }_{ 4p }^{ 2 } \end{matrix} \right] 
\]</span></p>
</div>
</div>
<div id="model-1-candidate-solutions" class="section level3">
<h3><span class="header-section-number">11.2.6</span> Model 1 candidate solutions</h3>
<div id="model-1-profiles-3" class="section level4">
<h4><span class="header-section-number">11.2.6.1</span> Model: 1, Profiles: 3</h4>
<p>This solution is characterized by:</p>
<ul>
<li>a <strong>full</strong> profile, profile 2 (though with more modestly high levels of challenge)</li>
<li>a <strong>universally low</strong> profile, profile 1 (again with more modestly - in this case low - levels of challenge)</li>
<li>an <strong>all moderate</strong> profile, profile 3, characterized by levels of all of the variables close to the mean, profile 3</li>
</ul>
<p>The number of observations associated with each of the profiles is somewhat balanced, with the all moderate profile demonstrating a higher number of observations (<em>n</em> = 1,288) than the full (<em>n</em> = 897) and universally low (<em>n</em> = 773) profiles. The log-likelihood was replicated many (more than 10) times. Because the profiles associated with this solution all demonstrated the same overall pattern (i.e., all five variables are high, low, or moderate), on the basis of interpretability, this particular solution may not be useful in terms of understanding how youth experience engagement and its conditions.</p>
<!-- While replicated, the lowest log-likelihood associated with this solution demonstrated a very large decrease in the log-likelihood relative to those associated with the 2nd, 3rd, and 4th lowest log-likelihood solutions. This could suggest that the model is under-identified (Asparouhov & Muthen, 2012). -->
<p><img src="rosenberg-dissertation_files/figure-html/m1_3p-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="model-1-profiles-4" class="section level4">
<h4><span class="header-section-number">11.2.6.2</span> Model: 1, Profiles: 4</h4>
<p>This solution is characterized by:</p>
<ul>
<li>a <strong>full</strong> profile, profile 2</li>
<li>a <strong>universally low</strong> profile, profile 1</li>
<li>an <strong>all moderate</strong> profile, profile 3.</li>
<li>a <strong>competent but not engaged or challenged</strong> profile, with high levels of competence and low levels of engagement and challenge</li>
</ul>
<p>Most profiles are in the all moderate profile (<em>n</em> = 1,288), with a large number in the full (<em>n</em> = 920) profile, and fewer in the universally low and competent (<em>n</em> n = 427) but not engaged or challenged profiles (<em>n</em> = 415). With somewhat more purchase in terms of its interpretability than the solution for model 1 with three profiles, like that solution, this one may not be as useful as more complex models for understanding youth’s experiences.</p>
<p>The log-likelihood was replicated many (more than 10) times.</p>
<p><img src="rosenberg-dissertation_files/figure-html/m1_4p-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="model-1-profiles-5" class="section level4">
<h4><span class="header-section-number">11.2.6.3</span> Model: 1, Profiles: 5</h4>
<p>This solution is characterized by:</p>
<ul>
<li>a <strong>full</strong> profile, profile 5</li>
<li>a <strong>universally low</strong> profile, profile 3</li>
<li>an <strong>all moderate</strong> profile, profile 3, though with moderate levels of affective engagement than in similar profiles associated with the four and five profile solutions, perhaps suggesting that a different profile than in those solutions</li>
<li>an <strong>only behavioral</strong> profile, profile 2, with moderate levels of behavioral engagement, very low affective engagement, and moderately (low) levels of cognitive engagement and challenge and competence</li>
<li>an <strong>only affective</strong> profile, profile 4, with moderate levels of affective engagement, low levels of behavioral engagement, and moderately (low) levels of cognitive engagement and challenge and competence</li>
</ul>
<p>The number of observations associated with each of the profiles is somewhat balanced, with a large number in the full profile (<em>n</em> = 928), a moderate number of observations in the universally low (<em>n</em> = 667) and all moderate (<em>n</em> = 643) profiles, and fewer observations in the only behaviorally engaged (<em>n</em> = 375) and only affective engaged (<em>n</em> = 345) profiles. This solution primarily distinguishes between affective and behavioral engagement; unlike the solution for model 1 with four profiles, there is not a competent but not engaged or challenged profile. This may suggest that solutions with a greater number of profiles represents both the distinction between behavioral and affective engagement highlighted by profiles in this solution as well as profiles that are characterized by higher or lower levels of the conditions for engagement (i.e., competence). The log-likelihood was replicated four times.</p>
<p><img src="rosenberg-dissertation_files/figure-html/m1_5p-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="model-1-profiles-6-alternate" class="section level4">
<h4><span class="header-section-number">11.2.6.4</span> Model: 1, Profiles: 6 (alternate)</h4>
<p>This solution is characterized by:</p>
<ul>
<li>a <strong>full</strong> profile, profile 6</li>
<li>a <strong>universally low</strong> profile, profile 1</li>
<li>an <strong>engaged and competent but not challenged</strong> profile, profile 3</li>
<li>a <strong>challenged</strong> profile, profile 2</li>
<li>a <strong>highly challenged</strong> profile, profile 3</li>
<li>a <strong>moderately low</strong> profile, profile 5</li>
</ul>
<p>The number of observations are not very balanced, with the moderately low profile with a large number of observations (<em>n</em> = 852) and the challenged, engaged and competent but not challenged, and full profiles with moderate numbers of observations (from 464 to 619 observations), and low numbers of observations exhibited by universally low (<em>n</em> = 280) and highly challenged (<em>n</em> = 158) profiles. This–and, critically, the lower log-likelihood of the other model 1, six profile solution–suggests that this solution is not preferred. However, the very different profiles that emerge for this solution suggest that there might not be a somewhat under-identified solution associated with model 1 and six profiles.</p>
<p><img src="rosenberg-dissertation_files/figure-html/m1_6p-alt-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="model-1-profiles-7-alternate" class="section level4">
<h4><span class="header-section-number">11.2.6.5</span> Model: 1, Profiles: 7 (alternate)</h4>
<p>When investigating an alternate solution (associated with the second lowest log-likelihood) for the model 1, seven profile solution, we can see that even for the solutions associated with other log-likelihoods, the profiles that can be identified are very similar. One minor distinction concerns the <strong>competent but not engaged or challenged</strong> profile, which in the alternate solution is associated with neutral levels of affective engagement, compared to moderately low levels of affective engagement in the solution with the lowest log-likelihood. Because five of the seven profiles associated with both of these model 1, seven profile solutions seem to be distinct from those identified from simpler model 1 solutions, investigation of this alternate solution provides additional evidence that these profiles are not associated with an under-identified model and that simpler models may be preferred over these seven profile solutions.</p>
<p><img src="rosenberg-dissertation_files/figure-html/m1_7-other-LL-p-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="model-2-candidate-solutions" class="section level3">
<h3><span class="header-section-number">11.2.7</span> Model 2 candidate solutions</h3>
<div id="model-2-profiles-3" class="section level4">
<h4><span class="header-section-number">11.2.7.1</span> Model: 2, Profiles: 3</h4>
<p>This solution is characterized by:</p>
<ul>
<li>a <strong>universally low</strong> profile, profile 1, associated with moderate (low) and low levels of all of the variables; this profile is similar to the universally low profile identified as part of other solutions, although with more moderate values for some of the variables (especially cognitive engagement)</li>
<li>a <strong>competent but not challenged</strong> profile, profile 2, characterized by high competence and low challenge</li>
<li>a <strong>challenged</strong> profile, profile 3, characterized by very high challenge and moderate (high) levels of the other variables, similar to the challenged profile found as part of the model 1, four profile solution, but with higher levels of competence, which are moderately high in this solution but moderately low for the other solution.</li>
</ul>
<p>The number of observations associated with each solution is fairly balanced, with the most in the challenged profile (<em>n</em> = 1,241), followed by the universally low (<em>n</em> = 954 observations) and competent but not challenged (<em>n</em> = 763) profiles. This solution is very different than the three profile solution that was interpreted for model 1. Model 2 differs from model 1 in that covariances between the variables are estimated (they are constrained to be the same are across the profiles). The log-likelihood was replicated (at least) ten times. Thus, this and other solutions associated with model 2 include information about how the variables relate. Including this information seems to be associated with profiles that differentiate the groups on the basis of the levels of each of the variables in more distinct ways: the model 1, three profile solution was characterized by high, moderate, or low levels of all variables for each of the three profiles.</p>
<p><img src="rosenberg-dissertation_files/figure-html/m2_3p-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="model-2-profiles-4" class="section level4">
<h4><span class="header-section-number">11.2.7.2</span> Model: 2, Profiles: 4</h4>
<p>This solution is characterized by:</p>
<ul>
<li>a <strong>universally low</strong> profile, profile 1</li>
<li>a <strong>challenged</strong> profile, profile 2</li>
<li>a <strong>highly challenged</strong> profile, profile 4</li>
<li>an <strong>engaged and competent but not challenged</strong> profile, profile 3</li>
</ul>
<p>The number of observations in each of the profiles is not very balanced, with more than 1,000 observations in both the universally low (<em>n</em> = 1,029) and challenged (<em>n</em> = 1,106) profiles, a moderate number if the engaged and competent but not challenged profile (<em>n</em> = 688), and very few in the highly challenged (<em>n</em> = 135) profile. The log-likelihood was replicated three times. While each of these profiles has been identified in another solution, the small number of observations in the highly challenged profile suggests that this solution be interpreted with some skepticism because of the potentially limited utility (and statistical power associated with the use) of the profiles in subsequent analyses.</p>
<p><img src="rosenberg-dissertation_files/figure-html/m2_4p-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="model-2-profiles-5" class="section level4">
<h4><span class="header-section-number">11.2.7.3</span> Model: 2, Profiles: 5</h4>
<p>This solution is characterized by:</p>
<ul>
<li>a <strong>universally low</strong> profile, profile 1</li>
<li>a <strong>full</strong> profile, profile 4, although with very high levels of challenged (in addition to high levels of all of the other variables), making this profile similar to that (challenged) profile</li>
<li>a <strong>highly challenged</strong> profile, profile 5</li>
<li>an <strong>all moderate</strong> profile, profile 3, although with moderately lower levels of competence than is found in profiles associated with other solutions</li>
<li>a <strong>competent but not challenged</strong> profile, profile 2, similar to the competent but not challenged or engaged profile, but with neutral, rather than low, levels of the engagement variables</li>
</ul>
<p>The number of observations associated with each of the profiles is not very balanced, with a very large number of observations in the all moderate profile (<em>n</em> = 1,113) and a large number in the competent but not challenged profile (<em>n</em> = 871), a moderate number in the full profile (<em>n</em> = 573), and very few in the universally low (<em>n</em> = 271) and challenged but not competent (<em>n</em> = 130) profiles. The log-likelihood was replicated four times. Like for the model 2, four profile solution, the small number of observations associated with two of the profiles suggests that this solution should be interpreted with some caution.</p>
<p><img src="rosenberg-dissertation_files/figure-html/m2_5p-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="exploration-of-a-wide-range-of-models-a" class="section level3">
<h3><span class="header-section-number">11.2.8</span> Exploration of a wide range of models a</h3>
<p>First, I examined a wide range of model types (i.e., the parameterization of the model) and the numbers of profiles. Note that six model types are able to be specified. These roughly became more complex, with additional parameters estimated, as the number for the model type increases from one to six.</p>
<p>This step is taken to select candidate solutions to investigate in more detail. In order to carry out this analysis, I followed guidelines recommended by the developers of the MPlus software (Asparouhov &amp; Muthen, 2012; Muthen &amp; Muthen,dfs 2017) as well as those making recommendations about its use (Geiser, 2012). In particular, I set the number of starts to 600 for initial stage starts, and to 120 for the number of starts to be optimized. This means that for each model estimated, 600 random starting values for the parameters were used to initialize the EM algorithm. Of these 600, 120 that demonstrated the lowest log-likelihood were allowed to continue until they reached convergence or the limit for the number of iterations. In order for a model to me considered trustworthy, of these 120 runs, the lowest log-likelihood must be replicated at least one time.</p>
<p>If the log-likelihood is not replicated, then the estimation completed one or more times, but because the same log-likelihood value (and parameter estimates) were not obtained, then the solution can be considered to be “under-identified”, a term used to describe solutions that depend strongly upon minor fluctuations in the data (Asparouhov &amp; Muthen, 2007). Accordingly, these solutions may not represent meaningful values and may not be replicable in light of very small changes to the data; these are not considered as candidate solutions for use in subsequent analyses. If no log-likelihood is obtained for any of the random starts, then the software returns an error; in these cases, the convergence criteria–values that determine when a solution has been obtained–are not met. This may be due to a large number of parameters that are estimated relative to the data, such that the number of iterations that the estimation is allowed to go through are not sufficient to obtain a solution (Asparouhov &amp; Muthen, 2007). Like when the log-likelihood is not replicated, these solutions are not considered for use in subsequent analyses.</p>
<p>For every combination of models one through six and from two through ten profiles, only solutions associated with model specifications 1 and 2 (and among these two solutions, only those associated with particular number of profiles) converged. Thus, only solutions associated with models 1 (the model with varying means, equal variances, and covariances fixed to zero) and model 2 (varying means, equal variances, and equal covariances) are explored in subsequent sections. This suggests that the more complex models were too complex given the systematic variability in the data used for the analysis.</p>
</div>
<div id="in-depth-statistics-for-particular-models" class="section level3">
<h3><span class="header-section-number">11.2.9</span> In-depth statistics for particular models</h3>
<p>After investigating the general information about a range of model solutions, solutions associated with models 1 and 2 are explored in greater detail, following recommendations associated with mixture modeling (Collins and Lanza, 2009; Geiser, 2012) and the authors of the MPlus software (Muthen &amp; Muthen, 2017) as well as recent peer-reviewed articles (Pastor et al., 2007). For these models, the log-likelihood (LL), a range of information criteria (AIC, BIC, sample adjusted BIC [SABIC], consistent AIC [CAIC]), statistics about the quality of the profile assignments (entropy, which represents the mean posterior probability) are presented.</p>
<p>The information criteria are based on the log-likelihood but take various steps to penalize complex models, and so can be used to directly compare models (i.e., the model with the lowest values for these statistics can be considered to better reflect the underlying properties of the profiles). Simulation studies have suggested that BIC, CAIC, SABIC, and BLRT are most helpful for selecting the correct number of profiles (Nylund, Asparouhov, &amp; Muthen, 2007). For the entropy statistic, higher values are considered better, though scholars have suggested that the entropy statistic not be used for model selection (Lubke &amp; Muthen, 2007).The log-likelihood should not be interpreted directly but is presented in conjunction with the information criteria for context about how each of them differs from the log-likelihood. These are also presented in the figures.</p>
<p>In addition to these statistics, a number of modified likelihood ratio tests (LRTs) are used, as the test statistics associated with unmodified LRT do not follow the distribution that the test is based on (Muthen &amp; Muthen, 2017). These are the Vu-Lo-Mendell-Rubin LRT, Lo-Mendell-Rubin LRT, and the bootstrapped LRT. Of the three, the bootstrapped is considered to be the best indicator of which of two models, one nested (with certain parameters fixed to 0) within the other, fits better, but it is also the most computationally-intensive to carry out (Asparouhov &amp; Muthen, 2012). For each of the LRTs, the test statistic and its associated p-value are provided; a p-value greater than .05 suggests that the model with fewer profiles should be preferred.</p>

<div class="figure" style="text-align: center"><span id="fig:model1"></span>
<img src="rosenberg-dissertation_files/figure-html/model1-1.png" alt="Fit statistics for model 1 solutions" width="50%" />
<p class="caption">
Figure 11.1: Fit statistics for model 1 solutions
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:model2"></span>
<img src="rosenberg-dissertation_files/figure-html/model2-1.png" alt="Fit statistics for model 2 solutions" width="40%" />
<p class="caption">
Figure 11.2: Fit statistics for model 2 solutions
</p>
</div>
<p>Looking across the statistics presented, some general ideas about which models are to be preferred emerge. Solutions are interpreted first for each model individually and then across models with the goal of choosing a smaller number of models to investigate in more detail.</p>
<p>For solutions associated with model 1, the decrease (indicating a preferred model) in information criteria becomes smaller as the number of profiles increases from 5 to 6 and 6 to 7. A solution associated with 8 profiles did not replicate the log-likelihood and the VLMR and LMR suggest that the solution associated with 9 profiles did not fit better than that with 8 profiles, suggesting that models with 7 or fewer profiles be preferred. Considering these models, the entropy statistic increases by a large amount between the solution associated with 4 and 5 profiles (and then decreases slightly between 5 and 6 and 6 and 7 profile solutions), suggesting (but not providing conclusive evidence) that models 5, 6, or 7 may be preferred. The bootstrapped LRT suggests that, until the log-likelihood is not replicated, every more complex model be selected. Taking these pieces of evidence into conclusion, for model 1, solutions associated with 4 through 7 may be considered in more depth, with an emphasis on solutions associated with profiles with 5 and 6 profiles on the basis of the slowing of the decrease in the information criteria associated with the solutions with greater profiles than these, and the increase in the entropy from 4 to 5 (and 6) profile solutions.</p>
<p>For solutions associated with model 2, only those associated with 2-5 profile solutions were associated with log-likelihoods that were replicated. For these four models, the log-likelihood decreased in a mostly consistent way, such that changes in the decrease are not as evident as those associated with model 1. The entropy statistic decreases from 2 to 3 profile solutions, increases from 3 to 4 profile solutions, and then decreases slightly from 4 to 5 profile solutions, providing some information that models associated with 4 profiles be preferred to the others. All of the LRTs suggest that the more complex model be selected, not providing clear information about which solutions are to be preferred. On the basis of these pieces of evidence, models with 3, 4, and 5 solutions may be considered in more depth. However, there is a lack of consistent evidence favoring more or less complex models.</p>
</div>
<div id="comparison-of-model-1-and-model-2-type-solutions" class="section level3">
<h3><span class="header-section-number">11.2.10</span> Comparison of model 1 and model 2 type solutions</h3>
<p>When looking across solutions, some overall patterns in terms of what profiles emerge and some directions for which models are to be selected for use in subsequent analysis can be identified. First, overall patterns are discussed. In the table, which profiles emerge from which solution is presented.</p>
<p>There is a wide range of profiles. Some appear very commonly, particularly those (full and universally low) characterized by high or low levels across all of the variables. Moderate profiles, both all moderate (characterized by moderately high levels across all of the variables) and moderately low (characterized by low levels across all of the variables), also appeared commonly, particularly for the solutions for model 1.</p>

<div id="model-type-1-profiles-7" class="section level4">
<h4><span class="header-section-number">11.2.10.1</span> Model type: 1, Profiles: 7</h4>
<p>This solution is characterized by:</p>
<ul>
<li>A <em>full</em> profile, profile 7</li>
<li>A <em>universally low</em> profile, profile 1</li>
<li>A <em>competent but not engaged or challenged</em> profile, profile 2, characterized by high competence and moderate (low) or low levels of engagement and challenge</li>
<li>A <em>moderately low</em> profile, profile 3, characterized by moderately low levels of all of the variables</li>
<li>A <em>challenged</em> profile, profile 4, characterized by high challenge, moderate (high) levels of engagement, and moderate (low) levels of competence</li>
<li>A <em>highly challenged</em> profile, profile 5, characterized by patterns similar to those of the challenged profile, but with higher challenge and with low levels of both engagement and challenge</li>
<li>A <em>challenged but not engaged or competent</em> profile, profile 6, characterized by low levels of challenge, and high levels of engagement and competence</li>
</ul>
<p>The number of observations associated with each of the profiles is not very balanced, with few (<em>n</em> = 181) observations associated with the universally low profile and few (<em>n</em> = 222) observations associated with the highly challenged profile. The number of observations associated with the other profiles ranged from 317 to 651. Distinct from other solutions, none of the other five profiles were found in the other model 1 solutions. Two pairs of the profiles–challenged and highly challenged and universally low and moderately low–exhibited similar patterns among the variables that were distinguished by different mean levels. The log-likelihood was replicated twice, with the next lowest log-likelihood being replicate four times, possibly warranting further investigation. Taken together, this solution raises questions about whether it may be too complex, possibly suggesting preference for model 1 five and six profile solutions.</p>
</div>
</div>
</div>
<div id="appendix-models-for-research-question-2-and-3-with-the-seven-profile-solution" class="section level2">
<h2><span class="header-section-number">11.3</span> Appendix: Models for research question #2 and #3 with the seven-profile solution</h2>
<!-- # Model start here -->
<!-- # Models start running here -->








</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="references.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/11-appendix.Rmd",
"text": "Edit"
},
"download": ["rosenberg-dissertation.pdf", "rosenberg-dissertation.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
