\documentclass[]{book}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Examining Work With Data in STEM Education Through the Lens of Engagement Theory: A Person-Oriented Approach Using an Experience Sampling Method},
            pdfauthor={Joshua M. Rosenberg},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{natbib}
\bibliographystyle{apalike}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{Examining Work With Data in STEM Education Through the Lens of
Engagement Theory: A Person-Oriented Approach Using an Experience
Sampling Method}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{Joshua M. Rosenberg}
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  \predate{\centering\large\emph}
  \postdate{\par}
  \date{2018-02-27}

\usepackage{booktabs}
\usepackage{longtable}

% \documentclass[]{msu-thesis}
% \usepackage{lmodern}
% \usepackage{amssymb,amsmath}
% \usepackage{ifxetex,ifluatex}
% \usepackage{fixltx2e} % provides \textsubscript
% \ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
%   \usepackage[T1]{fontenc}
%   \usepackage[utf8]{inputenc}
% \else % if luatex or xelatex
%   \ifxetex
%     \usepackage{mathspec}
%   \else
%     \usepackage{fontspec}
%   \fi
%   \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
% \fi
% % use upquote if available, for straight quotes in verbatim environments
% \IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% % use microtype if available
% \IfFileExists{microtype.sty}{%
% \usepackage{microtype}
% \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
% }{}
% \usepackage[margin=1in]{geometry}
% \usepackage{hyperref}
% \hypersetup{unicode=true,
%             pdftitle={Examining Work With Data in STEM Education Through the Lens of Engagement Theory: A Person-Oriented Approach Using an Experience Sampling Method},
%             pdfauthor={Joshua M. Rosenberg},
%             pdfborder={0 0 0},
%             breaklinks=true}
% \urlstyle{same}  % don't use monospace font for urls
% \usepackage{natbib}
% \bibliographystyle{apalike}
% \usepackage{longtable,booktabs}
% \usepackage{graphicx,grffile}
% \makeatletter
% \def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
% \def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
% \makeatother
% % Scale images if necessary, so that they will not overflow the page
% % margins by default, and it is still possible to overwrite the defaults
% % using explicit options in \includegraphics[width, height, ...]{}
% \setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% \IfFileExists{parskip.sty}{%
% \usepackage{parskip}
% }{% else
% \setlength{\parindent}{0pt}
% \setlength{\parskip}{6pt plus 2pt minus 1pt}
% }
% \setlength{\emergencystretch}{3em}  % prevent overfull lines
% \providecommand{\tightlist}{%
%   \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
% \setcounter{secnumdepth}{5}
% % Redefines (sub)paragraphs to behave more like sections
% \ifx\paragraph\undefined\else
% \let\oldparagraph\paragraph
% \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
% \fi
% \ifx\subparagraph\undefined\else
% \let\oldsubparagraph\subparagraph
% \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
% \fi
%
% %%% Use protect on footnotes to avoid problems with footnotes in titles
% \let\rmarkdownfootnote\footnote%
% \def\footnote{\protect\rmarkdownfootnote}
%
% %%% Change title format to be more compact
% \usepackage{titling}
%
% % Create subtitle command for use in maketitle
% \newcommand{\subtitle}[1]{
%   \posttitle{
%     \begin{center}\large#1\end{center}
%     }
% }
%
% %\setlength{\droptitle}{-2em}
% %  \title{Examining Work With Data in STEM Education Through the Lens of Engagement Theory: A Person-Oriented Approach Using an Experience Sampling Method}
% %  \pretitle{\vspace{\droptitle}\centering\huge}
% %  \posttitle{\par}
% %  \author{Joshua M. Rosenberg}
% %  \preauthor{\centering\large\emph}
% %  \postauthor{\par}
% %  \predate{\centering\large\emph}
% %  \postdate{\par}
% %  \date{2017-11-24}
% %
%
% \frontmatter
% %\pagenumbering{Roman}
% \newpage
%
% \newpage
%
% \pagebreak
%
% \pagebreak
%
%
% \usepackage{booktabs}
% \usepackage{amsthm}
% \makeatletter
% \def\thm@space@setup{%
%   \thm@preskip=8pt plus 2pt minus 4pt
%   \thm@postskip=\thm@preskip
% }
% \makeatother
% \setlength{\parindent}{4em}
% \setlength{\parskip}{0em}
%
% \title{Examining Work With Data in STEM Education Through the Lens of Engagement Theory: A Person-Oriented Approach Using an Experience Sampling Method
% }
% \author{Joshua M. Rosenberg}
% \fieldofstudy{Educational Psychology and Educational Technology}
% \dedication{This dissertation is dedicated to Katie.}
% \date{2018}
%
% %\
%
% %%%%%% MSU-THESIS stuff
% % \usepackage[T1]{fontenc}
% % \usepackage{newtxtext,newtxmath} % If they want Times we’ll give them Times
% % \usepackage{amsmath}
% % %
% % \usepackage[]{natbib}
% % \bibliographystyle{unified}
% %
% %
% % % If you need newlines in your title, you must use \protect\\
% % \title{Examining Work With Data in STEM Education Through the Lens of Engagement Theory: A Person-Oriented Approach Using an Experience Sampling Method}
% % \author{Joshua M. Rosenberg}
% % \fieldofstudy{Educational Psychology and Educational Technology}
% % \dedication{This dissertation is dedicated to Katie.}
% % \date{2018}
% % \usepackage{listings}
% % \lstset{language=TeX,basicstyle={\ttfamily}}
% % \usepackage{lipsum}
% % \usepackage{xcolor}
% % \usepackage{gb4e}
% %
% % %\usepackage[bookmarksopenlevel=2,bookmarks=true]{hyperref} % not needed but here for testing
% %
% % \counterwithin{exx}{chapter}
% % \singlegloss
% %
% % % Uncomment the next line for single spaced examples with gb4e
% % %\patchcommand{\exe}{\SingleSpacing}{}
% %
% % % This code is an example of how to set up a new list of
% % \newlistof{listoflistings}{lol}{List of Listings}
% % \newfloat[chapter]{listing}{lol}{Listing}
% % \newlistentry{listing}{lol}{0}
% % \renewcommand*{\cftlistingname}{Listing\space}
% % \renewcommand*{\cftlistingaftersnum}{\msucaptiondelim}
% \usepackage{booktabs}
% \usepackage{longtable}
% \usepackage{array}
% \usepackage{multirow}
% \usepackage[table]{xcolor}
% \usepackage{wrapfig}
% \usepackage{float}
% \usepackage{colortbl}
% \usepackage{pdflscape}
% \usepackage{tabu}
% \usepackage{threeparttable}
%
% \usepackage{amsthm}
% \newtheorem{theorem}{Theorem}[section]
% \newtheorem{lemma}{Lemma}[section]
% \theoremstyle{definition}
% \newtheorem{definition}{Definition}[section]
% \newtheorem{corollary}{Corollary}[section]
% \newtheorem{proposition}{Proposition}[section]
% \theoremstyle{definition}
% \newtheorem{example}{Example}[section]
% \theoremstyle{definition}
% \newtheorem{exercise}{Exercise}[section]
% \theoremstyle{remark}
% \newtheorem*{remark}{Remark}
% \newtheorem*{solution}{Solution}
% \begin{document}
% %\maketitle
%
% \maketitlepage
% % Next make the abstract
% \begin{abstract}
% % Your abstract goes here.  Master's 1 page max. PhD 2 page max.
% This study will examine how 203 early adolescent learners work with data, or engage in activities focused on constructing measures of and modeling data, in the context of STEM summer enrichment programs. Video recordings of programs will be coded to identify the presence of five aspects of learners’ work with data: asking questions or identifying problems, constructing measures, collecting data, accounting for variability or uncertainty, and interpreting and communicating findings. Additionally, measures of instructional support for such practices will be used, so codes for work with data with instructional support are also created. Youth’s responses to the Experience Sampling Method (ESM) will be used to examine their cognitive, behavioral, and affective engagement as well as their perceptions of challenge and competence. A person-oriented analytic approach will be used to identify profiles of engagement that will help us to understand how learners engage in work with data. Examining work with data in terms of contemporary engagement theory can help us to understand these key STEM activities in terms of learner's experience, which past research suggests impacts student learning, yet which has not been brought to bear on the topic of work with data. Knowing more about students’ engagement can help us to design activities and interventions around work with data that are highly engaging to students and that support their capabilities to work with data.
%
% \end{abstract}
%
% % Force a newpage
% \clearpage
% % Make the copyright page. The Graduate School ridiculously prohibits you
% % from having a copyright page unless you pay ProQuest to register the copyright.
% % This should be illegal, but I didn't make up the rule.
%
% \makecopyrightpage
%
% % If you have a dedication page, uncomment the next command to print the dedication page
% %
% \makededicationpage
% %
% \clearpage
%
% % Your Acknowledgements are formatted like a chapter, but with no number
% \chapter*{Acknowledgements}
% \DoubleSpacing % Acknowledgements should be double spaced
% First, I would like to acknowledge my advisor and dissertation co-director Matthew Koehler and my dissertation co-director Jennifer Schmidt.
% \clearpage
%
% % We need to turn single spacing back on for the contents/figures/tables lists
% \SingleSpacing
% \tableofcontents* % table of contents will not be listed in the TOC
% \clearpage
% \listoftables % comment this out if you have no tables
% \clearpage
% \listoffigures % comment this out if you have no figures
% \mainmatter
% % If you have a list of abbreviations/symbols it would go here preceded by a \clearpage
% % See the class documentation and the Memoir manual for how to create other lists
% %
%
% \chapter{Introduction}\label{intro}
%
% \section{Background}\label{background}
%
% \DoubleSpacing
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage[table]{xcolor}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage[normalem]{ulem}

\usepackage{amsthm}
\newtheorem{theorem}{Theorem}[chapter]
\newtheorem{lemma}{Lemma}[chapter]
\theoremstyle{definition}
\newtheorem{definition}{Definition}[chapter]
\newtheorem{corollary}{Corollary}[chapter]
\newtheorem{proposition}{Proposition}[chapter]
\theoremstyle{definition}
\newtheorem{example}{Example}[chapter]
\theoremstyle{definition}
\newtheorem{exercise}{Exercise}[chapter]
\theoremstyle{remark}
\newtheorem*{remark}{Remark}
\newtheorem*{solution}{Solution}
\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\chapter{Front Matter}\label{front-matter}

\subsection{Dedication}\label{dedication}

This dissertation is dedicated to Katie.

\subsection{Acknowledgments}\label{acknowledgments}

First, I would like to acknowledge my advisor and dissertation
co-director Matthew Koehler and my dissertation co-director Jennifer
Schmidt.

\subsection{Abstract}\label{abstract}

This study will examine how 203 early adolescent learners work with
data, or engage in activities focused on constructing measures of and
modeling data, in the context of STEM summer enrichment programs. Video
recordings of programs will be coded to identify the presence of five
aspects of learners' work with data: asking questions or identifying
problems, constructing measures, collecting data, accounting for
variability or uncertainty, and interpreting and communicating findings.
Additionally, measures of instructional support for such practices will
be used, so codes for work with data with instructional support are also
created. Youth's responses to the Experience Sampling Method (ESM) will
be used to examine their cognitive, behavioral, and affective engagement
as well as their perceptions of challenge and competence. A
person-oriented analytic approach will be used to identify profiles of
engagement that will help us to understand how learners engage in work
with data. Examining work with data in terms of contemporary engagement
theory can help us to understand these key STEM activities in terms of
learner's experience, which past research suggests impacts student
learning, yet which has not been brought to bear on the topic of work
with data. Knowing more about students' engagement can help us to design
activities and interventions around work with data that are highly
engaging to students and that support their capabilities to work with
data.

\chapter{Introduction}\label{intro-placemarker}

Changes in how we plan our day-to-day lives, communicate, and learn are
increasingly impacted by data. These sources of data are created by us,
for us, and about us, although at present opportunities for learners to
analyze data in educational settings remain limited. Data analysis
includes processes of collecting, creating, modeling data, and asking
questions that may be answered with data and making sense of findings.
Analyzing data in educational settings, then, is more than just
crunching numbers or interpreting a figure created by someone else, but
rather is about making sense of phenomena and problem solving (Wild \&
Pfannkuch, 1999). Data analysis and its processes cut across STEM
domains and are recognized as core competencies in both the Next
Generation Science Standards and the Common Core State Standards
(National Governors Association Center for Best Practices, Council of
Chief State School Officers, 2010; NGSS Lead States, 2013). Scholars
have pointed out the benefits of analyzing data for learners as young as
two years old (Gopnik, \& Sobel, 2000).

In supporting teachers and learners' data analysis efforts, some
scholars have focused on the process of key data analytic practices,
particularly the practices of generating measures of phenomena and
creating data models---as an organizing activity in science and
mathematics content areas (English, 2012; Lehrer \& Romberg, 1996; Lesh,
Middleton, Caylor, \& Gupta, 2008). Findings from this area of research
suggest that engaging in these practices ``has an exceptionally high
payoff in terms of students' scientific reasoning'' (Lehrer \& Schauble,
2015, p.~696) and can highlight the utility of mathematics for students'
lives (Lesh, Middleton, Caylor, \& Gupta, 2008).

While scholars have looked at cognitive outcomes and learners'
capability to participate in specific, key aspects of data analysis as
well as strategies to address key challenges of doing so, we have not
yet examined key data analytic practices in terms of engagement theory.
Contemporary engagement theory offers a framework with which to
understand learners' experience of engaging in these practices, referred
to as work with data in the remainder of this study because it considers
multiple dimensions of experiencing engagement and its dynamic nature
(Fredricks \& McColskey, 2012). Scholars commonly consider engagement in
terms of its cognitive (i.e., use of meta-cognitive learning
strategies), behavioral (hard work on a task), and affective dimensions
(enjoyment; Fredricks, Blumenfeld, \& Paris, 2004; Sinatra, Heddy, \&
Lombardi, 2015; Skinner \& Pitzer, 2012).

In recognition of its dynamic nature, some engagement scholars have
usefully drawn upon flow theory (Csikszentmihalyi, 1990, 1997) to
identify how learners' perceived competence and challenge act as key
conditions of engagement (Shernoff, Kelly, Tonks, Anderson, Cavanagh,
Sinha, \& Abdi, 2016), aligning with situated views of learning (Sfard,
1998) and motivation (Nolen, Horn, \& Ward, 2015).

The purpose of this study, then, is to understand learners' experience
of engagement in work with data and the conditions that support it.
Engagement is understood in terms of cognitive, behavioral, and
affective dimensions, and the conditions that support engagement are
understood in terms of two subjective components that past research and
theory suggest influence engagement: perceived challenge and perceived
competence, as well as instructional support for engaging in aspects of
work with data. Engagement in work with data is explored in the context
of outside-of-school STEM enrichment programs carried out during the
summer. In recognition of the challenge of studying engagement in
learning environments where factors related to activities, learners, and
each of the nine programs all interact at the same time, this study uses
a methodological approach suited to studying engagement as a dynamic,
multi-faceted experience. Specifically, this study employs the
Experience Sampling Method (ESM; Hektner, Schmidt, \& Csikszentmihalyi,
2007) where learners answer short questions about their experience when
signaled. This approach is both sensitive to changes in engagement over
time, as well as between learners and allows us to understand engagement
and how factors impact it in more nuanced and complex ways (Turner \&
Meyer, 2000).

\chapter{Literature Review}\label{literature-review}

What is data analysis and what has past research taught us about it?
This section defines data analysis as a key practice across STEM
domains, with a focus on work with data as activities that are both very
specific to work with data (i.e., constructing measures and data
modeling) and activities that are more general across STEM domains
(i.e., asking questions and interpreting findings). This section also
reviews gaps in the literature and introduces engagement and
``influencers'' of engagement, or factors that past research indicates
can impact learners' engagement, to establish the conceptual framework
used in the present study.

\section{Defining Work With Data}\label{defining-work-with-data}

As described in the introduction to this section, some scholars have
focused on a few key pieces of data analysis connected through the use
of ``data to solve real problems and to answer authentic questions''
(Hancock et al., 1992, p.~337). This approach is commonly described as
including two goals: 1) creating data through constructing measures and
collecting data and 2) accounting for variability in data through
models, or data modeling (English, 2012; Hancock et al., 1992; Lehrer \&
Romberg, 1996; Lesh et al., 2008). This approach has primarily been
taken up by mathematics educators and is reflected in statistics
curriculum documents (Franklin et al., 2007). In science settings, where
answering questions about phenomena serve as the focus of activities, it
shares features of the process of engaging in scientific and engineering
practices but has been less often studied.

Scholars have conceived of working with data in different ways, but some
core components have emerged. For instance, Wild and Pfannkuch (1999)
consider the process in terms of identifying a problem, generating a
measurement system and sampling plan, collecting and cleaning the data,
exploring the data and carrying out planned analyses, and interpreting
the findings from the analysis. Such a process is common in STEM content
areas, particularly across statistics education research and is
instantiated in standards for curricula: Franklin et al.'s guidelines
for the American Statistical Association focus on the Framework for
statistical problem solving: formulating questions, collecting data,
analyzing data, and interpreting results (2007). The goals of this
framework and its components are similar to Hancock et al.'s (1992)
description of ``using data to solve real problems and to answer
authentic questions'' (p.~337). Scholars have subsequently expanded
Hancock et al.'s definition of to include six components: asking
questions, generating measures, collecting data, structuring data,
visualizing data, and making inferences in light of variability (see
Lehrer \& Schauble, 2004). The last of these components is crucial
across all of the visions of work with data reviewed here and
distinguishes these processes from other aspects of data analysis:
Accounting for variability (or uncertainty) is central to solving
real-world problems with data and the process of data modeling.

The five aspects of work with data. The definition of working with data
used in the present study represents a synthesis across these existing
accounts of this process and focuses on five aspects that are common to
them. Engagement in work with data, then, includes five processes that
are part of a cycle (Franklin et al., 2007; Lee \& Tran, 2015; Wild \&
Pfannkuch, 1999). Those processes are: asking questions or identifying
problems, making observations, generating data, data modeling (to
account for variability or uncertainty), and interpreting and
communicating findings.

The five practices depicted in Figure 1, are a cycle because not only
does each part follow that before it, but also because the overall
process is iterative: interpreting findings commonly leads to new
questions and subsequent engagement in work with data. The first
process, asking questions, is about generating questions that can be
answered with empirical evidence. The next, making observations is about
watching phenomena and noticing what is happening with respect to the
phenomena or problem being investigated. This is followed by generating
data, the process of figuring out how or why to inscribe an observation
as data about a phenomena, as well as generating coding frames or tools
for measuring. Next, because data are often messy, data modeling is a
necessary step follows from its creation or collection. Data models
include simple statistics, such as the mean and variance, as well as
more complicated models, such as linear models and extensions of the
linear model. Finally, the last step is to interpret and communicate
findings regarding the phenomena that the question is about.

\begin{center}\includegraphics[width=0.8\linewidth]{images/figure1} \end{center}

Also, as depicted in Figure 1, scholars have pointed out some key
features of how work with data is carried out that impact their
effectiveness as a pedagogical approach. These key features include an
emphasis on making sense of real-world phenomena and iterative cycles of
engaging in work with data and collaboration and dialogue, through which
ideas and intermediate findings are critiqued and subject to critique,
and revised over time (McNeill \& Berland, 2017). As we will discuss
later, these factors might have the potential to impact engagement
through the proximal conditions of challenge and competence.

The role of work with data in the curriculum. Scholars argue that work
with data can serve as an organizing set of practices for engaging in
inquiry in STEM settings (Lehrer \& Schauble, 2015). Data are both
encountered and generated by learners, and so opportunities for STEM
students to work with data provide many opportunities to leverage
students' curiosity because processes of inquiry can be grounded in
phenomena that learners themselves can see and manipulate or phenomena
that learners are interested in. Also important, becoming proficient in
work with data can provide learners with an in-demand capability in
society, owing to the number of occupations, from education to
entrepreneurship, that demand or involve taking action based on data
(Wilkerson \& Fenwick, 2017). Furthermore, becoming proficient in work
with data can be personally empowering because of the parts of our
lives---from paying energy bills to interpreting news articles---that
use data.

Recent reform efforts emphasize work with data (i.e., the scientific and
engineering practices in the NGSS and the standards for mathematical
practice in the Common Core State Standards). However, work with data is
uncommon in many classroom settings (McNeill \& Berland, 2017), and so
learning environments suited to engaging in work with data, but not
explicitly designed to support it, may be valuable to study because they
may serve as incubators of these rare and challenging learning
activities.

Work with data is related to what is commonly described as data analysis
in K-12 settings, though data analysis as described in curricular
standards and policy documents can take many forms: from learning about
what we already know to systematic efforts to measure large, small, or
hard to study phenomena. Data analysis includes both individual
cognitive processes, such as reasoning about what counts as a good
source of data and coordinated social processes, like sharing what is
found with others (Lovett \& Shah, 2007). Many policy and curricular
documents characterize data analysis as using data to explain or predict
phenomena (i.e., National Governors Association Center for Best
Practices, Council of Chief State School Officers, 2010; NGSS Lead
States, 2013). The range of capabilities included within data analysis
is large, ranging from collecting insufficient data to construct an
answer to a question, interpreting already-created figures or analyzing
already-collected data, and seeking to develop answers to questions that
are already known. In addition, teachers and other stakeholders do data
analysis in very different ways, with greater or lesser veracity to the
aims of data analysis (McNeill \& Berland, 2017). Thus, work with data
as defined in this study include both more specific aspects of data
analysis (constructing measures and data modeling) and more general
aspects, such as asking questions and interpreting findings.

Outside-of-school programs are a potentially valuable setting to explore
engagement in work with data because of the combined pedagogical and
technical expertise of their staff and the activities learners do during
their participation in them. Staff for these programs includes educators
and scientists, engineers, and others with the technical experience.
Additionally, the programs were designed to involve learners in the
types of real-world practices experienced by experts in STEM
disciplines. Attendance in such programs is associated with many
benefits to learners (Green, Lee, Constance, \& Hynes, 2013; see Lauer,
Akiba, Wilkerson, Apthorp, Snow, \& Martin-Glenn, 2006, for a
comprehensive review). These programs are also selected because little
research has examined how data are part of the experiences of youth in
out-of-school-time programs, despite its place as one of a few core
practices in STEM. While these reasons to study work with data focus on
outside-of-school programs, they are also germane to more formal
learning environments, such as classrooms, in which teachers want to
design opportunities for their learners to work with data. This is
important even for those teachers who themselves have technical
expertise, but who have experienced limited training and support for
engaging learners in work with data. Therefore, these programs can
provide insight into whether engaging in work with data is associated
with more optimal forms of engagement in the conditions like those for
classrooms in which engaging in work with data is a novel and
potentially promising approach to doing and learning about STEM.

\section{What We Know (And Do Not Know) About Engagement in Work with
Data}\label{what-we-know-and-do-not-know-about-engagement-in-work-with-data}

Research related to engagement in work with data has been carried out by
developmental and educational psychologists as well as by mathematics
and science educators (see Lehrer and Schauble, 2015, for a review).
This research has been carried out in laboratories and classroom
settings. For this study, key findings from past studies are organized
around three themes: 1. Specific cognitive outcomes 2. Learners'
capability to participate in each of the aspects of work with data 3.
Strategies to address key challenges of engaging in each of the aspects
of work with data

First, scholars have researched cognitive capabilities related to work
with data. Much of this laboratory-based research has focused on how
children develop the capability to inductively reason from observations
(Gelman \& Markman, 1987). Other research has focused on the development
of causal, or mechanistic, reasoning, among young children (Gopnik et
al., 2001; Gopnik \& Sobel, 2000), often from a Piagetian,
individual-development focused tradition (i.e., Piaget \& Inhelder,
1969). A key outcome of engaging in work with data has to do with how
learners account for variability (Lehrer, Kim, \& Schauble, 2007;
Petrosino, Lehrer, \& Schauble, 2003; Lesh, Middleton, Caylor, \& Gupta,
2008; Lee, Angotti, \& Tarr, 2010), arguably the main goal of engaging
in work with data (Konold \& Pollatsek, 2002). From this research, we
know that learners can develop the capacity to reason about variability
(and covariability).

Second, we know that different aspects of work with data pose unique
opportunities and challenges. Asking empirical questions requires
experience and ample time to ask a question that is both able to be
answered with data and which is sustaining and worth investigating
(Bielik, 2016; Hasson \& Yarden, 2012). Constructing measures, such as
of the height of the school's flagpole, requires negotiation not only of
what to measure, but how and how many times to measure it (Lehrer, Kim,
\& Schauble, 2007). Regarding modeling, not only teaching students about
models, such as that of the mean, but also asking them to create them,
are valuable and practical (Lehrer \& Schauble, 2004; Lehrer, Kim, \&
Jones, 2011), but also time-intensive. Interpreting findings, especially
in light of variability through models, and communicating answers to
questions, means not only identifying error but understanding its
sources, and can be supported through exploring models that deliberately
represent the data poorly, but can be instructive for probing the
benefits and weaknesses of models (Lee \& Hollebrands, 2008; Lehrer,
Kim, \& Schauble, 2007). In the context of these opportunities and
challenges, how learners participate in different aspects of work with
data in terms of engagement theory has not been a focus of research.
Consider the process of structuring data, commonly described as a---or
the---key part of many applied data analyses, that is also
under-emphasized in students' use of data in science settings in which
students are provided already-processed, or plotted, data (McNeill \&
Berland, 2017). How challenging do students perceive these activities to
be? How to they perceive their competence regarding this activity? More
importantly, how do they engage---cognitively, behaviorally, and
affectively---during these experiences? Knowing more about these
processes could help us to develop informed recommendations for teachers
and designers intending to bring about opportunities for learners to
engage in work with data in a better-supported way that is sustained
over time.

Third, strategies to support engagement in work with data have included
design of curricula, development of instructional strategies supported
through collaborations between researchers and teachers, and often,
technological tools. At present, opportunities for students to engage in
work with data, or analyze data to solve real problems and to answer
authentic questions, are limited in K-12 STEM settings. Much of the
research in science settings focuses on evidence use, which can include
data, but also includes other forms of evidence, such as those from
authoritative sources (McNeill \& Berland, 2016). Furthermore, creating
and constructing models of primary data takes ample time (Dickes,
Sengupta, Farris, \& Basu, 2016), and doing so even in mathematics
settings is uncommon (Lehrer \& Schauble, 2015). Furthermore, providing
opportunities for students to engage in work with data requires a shift
in educational norms and curricular resources, aligned standards and
assessments, and teacher professional development (McNeill \& Berland,
2017; Wilkerson-Jerde, Andrews, Shaban, Laina, \& Gravel, 2016). From
this research, we know about specific strategies and learning
progressions for learners to develop this capability, such as the role
of measurement in exposing learners in a direct way to sources of
variability (Petrosino et al., 2003), role of simulation to learn about
sampling distributions (Stohl \& Tarr, 2002), and use of relevant
phenomena, such as manufacturing processes, such as the size of metallic
bolts, which can help learners to focus on ``tracking a process by
looking at its output'' (Konold \& Pollatsek, 2002, p.~282).

\section{Engagement in STEM Domains}\label{engagement-in-stem-domains}

The nature of engagement is discussed in terms of general features that
have been identified across content area domains, conditions that
support engagement, and differences between engagement in general and in
STEM settings. This is followed by a discussion of two key features of
engagement: its dynamic characteristics and what a person-oriented
approach to its study can add to research about engagement and its
impact on learning and other outcomes.

General characteristics of engagement. Engagement is defined in this
study as active involvement, or investment, in activities (Blumenfeld et
al., 2004). Explaining how learners are involved in activities and tasks
is especially important if we want to know about what aspects of work
with data are most engaging (and in what ways), and therefore can serve
as exemplary for others advancing work with data as well as those
calling for greater support for engagement. Apart from being focused on
involvement, engagement is often thought of as a meta-construct, that
is, one that is made up of other constructs (Skinner \& Pitzer, 2012;
Skinner, Kindermann, \& Furrer, 2009). By defining engagement as a
meta-construct, scholars characterize it in terms of cognitive,
behavioral, and affective dimensions that are distinct yet interrelated
(Fredricks, 2016). We know from past research that the cognitive,
behavioral, and affective dimensions of engagement can be distinguished
(Wang \& Eccles, 2012; Wang \& Holcombe, 2012) and that while there are
long-standing concerns about the conceptual breadth of engagement
(Fredricks et al., 2016), careful justification and thoughtful use of
multidimensional engagement constructs and measures is warranted based
on past research.

Recent scholarship has summarized key characteristics of engagement and
outcomes from being engaged at school and in other learning environments
(Fredricks, 2016), defined for STEM domains in the next section.
Engagement is also considered to be dynamic and changing in response to
individual, situation or moment, and broader contextual factors, such as
the family, classroom, or outside-of-school programs. Many
conceptualizations of engagement include cognitive, behavioral, and
affective dimensions, but the contents of these dimensions can vary
across domains, as discussed in the next section about STEM content
areas.

Characteristics of engagement in STEM domains. Engagement in STEM
settings shares characteristics with engagement across disciplines, yet
there are some distinct aspects of it (Greene, 2015). While one type of
engagement---behavioral---is associated with positive outcomes, many
STEM practices call for engagement in additional ways (Sinatra et al.,
2015), especially around epistemic and agency-related dimensions. For
example, many scholars have defined scientific and engineering practices
as epistemic practices, which involve applying epistemic considerations
around sources of evidence and the nature of explanatory processes
(Berland et al., 2016; Stroupe, 2014). The emphasis on developing new
knowledge and capabilities through engaging in STEM practices is a
potentially important aspect. This is important because measures of
engagement might need to be modified for use in STEM domains. Because of
the importance of constructing knowledge to engagement in STEM
practices, then, cognitive engagement is defined for this study in terms
of learning something new or getting better at something.

The behavioral and affective aspects of engagement in STEM settings are
arguably more similar to engagement in general than cognitive
engagement. While sometimes defined in terms of extra-curricular
involvement or following directions, behavioral engagement is defined in
this study as working hard at and concentrating on learning-related
activities (Fredricks et al., 2004; Singh, Granville, \& Dika, 2002).
Finally, affective engagement is defined as affective responses to
activities, such as being excited, angry, or relaxed (Pekrun \&
Linnenbrink-Garcia, 2012).

Key conditions that support engagement. In particular for
engagement---about involvement in activities---past research has shown
that ESM can help us to find out what conditions support it. Past
research suggests that not only learner-level characteristics, such as
learners' interest in the domain of study, but also dynamic, changing
moment-to-moment conditions are also important (Shernoff et al., 2003;
Shernoff et al., 2016; Shumow, Schmidt, \& Zaleski, 2013). Focusing on
dynamic conditions, Emergent Motivation Theory (EMT; Csikszentmihalyi,
1990), provides a useful lens. From EMT, a key momentary influencer of
engagement is how difficult individuals perceive an activity to be, or
its perceived challenge. Another key influencer is how good at an
activity individuals perceive themselves to be, or their perceived
competence. Most important, from the perspective of EMT, being
challenged by and good at an activity are especially engaging
experienced when together. Past research has supported this contention.
Shernoff et al. (2016), for example, demonstrated that while challenge
and skill with high levels of one but low levels on the other (i.e.,
high challenge and low skill) were not broadly associated with positive
forms of engagement, their interaction was, suggesting that learners'
perceptions of the challenge of the activity, and their perceptions of
how skillful they are, are important for explaining why learners engage.

Other key conditions that support engagement concern teacher support
(Strati, Schmidt, \& Maier, 2017). Particularly concerning work with
data, which is demanding not only for learners but also teachers,
sustained support from teachers is an essential component of learners
being able to work with data (Lehrer \& Schauble, 2015; Wilkerson,
Andrews, Shaban, Laina, \& Gravel, 2016). Consequently, this study
considers not only profiles of engagement, but also the conditions of
engagement as part in terms of both learners' subjective experiences and
support from the instructors. The conditions included in the PECs relate
to learners' subjective perceptions of two key factors suggested by past
research and theory, in particular, how challenging they perceive the
activity to be and how good at it they perceive themselves to be
(Csikszentmihalyi, 1990). In recognition of differences among learners
in their tendency to engage in different (higher or lower) ways in
specific activities based in part on individual differences (Hidi \&
Renninger, 2006), learners' interest in STEM before the start of the
programs is also considered as a factor that can impact engagement.
Instructional support for work with data is also considered through the
creation of codes for activities in which students are involved with
data and the instructors are providing support for the activity in which
they are engaged. Finally, gender and the racial and ethnic group of
students is added, as past research has indicated these as factors that
influence engagement in STEM (Bystydzienski, Eisenhart, \& Bruning;
Shernoff \& Schmidt, 2008). These conditions are different from those
discussed in the section on the five aspects of work with data in that
they are teacher-related factors (with respect to instructional
support), subjective factors (with respect to perceptions of challenge
and competence), and demographic characteristics, whereas a focus on
real-world phenomena, iterative cycles, and collaboration and dialogue
may potentially impact engagement through learners' perceiving the
activity to be supported by the subjective contextual conditions of
challenge and competence.

\section{Using ESM to Study the Dynamics of
Engagement}\label{using-esm-to-study-the-dynamics-of-engagement}

A number of scholars, in recognition of the dynamic nature of
engagement, have explored the use of Experience Sampling Method (ESM) to
understand engagement (e.g., Strati et al., 2017)---or have recommended
it is as a valuable approach for doing so (Turner \& Meyer, 2000;
Sinatra et al., 2015). ESM involves asking---usually using a digital
tool and occasionally a diary---to ask participants short questions
about their experiences. ESM is particularly well-suited to
understanding the dynamic nature of engagement because students answered
brief surveys about their experience when they were signaled, minimally
interrupting them from the activity they are engaged in and also seeking
to collect measures about learners' experience when signaled (Hektner,
et al., 2007).

Research how shown us how the use of ESM can lead to distinct research
contributions. Shernoff, Csikszentmihalyi, Schneider, and Shernoff
(2003) examined engagement through the use of measures aligned with flow
theory, namely, using measures of concentration, interest, and enjoyment
(Csikszentmihalyi, 1997). In a study using the same measures of
engagement (concentration, interest, and enjoyment) Shernoff et al.
(2016) used an observational measure of challenge and control (or
environmental complexity) and found that it significantly predicted
engagement, as well as self-esteem, intrinsic motivation, and academic
intensity. Schneider et al. (2016) and Linnansaari et al. (2015)
examined features of optimal learning moments or moments in which
students report high levels of interest, skill, and challenge, as well
as their antecedents and consequences. Similar to ESM in that through
its use engagement can be studied in a more context-sensitive, still
other scholars have used daily diary studies to examine engagement as a
function of autonomy-supportive classroom practices (Patall, Vasquez,
Steingut, Trimble, \& Pituch, 2015; Patall, Steingut, Vasquez, Trimble,
\& Freeman, 2017). This past research that used ESM (or daily diary
studies) to study engagement has shown us that the methodological
approach can be used to answer questions that were hard to answer using
the more-traditional pre- or post-survey measures.

Other research shows us that there are newer approaches to analyzing ESM
data that can contribute insights into the dynamics of engagement in a
more fine-grained way. For example, Strati et al. (2017) explored the
relations between engagement to measures of teacher support, finding
associations between instrumental support and engagement and powerfully
demonstrating the capacity of ESM to understand some of the dynamics of
engagement. Similarly, Poysa et al. (2017) used a similar data analytic
approach as Strati et al. (2017), that is, use of crossed effects models
for variation within both students and time points, both within and
between days. These studies establish the value of the use of ESM to
understand the dynamics of engagement and that such an approach may be
able to be used to understand engaging in work with data. Additionally,
these studies show that how effects at different levels are treated,
namely, how variability at these levels is accounted for through random
effects as part of mixed effects models, is a key practical
consideration for analysts of ESM data.

\section{A Person-Oriented Approach to
Engagement}\label{a-person-oriented-approach-to-engagement}

One powerful and increasingly widely used way to examine dynamic
constructs holistically is a person-oriented approach, which can be used
to consider the way in which psychological constructs are experienced
together and at once in the experiences of learners. In the context of
the present study, this approach can help us to identify naturally
occurring profiles of engagement and its conditions that capture both
the cognitive, behavioral, and affective dimensions of engagement and
the subjective conditions of challenge and competence to understand how
students experience engagement and its conditions in a more holistic
way. The person-oriented view, developed within developmental science,
emphasizes these groups of constructs in light of the dynamic nature of
learning and development, and the importance of both person-level and
contextual factors upon these dynamics (Bergman \& El-Khouri, 1997;
Magnusson \& Cairns, 1996), though recent conceptions of the
developmental science approach sometimes differ in the extent to which
they acknowledge these contextual factors (Witherington, 2015). Though
studies examining learning from a person-oriented perspective are not
very common, some examples include studies of intrinsic and extrinsic
motivation (Corpus \& Wormington, 2014; Hayenga \& Corpus, 2010),
profiles of achievement goals (see Wormington \& Linnenbrink-Garcia,
advance online publication, for a review), and epistemic cognition
(Trevors, Kendeou, Braten, \& Braasch, 2017).

There are some recent studies taking a person-oriented approach to the
study of engagement (i.e., Salmela-Aro, Moeller, Schneider, Spicer, \&
Lavonen, 2016a; Salmela-Aro, Muotka, Alho, Hakkarainen, \& Lonka, 2016b;
Van Rooij, Jansen, \& van de Grift, 2017; Schmidt, Rosenberg, \& Beymer,
advance online publication). Van Rooij et al. (2017) identified five
secondary school student profiles, derived from three dimensions of
student engagement: behavioral engagement, cognitive engagement, and
intellectual engagement. Salmela-Aro et al. (2016b) examined burnout and
engagement using a person-oriented approach. While not using ESM, this
study demonstrated the use of a person-oriented approach including
(although not focused on profiles comprised exclusively of) engagement.
Examining the same variables (engagement and the three aspects of school
burn-out) and others, Salmela-Aro et al. (2016b) demonstrated
substantial differences in student momentary resources, demands, and
engagement across the four profiles and contributes to a rich
understanding of engagement in situ yet does not conduct profiles of
engagement at the momentary level.

Using profiles to account for the dynamics of a multidimensional
construct. The person-oriented approach has an important implication for
how we consider engagement, in particular when we consider how to
understand engagement as a meta-construct (Skinner, Kindermann, \&
Furrer, 2009) and how to account for its dynamic nature
(Csikszentmihalyi, 1990). Regarding engagement as a meta-construct, we
know from both engagement and person-oriented research that engagement
can be explained in terms of different patterns among its individual
components (Bergman \& Magnusson, 1997), in the present case its
cognitive, behavioral, and affective components. Because learners'
engagement includes cognitive, behavioral, and affective aspects
experienced together at the same time, it can be experienced as a
combined effect that is categorically distinct from the effects of the
individual dimensions of engagement. This combined effect can be
considered as profiles of engagement. Past studies have considered
profiles of cognitive, behavioral, and affective aspects of engagement.
For example, Schmidt et al. (advance online publication) demonstrated
how ESM and the person-oriented approach can be combined to learn about
engagement in terms of how cognitive, behavioral, and affective
engagement are experienced at once, and how they exhibit differences
across activities and learners' reports of the choices related to the
activity that they were able to make. Note that while the
person-oriented approach considers the relations among variables
together and at once in the experience of learners, they can also be
used as part of variable-oriented analyses, and in particular analyses
that account for how responses are nested within students, as in
repeated measures and longitudinal sources of data.

To account for the dynamic nature of engagement, some past studies have
used other measures to predict engagement, such as use of in-the-moment
resources and demands (Salmela-Aro et al., 2016b) or, in the case of the
study reviewed in the previous section, use of instructional activities
and choice (Schmidt et al., advance online publication). For example,
Schmidt et al. explored how in the case of laboratory-related
activities---especially those that learners perceived as offering them
greater choice in the goals of the activity---were associated with more
optimal profiles of momentary engagement. Using a person-oriented
approach and the use of profiles of cognitive, behavioral, and affective
engagement, this study suggests that laboratory related activities akin
to those characterized by work with data in which learners have to make
choices about how to carry out the analysis may be important predictors
of engagement. Another potential way to account for the dynamics of
engagement is to consider both engagement and its conditions at once.
Since a person-oriented approach emphasizes the dynamic nature of
development and the impact of not only external but also
intra-individual factors, momentary factors such as resources and
demands, could be used along with the measures of engagement to
construct momentary profiles.

\section{Need for the Present Study}\label{need-for-the-present-study}

While many scholars have argued that work with data can be understood in
terms of the capabilities learners develop and the outcome learners
achieve, there is a need to better understand learners' experience in
terms of contemporary engagement theory. Doing so can help us to
understand work with data in terms of learner's experience, which we
know from past research impacts what and how students learn (Sinatra et
al., 2015), yet which has not been brought to bear on the topic of
engagement in work with data. In particular, the use of ESM and a
person-oriented approach allow us to study engage in a way aligned with
how scholars have recently considered engagement, namely, as something
that is dynamic and as something that is multifaceted, including
multiple dimensions of engagement and the (subjective and
instruction-related) conditions that support engagement. Knowing more
about students' engagement can help us to design activities and
interventions focused around work with data that are more engaging and
which provide more support to learners in terms of their perceptions of
challenge and their own competence. While other lenses can be brought to
bear to better understand---and support---engagement in work with data,
contemporary engagement theory not only has the power to explain
differences in how students engage in data modeling, but it also aligns
with how both teachers and recent curricular standards consider
engagement.

In addition to this general need to study engagement in work with data
from the perspective of contemporary engagement theory, no research that
I am aware of has examined work with data or data analysis more
generally in the context of outside-of-school programs. These settings
are potentially rich with opportunities for highly engaged learners to
analyze authentic data sources. Third, little research has examined how
data is part of the experiences of youth in out-of-school-time programs,
despite its place as one of a few core practices in STEM. Fourth, this
study employs a data analytic approach that allows for accounting for
student, program, and momentary impacts on engagement, at this time an
approach that has only been conducted as part of two studies, Strati et
al. (2017) and Poysa et al. (2017). Fifth, most studies of engagement
have considered it in terms of the individual components of engagement,
rather than in terms of profiles of engagement.

\section{Conceptual Framework}\label{conceptual-framework}

The present study is about how engagement can be used to understand how
learners are involved in work with data and how characteristics of
activities and learners impact the relationships between work with data
and engagement. Its context is out-of-school-time STEM enrichment
programs designed to meet guidelines for best practices. The conceptual
framework in the present study is presented in Figure 2 and is unpacked
in the remainder of this section.

\begin{center}\includegraphics[width=0.8\linewidth]{images/figure2} \end{center}

There are five aspects of work with data synthesized from past research
(i.e., Hancock et al., 1992; Lehrer \& Romberg, 1996; Wild \& Pfannkuch,
1999): 1. Asking questions or identifying problems 2. Making
observations 3. Generating data 4. Data modeling 5. Interpreting and
communicating findings

In addition to these five aspects of work with data, two activities that
are not part of work with data will be coded so engagement in each
aspect of work with data can be compared to other during other times.
Other instructional activities, such as listening to a lecture by an
instructor, and other activities, such as activities characterized by
students being not focused on STEM, off-task, or unfocused.

In this figure, engagement in work with data is associated with
different profiles of engagement and its conditions (PECs). The
theoretical framework for the person-oriented approach suggests that
while the dynamics among the individual aspects of engagement emerge in
complex and situation-specific ways, it is possible to consider
engagement in terms of patterns among its components. In most settings,
a relatively small number of these patterns can be identified in most
developmental (and learning-related) settings (Bergman \& Magnusson,
1997) and these patterns can be considered in terms of profiles of
engagement (Schmidt et al., 2017).

In addition, a pre-program measure of learners' individual interest in
STEM is hypothesized to be associated with both the relationship between
learners' perception of the activity and themselves and the relationship
between the aspects of work with data and engagement because some
learners may be inclined from the start to be more engaged. This
inclination could explain some of the variability in relations between
engaging in work with data and the PECs. ESM responses are associated
with students, moments, and program effects that must be accounted for
(Strati et al., 2017). Each student in the same program was signaled at
the same time, so that each student will have a response associated with
each moment (within the same program), and each moment will have a
response associated with each student (again, within the same program).

\section{Research Questions}\label{research-questions}

The four research questions are as follows: 1. What profiles of
engagement and its conditions (PECs) emerge from the participants'
responses? 2. How does work with data relate to each PEC? a. How does
work with data, in general, relate to PEC? b. How do the specific
aspects of work with data (i.e., asking questions or identifying
problems, constructing measures, accounting for variability or
uncertainty, and interpreting and communicating findings), and other
activities that are not work with data, relate to each PEC? 3. How do
the relationships identified as part of answering research question \#2
differ depending on whether or not instructional support for work with
data was provided? a. How do the relationships between work with data,
in general, and PECs differ on the basis of instructional support for
work with data? b. How do the relationships between the specific aspects
of work with data and PECs differ on the basis of instructional support
for work with data? 4. Do the relationships between work with data and
the PECs vary depending on students' pre-program interest in STEM? a.
How do these relations differ for work with data on its own? b. How do
these relations differ for work with data with support? 5. What are the
common characteristics of potentially adaptive PECs beyond the presence
of the aspects of work with data and other activities or the
characteristics of learners?

\chapter{Method}\label{method}

This is a causal comparative study, in that explanations for differences
in PECs are sought after their occurrence. This study uses ESM (Hektner
et al., 2007) data collected as part of a study of learners' interest
and engagement in outside-of-school STEM enrichment programs (Shumow \&
Schmidt, 2013). It makes use of a sequential exploratory data analysis
strategy, in which qualitative data is analyzed to enrich quantitative
findings (Creswell, Clark, Gutmann, \& Hanson, 2003). In particular,
moments in which learners are particularly engaged are identified as
part of the quantitative analysis; these moments are then coded
qualitatively to identify their common characteristics, first through an
inductive step and then through a confirmatory step involving a second
rater. While programs have been video-recorded, the video has not been
coded for the aspects of work with data, and the other measures from ESM
and pre-survey data are to be constructed for this study.

\section{Participants}\label{participants}

Participants will consist of 203 youth. Students in these programs are
from diverse racial and ethnic backgrounds. Most participants are around
13 years old (from students whose age was available: M = 12.71, SD =
1.70, min. = 10.75, max. = 16.36). Detailed demographic characteristics
of learners are presented in Table 1.

\textbf{Table 1 Demographic Characteristics of Learners}

\section{Context}\label{context}

The setting for this study will be nine out-of-school STEM programs
designed around best practices in urban areas in the Northeast United
States during the summer of 2015. These are described in Table 2 with
pseudonyms for the program names.

\textbf{Table 2 STEM Enrichment Program Names and Their Descriptions}

Two intermediary organizations contracted by the urban area school
districts to administer the summer programs. The two intermediaries were
responsible for soliciting and enrolling youth; establishing guidelines
for the design of the programs, and the goals of the programs; and
provide training and professional development for the program's staff. A
key difference between the intermediary organizations was that one
separated academic and enrichment-related activities, whereas, in
another, which was more closely involved in the day-to-day activities of
the program, the academic and enrichment components were more
integrated, which may have program-specific effects on learners'
engagement. Many of the programs aim to involve learners in work with
data. These learning environments bring together youth activity leaders,
educators, and those with technical expertise in STEM domains. Students
spent around three hours per day for four days per week for the
approximately four-week programs, which were taught by youth activity
leaders and scientists, engineers, and other community members with
technical expertise.

\section{Procedure}\label{procedure}

6045 9710 0447 9826

Students completed a pre-survey before the program. Students also
completed pre- and post-course surveys of their experience in STEM,
intention to pursue a STEM major or career, and questions for other
motivation and engagement-related measures. At the beginning of the
programs, students were introduced to the study and the phones used for
data collection related to the ESM. ESM data were collected two days
each week, for three weeks (weeks 2-4 of the program). In all of the
programs, about equal video-recording time was dedicated to classroom
and field experiences. This detail is important because programs
associated with one of the intermediaries rotated between classroom and
field experience days, while the other used the first half of each day
for one (i.e., classroom activities) or the other (i.e., field
experience days).

Each day, students were signaled four times. These signals were at the
same time for all of the students within their program, but at different
times between programs and between days within programs (with the
constraint that no two signals could occur less than ten minutes apart).
All of the programs were video-recorded by research team members and on
three occasions research team members who recorded detailed field notes
on the nature of program activities. So that measures corresponding to
the video and ESM data can be matched, videos include a signal from the
video-recorder identifying the ESM signal to which students responded at
that point in the video.

In a reflection of the dynamic conceptualization of engagement, this
study uses data collected from ESM. As such, learners are prompted at
regular intervals to respond to short questions about their perceptions
of their engagement and its influencers. Though time-consuming to carry
out, ESM can be a powerful measure that leverages the benefits of both
observational and self-report measures, allowing for some ecological
validity and the use of closed-form questionnaires amenable to
quantitative analysis (Csikszentmihalyi \& Larson, 1987). Despite the
logistic challenge of carrying out ESM in large studies, some scholars
have referred to it as the ``gold standard'' for understanding
individual's subjective experience (Schwarz, Kahneman, \& Xu, 2009).
This approach has the benefit of measuring learners' engagement at a
fine grain-size: Changes in the activity on learners' engagement, even
within the same session of the program, and changes in how influencers
of engagement impact engagement and how the activity may relate to
engagement, can be measured.

\section{Data Sources and Measures}\label{data-sources-and-measures}

Data sources will consist of self-reported ESM measures of engagement
and learners' perceptions of themselves and the activity, pre-survey
measures of students' interest, students' demographic information, and
video-recordings of programs.

ESM measures of learners' engagement and its conditions. Measures for
engagement and its conditions will be constructed from three ESM
responses for engagement and two ESM responses for the conditions of
engagement. The three variables for engagement are for learning (for the
cognitive engagement construct), working hard (for behavioral
engagement), and enjoying (for affective engagement). The variables for
the conditions are for perceived challenge and perceived competence. All
five items will be used to construct PECs. Each of the ESM items
consisted of the item text and the following four item response options,
of which students were directed to select one: Not at all (associated
with the number 1 on the survey), A little (2), Somewhat (3), and Very
Much (4), as presented in Table 3.

\textbf{Table 3 ESM measures for profiles of engagement and its
conditions (PECs)}

Survey measures of pre-interest. Measures of students' pre-interest are
used as student-level influencers of PECs. In particular, three items
adapted from Vandell, Hall, O'Cadiz, and Karsh (2012) were used, with
directions for students to rate their agreement with the items' text
using the same scale as the ESM items: Not at all (associated with the
number 1 on the survey), A little (2), Somewhat (3), and Very Much (4).
The items are presented in Table 4.

\textbf{Table 4 Survey Measure Used in This Study}

Codes for the activity from the video-recordings. Different aspects of
work with data will be identified from video-recordings with the use of
a coding frame with seven codes: five for each of the aspects of work
with data and the remaining two codes are for other instructional
activities, such as listening to a youth activity leader or completing a
worksheet, in order to compare work with data to other activities which
are potentially engaging but not oriented toward work with data, and one
for other activities, such as traveling between program sites or the
time in between activities. These codes are summarized in Table 5.

\textbf{Table 5 Coding Frame for Work With Data}

To determine the potential viability of this coding frame, observational
notes from trained observers were analyzed. There were at least three
observations for each of the nine programs. While these observation
notes were collected only on a small number of days, video recordings of
the programs (analyzed in the present study) were much more
comprehensive. 31 observation notes were collected in total. A coding
framework for work with data with three levels was used: 0 (no evidence
of work with data), 1 (some evidence of work with data), and 3 (evidence
of work with data). This analysis demonstrated that 36.6 \% of notes
revealed no evidence of work with data, 40 \% of notes revealed some /
potential evidence of work with data, and 23.3\% revealed evidence of
work with data.

In addition to the codes for aspects of work with data, all of the video
are also coded as occurring in the classroom or in a field setting.
These codes were created by research team members on the basis of
documentation from the intermediary program providers, who alternated
between classroom and field experiences on the basis of a set schedule.
Furthermore, the videos are also coded regarding the instructional
leader support for STEM-related practices created through the use of the
Program Quality Assessment (Akiva, 2005). Accordingly, codes for
instructional leader support for STEM practice to correspond to the
codes for work with data will be created. These codes will equal to 1
only when both the aspect of work with data (in Table 5) is present as
is the PQA code(s) associated with that aspect of work with data;
accordingly, these codes will represent students' engagement in aspects
of work with data that are also observed to be supported by youth
instructional leaders. These codes are presented in Table 6.

\textbf{Table 6 Coding Frame for Instructional Support for Work With
Data}

Demographic variables. In addition to the measures described in this
section, demographic information for youths' gender and their racial and
ethnic group will be used to construct demographic variables for gender
and membership in an under-represented (in STEM) group; membership in an
under-represented group will be identified on the basis of students'
racial and ethnic group being Hispanic, African American, Asian or
Pacific Islanders, or native American.

\section{Data Analysis}\label{data-analysis}

Before analyzing data to answer the research questions, preliminary
analyses will be carried out. The steps for both preliminary and the
primary analyses are described in this section.

Preliminary analyses. Codes for the aspects of work with data will be
created from coding videos of the activity occurring immediately before
learners were signaled to respond to a survey as part of the ESM. Before
one rater independently codes the video associated with all of the
signals, inter-rater reliability between the primary and a secondary
rater will be established. The coding frame in Table 5 will be used to
code a random sample of the videos associated with 30 of the ESM
responses. The coding frame will be used to code for the presence of one
and only one of the codes for the aspects of work with data. The
agreement between the original and second rater will be calculated using
Fleiss' kappa, with a value above .70 indicating satisfactory agreement.
If the disagreement is not satisfactory, then cases in which the raters
disagreed will be discussed and resolved, and a different sample of
videos associated with ESM responses will be coded again. Following the
satisfactory agreement, all of the videos associated with ESM signals
will be coded independently: In order to provide to the coder the
context to the video segments to be coded, all of the video segments
will be viewed (but only those associated with ESM signals will be
coded).

First-order Pearson correlations, frequency, range, mean, skew,
kurtosis, and standard deviations will be examined for all variables
including ESM measures for challenge, competence, cognitive, behavioral
and affective engagement, and for the pre-survey measure for interest.
In addition, the frequency of the codes for aspects of work with data,
and the number of responses by student, program, and moment will be
examined.

Primary analyses for RQ \#1. To answer this question, PECs will be
constructed using on the basis of five variables: cognitive, behavioral,
and affective engagement and learners' perceptions of challenge and
competence. Answers to this question will help to understand how the
aspects of engagement relate to both one another and to key conditions
that influence engagement.

To create PECs, a mixture modeling approach will be carried out. Mixture
modeling is an approach for identifying distinct distributions, or
mixtures of distributions, of measured variables. A type of mixture
modeling within a latent variable modeling framework, Latent Profile
Analysis (LPA; Harring \& Hodis, 2016; Muthen, 2004) is used in this
study, in particular, to identify the number and nature of PECs. LPA
allows for capturing the multidimensional nature of engagement.
Particularly, LPA can be used to identify common patterns in learners'
ESM responses as part of a person-oriented analysis to construct PECs.
These profiles make it possible to analyze the multivariate data
collected on engagement in a way that balances the parsimony of a single
model for all learners with a recognition of individual differences in
how learners' experience each of the dimensions of engagement together
at the same time. A key benefit of the use of LPA, in addition to
likelihood estimation-based fit indices, is probabilities of an
observation being a member of a cluster, unlike in hierarchical and
k-means cluster analysis, for which an observation is hard classified
exclusively into one cluster.

Profiles will be constructed with the five self-reported ESM measures
for cognitive, behavioral, and affective engagement and perceptions of
challenge and competence. Once this step is carried out, the probability
of a response being associated with a profile of engagement and its
conditions will be used as the dependent variable for subsequent
analyses. An interface to the MCLUST software will be developed and used
to carry out the LPA. The number of profiles will be determined on the
basis of the log-likelihood and bootstrapped likelihood ratio test,
entropy, Akaike Information Criteria, and Bayesian Information Criteria
statistics, as well as concerns of parsimony and interpretability.
Scholars have pointed out the importance of cross-validation for mixture
modeling (Steinley \& Brusco, 2011); accordingly, double-split half
cross-validation (Breckenridge, 2000) will also be carried out. Because
of sampling error possible through the resampling needed for this
approach, the cross-validation will be repeated at least 30 times for
each candidate profile solution. This analysis can help us to understand
how patterns in higher or lower levels of the variables used to
construct the profiles group together in PECs, providing insight into
both how engagement is commonly experienced as a meta-construct as well
as how key conditions influence engagement.

Primary analyses for RQ \#2. To answer this question, on how well the
aspects of work with data predict the PECs, first, indicators for
activities coded for any of the five aspects of work with data and
either of the other two activities will be used to predict each PEC.
This will help us to understand how work with data, in general, is
different from other activities in terms of predicting each PEC. Next,
how each of the five aspects of work with data, as well as the other
activities, predict each PEC will be explored. This will help us
understand how learners engage in specific aspects of work with data.

Due to similar mixed-effects models used to analyze data to answer RQ
\#2 and \#3, the data analysis strategy for these steps is described
together here. First, the general approach used for specifying the mixed
effects is first described, followed by details about how the models
will be used to provide answers to the specific research questions.

All of the models will use random effects for learner, momentary, and
program effects. Learner and moment can be considered to be crossed with
both nested within the program. Because the outcome from LPA is not a
hard classification (i.e., an observation is in a profile---or not) but
a probability, the outcome is treated as a continuous variable. There
will be as many models as profiles identified in the preliminary
analysis; so, the profile will be different between models. A bottom-up
model-building process (West, Welch, \& Galecki, 2014), in which a more
complex model is constructed on the basis of and continually compared to
a more simple model, is used.

First, null models with only the random parts (i.e., random learner,
momentary, and program effects) will be specified. Then, the predictors
will be added to the model with the main effects of the variables added
to the null mixed effects model. The main effects are for the aspects of
work with data and instructional support for the aspects of work with
data as well as individual interest in STEM (as a control variable).
Note that the interaction between individual interest in STEM and the
aspects of work with data is added in a separate step, as described in
the next section. The model with the random effects for the learner,
moment, and program and with the direct effects of all the predictor
variables is presented below.

Here, the probability of a response being associated with a profile
(obtained through the LPA carried out during the preliminary analyses)
is predicted by the direct effects of indicators for the aspects of work
with data ({[}replace{]}01 -- {[}replace{]}05 below) measured at the
momentary level, their individual interest in STEM ({[}replace{]}06),
measured at the student level, and the random learner, moment, and
program effects ({[}replace{]}learner, {[}replace{]}moment, and
{[}replace{]}program). The general specification for the models for
learner i during moment j in program k is written as:

Findings associated with this research question will help us understand
how learners engage during different aspects of work with data and how
engagement during the aspects of data differ from engagement during
non-instructional activities. Another benefit of these models is the
variance components, which can be interpreted in terms of the intraclass
correlations. Because momentary and learner random effects are crossed
and both nested with the program random effects, estimates for each of
these random effects can provide information on the sources of
unexplained variability in the PECs, thus helping us to understand the
amount of variation that variables at each of the levels of the random
effects (learner, moment, and program) can be explained.

Primary analyses for RQ \#3. To answer this question, on how well the
aspects of work with data with instructional support predict the PECs,
first, indicators for activities coded for any of the five aspects of
work with data will be interacted with a dummy code indicating
instructional support in general, created on the basis of any of the
variables for instructional support for work with data being equal to 1.
This dummy coded variable will then be interacted with any of the
aspects of work with data with relations to the PECs. Second, each of
aspects of work with data with relations to the PECs will be interacted
with a dummy code for the specific aspect of instructional support (in
Table 6). This will help us to understand how work with data, in general
and in terms of specific forms of instructional support, differs from
other activities and how support from the instructor can contribute to
more engaging work with data.

Primary analyses for RQ \#4. To answer this question, on how the
relationships between work with data and the PECs depends on students'
pre-program interest in STEM, first, differences in the relationships
between work with data in general and the PECs on the basis of students'
individual interest in STEM will be explored, using an interaction
between practices and individual interest in STEM. These analyses will
be carried out separately for relations between work with data (on its
own, corresponding to the analyses carried out for RQ \#3) and work with
data with instructional support (for RQ \#4). Next, for any specific
aspect of work with data that significantly predicts each PEC, the same
will be carried out, so that the interaction between individual interest
in STEM and the specific aspect of work with data will be used to
predict each PEC. These interactions between individual interest in STEM
and the dummy codes for aspects of work with data will be added to the
model specification for RQ \#2. Answers to this question will help us
learn how the relationships between the PECs and the aspects of work
with data vary on the basis of a trait-like characteristic of the
learner may have important impacts. Given the exploratory nature of
discovering which PECs emerge and how other factors relate to them,
specific hypotheses are not made at this time.

Primary analyses for RQ \#5. To answer this question, on the common
characteristics of potentially adaptive PECs, a sequential exploratory
data analysis strategy is used. While the activity in terms of the
aspects of work with data and the other activities likely predicts
differences in PECs, there may be other characteristics that predict
PECs, and those characteristics that predict potentially adaptive, or
beneficial to students' learning, PECs may be useful to identify both
for interpreting findings from the present study and for future
research. To answer this question, heterogeneity in terms of how the
aspects of work with data relate to the PECs will first be identified.
For example, if constructing measures is found to be associated with
both potentially adaptive and potentially maladaptive PECs, then videos
associated with this aspect of work with data will be interrogated
further for this research question.

The use of mixed effects models as part of the earlier research
questions provides an especially useful strategy for selecting cases
because the random moment effects represent moments that are associated
with especially higher probabilities of responses associated with the
different PECs. PECs will be identified and then coded qualitatively as
part of an Extreme Case Approach. Selection of cases in this way also
addresses a key challenge of the Extreme Case Approach, namely, how to
present the variability among cases that may be selected because they
are so different from the others---and from one another. The videos to
select will be identified on the basis of moment-specific predictions
accounting for all of the variables used to investigate the relations
examined as part of question 2. If the moment-specific prediction for a
potentially adaptive profile is especially positive and large, this
suggests that there are characteristics of this moment that help to
explain how students engaged in the aspects of work with data in highly
engaging ways. Similarly, if the moment-specific prediction for a
potentially maladaptive profile is especially negative and large, this
suggests that there are characteristics of this moment that help to
explain how this activity was not highly engaging. This analysis can
help us to develop an account of what may distinguish these extreme
cases from the majority with respect to the factors that influence
engagement in work with data, as well as what may be particular to each
specific case (Jahnukainen, 2010). Note that as part of an sequential
exploratory mixed methods design, the focus of this qualitative analysis
may shift based on what the results of the quantitative analyses
suggest.

In the first code-generating inductive step (Hatch, 2002), videos of the
moments will be open-coded, in which notes and possible themes are
recorded. Examples of potential codes include the factors influencing
engagement in work with data presented in Figure 1: phenomena-based
investigations, reference to or the presence of repeated cycles of
engaging in work with data over time, and collaboration among learners.
After open coding, notes and possible themes and the data will be read,
and possible patterns in them will be recorded. These patterns will be
collapsed into an initial coding frame, consisting of the codes, their
description, and an example.

This coding frame is used in the second confirmatory step, which will
involve a second rater, similar to the coding for the work with data
carried out as part of the preliminary analysis. In the second step, the
coding frame will be used to code for the presence of the codes in 20 of
the video segments, randomly selected from among those identified as
associated with random effects above the 80th percentile for the final
models. Like in the preliminary analysis, the agreement between the
original and second rater will be calculated using Fleiss' kappa, with a
value above 0.70 indicating satisfactory agreement. If the agreement is
not satisfactory, then cases in which the raters disagreed will be
discussed and resolved, and a different sample of segments (if there is
a sufficient number of samples; because only segments coded for one of
the aspects of work with data will be sampled from) will be coded again.
Knowing more about what other characteristics of the activity could
impact the relationship between aspects of work with data and learners'
engagement can help us to discover particular teaching strategies,
instructional practices, and combinations of the aspects of work with
data associated with engaging activities.

\section{Power Analysis}\label{power-analysis}

Few publications and tools address the question of statistical power for
models with crossed random effects (Westfall, Kenny, \& Judd, 2014). To
carry out power analysis for detecting the minimum detectable effect for
the relationship between one of the aspects of work with data and
profiles of engagement, Westfall et al.'s (2017) software Power Analysis
for General Anova designs to calculate power for models with arbitrarily
complex random effects structures is used. The power, or {[}replace{]},
was set to 0.80. The results of the power analysis indicated that a
minimum detectable d (effect size) is 0.43, a moderate effect (Cohen,
1992).

\section{Limitations}\label{limitations}

This study has three primary limitations. First, this study does not
consider outcomes from engaging, such as the products of neither
students' work, nor the specific cognitive capabilities they develop
through their participation. Second, the context for this study is
suited to understanding engagement in aspects of work with data but not
explicitly designed for it, and learning environments that deliberately
support work with data over a long period may demonstrate different
patterns of engagement than those examined in this study because of the
focus on and sequencing of the aspects of work with data, which may make
it more (or less) cognitively, behaviorally, or affectively engaging
than is determined in this study. Third, this program is not
representation of all outside-of-school programs, as many of the
programs were based on characteristics of model STEM enrichment
programs; as a result, engagement may be different in other STEM
enrichment programs depending on characteristics of the programs and
their activities, and findings from this study should be interpreted in
terms of programs that share similar features in terms of their design.

\chapter{Results}\label{results}

In this section, results in terms of the research questions are
presented.

First, for RQ \#1:

\section{Research Question \#1}\label{research-question-1}

This question addresses what profiles emerged from the data. This
section is organized around:

\begin{itemize}
\tightlist
\item
  Overall solutions for all models (whether models converged and the
  log-likelihood was replicated)
\item
  Fit statistics for models that converged and demonstrated that the
  log-likelihood was replicated
\item
  Comparison of candidate solutions
\end{itemize}

\subsection{Overall solutions for all
models}\label{overall-solutions-for-all-models}

sadfsa

\begin{landscape}\begin{table}

\caption{\label{tab:printing-solutions-overall-stats}Overall statistics for all models}
\centering
\resizebox{\linewidth}{!}{\begin{tabular}[t]{rllllll}
\toprule
n\_profiles & model\_1 & model\_2 & model\_3 & model\_4 & model\_5 & model\_6\\
\midrule
2 & 39916.157 & 38423.266 & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue\\
3 & 39082.592 & 38049.877 & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue\\
4 & 38616.439 & 37623.057 & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue\\
5 & 37907.604 & 37301.328 & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue\\
6 & 37617.262 & Warning: LL not replicated & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue\\
7 & 37182.108 & Warning: LL not replicated & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue\\
8 & Warning: LL not replicated & Warning: LL not replicated & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue\\
9 & 36836.247 & Warning: LL not replicated & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue\\
10 & Warning: LL not replicated & Warning: LL not replicated & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue & Error: Convergence issue\\
\bottomrule
\end{tabular}}
\end{table}
\end{landscape}

\subsection{In-depth statistics for particular
models}\label{in-depth-statistics-for-particular-models}

First, I examined a wide range of models and solutions. I did this in
order to select particular, candidate models to scrutinize in greater
detail. In order to carry out this analysis, I followed guidelines
recommended by the developers of MPlus (Asparouhov \& Muthen, 2012;
Muthen \& Muthen, 2017) as well as those making recommendations about
its use (Geiser, 2012). In particular, I set the number of starts to 600
for initial stage starts, and to 120 for the number of starts to be
optimized. This means that for each model estimated, 600 random starting
values for the parameters were used to initialize the EM algorithm. Of
these 600, 120 that demonstrated the lowest log-likelihood were allowed
to continue until they reached convergence or the limit for the number
of iterations. In order for a model to me considered trustworthy, of
these 120 runs, the lowest log-likelihood must be replicated at least
one time.

The results are presented in Figure 5.1. If this is the case, then the
log-likelihood would appear in the table below; if not, ``LL not
replicated'' is reported as the value. If none of the 120 runs converge,
then ``Did not converge'' is reported as the value. As can be seen from
this table, only models associated with model specifications 1 and 2
(and among these two solutions, only those associated with particular
number of profiles) converged.

\begin{landscape}\begin{table}

\caption{\label{tab:printing-solutions-spec-stats}Solutions for models that converged with replicated LL}
\centering
\resizebox{\linewidth}{!}{\begin{tabular}[t]{rrrrrrrrrrrrrr}
\toprule
n\_profile & model & LL & AIC & BIC & SABIC & CAIC & Entropy & VLMR\_val & VLMR\_p & LMR\_val & LMR\_p & BLRT\_val & BLRT\_p\\
\midrule
2 & 1 & -19894.14 & -19894.14 & 39916.16 & 39865.32 & 39820.47 & 0.807 & 3468.199 & 0.0000 & 3397.353 & 0.0000 & 3468.199 & 0\\
3 & 1 & -19453.38 & -19453.38 & 39082.59 & 39012.69 & 38951.11 & 0.794 & 881.519 & 0.0126 & 863.512 & 0.0136 & 881.519 & 0\\
4 & 1 & -19196.33 & -19196.33 & 38616.44 & 38527.47 & 38449.21 & 0.811 & 514.107 & 0.0000 & 503.605 & 0.0000 & 514.107 & 0\\
5 & 1 & -18817.93 & -18817.93 & 37907.60 & 37799.57 & 37704.68 & 0.913 & 756.788 & 0.0000 & 741.329 & 0.0000 & 756.788 & 0\\
6 & 1 & -18648.78 & -18648.78 & 37617.26 & 37490.17 & 37378.70 & 0.888 & 338.296 & 0.0000 & 331.386 & 0.0000 & 338.296 & 0\\
7 & 1 & -18407.23 & -18407.23 & 37182.11 & 37035.95 & 36907.95 & 0.886 & 523.141 & 0.0112 & 512.455 & 0.0121 & 523.141 & 0\\
9 & 1 & -18186.35 & -18186.35 & 36836.25 & 36651.96 & 36491.06 & 0.899 & 171.674 & 0.1322 & 168.167 & 0.1359 & 171.674 & 0\\
2 & 2 & -19107.73 & -19107.73 & 38423.27 & 38340.65 & 38267.95 & 0.924 & 850.304 & 0.0000 & 832.934 & 0.0000 & 850.304 & 0\\
3 & 2 & -18897.06 & -18897.06 & 38049.88 & 37948.20 & 37858.85 & 0.880 & 421.343 & 0.0000 & 412.736 & 0.0000 & 421.343 & 0\\
4 & 2 & -18659.68 & -18659.68 & 37623.06 & 37502.32 & 37396.37 & 0.922 & 474.773 & 0.0000 & 465.075 & 0.0000 & 474.773 & 0\\
5 & 2 & -18474.83 & -18474.83 & 37301.33 & 37161.52 & 37039.03 & 0.901 & 304.938 & 0.0000 & 298.709 & 0.0000 & 304.938 & 0\\
\bottomrule
\end{tabular}}
\end{table}
\end{landscape}

\subsection{This section presents fit statistics for select
models}\label{this-section-presents-fit-statistics-for-select-models}

\begin{center}\includegraphics[width=1\linewidth]{rosenberg-dissertation_files/figure-latex/model1-1} \end{center}

\subsection{Comparison of candidate
solutions}\label{comparison-of-candidate-solutions}

In this section, specific models are examined so that candidate
solutions can be compared.

\subsection{Model 1 candidate
solutions}\label{model-1-candidate-solutions}

Here are solutions for model 1.

\begin{center}\includegraphics[width=0.8\linewidth]{rosenberg-dissertation_files/figure-latex/spec-solutions-m1_3-1} \end{center}

\begin{tabular}{l|l|r|l}
\hline
  & LL & seed & m\_iterations\\
\hline
1 & -19453.381 & 231281 & 542\\
\hline
2 & -19453.381 & 879211 & 453\\
\hline
3 & -19453.381 & 897782 & 545\\
\hline
4 & -19453.381 & 155622 & 507\\
\hline
5 & -19453.381 & 192071 & 142\\
\hline
6 & -19453.381 & 507154 & 387\\
\hline
7 & -19453.381 & 674171 & 195\\
\hline
8 & -19453.381 & 316165 & 299\\
\hline
9 & -19453.381 & 374219 & 353\\
\hline
10 & -19453.381 & 783102 & 433\\
\hline
11 & -19453.381 & 650371 & 14\\
\hline
12 & -19453.381 & 68850 & 462\\
\hline
13 & -19453.381 & 539389 & 544\\
\hline
14 & -19453.381 & 580405 & 286\\
\hline
15 & -19453.381 & 685268 & 596\\
\hline
16 & -19453.381 & 481835 & 57\\
\hline
17 & -19453.381 & 46437 & 153\\
\hline
18 & -19453.381 & 505244 & 582\\
\hline
19 & -19453.381 & 51375 & 148\\
\hline
20 & -19453.381 & 715255 & 523\\
\hline
21 & -19453.381 & 848890 & 95\\
\hline
22 & -19453.381 & 36714 & 201\\
\hline
23 & -19453.381 & 638611 & 524\\
\hline
24 & -19453.381 & 804104 & 566\\
\hline
25 & -19453.381 & 790452 & 303\\
\hline
26 & -19453.381 & 972873 & 157\\
\hline
27 & -19453.381 & 378393 & 509\\
\hline
28 & -19453.381 & 127215 & 9\\
\hline
29 & -19453.381 & 414284 & 158\\
\hline
30 & -19453.381 & 415502 & 194\\
\hline
31 & -19453.381 & 648555 & 113\\
\hline
32 & -19453.381 & 617243 & 237\\
\hline
33 & -19453.381 & 551639 & 55\\
\hline
34 & -19453.381 & 220454 & 288\\
\hline
35 & -19453.381 & 567165 & 319\\
\hline
36 & -19453.381 & 561664 & 392\\
\hline
37 & -19453.381 & 437181 & 135\\
\hline
38 & -19453.381 & 462228 & 298\\
\hline
39 & -19453.381 & 900268 & 327\\
\hline
40 & -19453.381 & 741484 & 441\\
\hline
41 & -19453.381 & 178475 & 231\\
\hline
42 & -19453.381 & 534483 & 290\\
\hline
43 & -19453.381 & 566687 & 597\\
\hline
44 & -19453.381 & 215353 & 164\\
\hline
45 & -19453.381 & 608496 & 4\\
\hline
46 & -19453.381 & 923437 & 398\\
\hline
47 & -19453.381 & 65651 & 214\\
\hline
48 & -19453.381 & 267983 & 228\\
\hline
49 & -19453.381 & 335485 & 496\\
\hline
50 & -19453.381 & 438144 & 271\\
\hline
51 & -19453.381 & 476498 & 179\\
\hline
52 & -19453.381 & 655497 & 376\\
\hline
53 & -19453.381 & 195353 & 225\\
\hline
54 & -19453.381 & 440841 & 118\\
\hline
55 & -19453.381 & 43523 & 297\\
\hline
56 & -19453.381 & 391179 & 78\\
\hline
57 & -19453.381 & 359578 & 458\\
\hline
58 & -19453.381 & 910224 & 580\\
\hline
59 & -19453.381 & 972430 & 491\\
\hline
60 & -19453.381 & 443917 & 60\\
\hline
61 & -19453.381 & 404426 & 344\\
\hline
62 & -19453.381 & 23012 & 352\\
\hline
63 & -19453.381 & 247224 & 94\\
\hline
64 & -19453.381 & 425929 & 508\\
\hline
65 & -19453.381 & 371737 & 532\\
\hline
66 & -19453.381 & 992389 & 77\\
\hline
67 & -19453.381 & 688839 & 273\\
\hline
68 & -19453.381 & 260953 & 589\\
\hline
69 & -19453.381 & 902278 & 21\\
\hline
70 & -19453.381 & 371246 & 101\\
\hline
71 & -19453.381 & 802682 & 419\\
\hline
72 & -19453.381 & 471398 & 74\\
\hline
73 & -19453.381 & 297518 & 166\\
\hline
74 & -19453.381 & 411615 & 171\\
\hline
76 & -19453.381 & 311214 & 64\\
\hline
77 & -19453.381 & 414828 & 322\\
\hline
78 & -19453.381 & 782200 & 84\\
\hline
79 & -19453.381 & 206099 & 363\\
\hline
80 & -19453.381 & 156536 & 245\\
\hline
81 & -19453.381 & 802256 & 477\\
\hline
82 & -19453.381 & 830392 & 35\\
\hline
83 & -19453.381 & 509733 & 130\\
\hline
84 & -19453.381 & 831410 & 567\\
\hline
85 & -19453.381 & 467339 & 66\\
\hline
86 & -19453.381 & 130011 & 587\\
\hline
87 & -19453.381 & 691041 & 590\\
\hline
88 & -19453.381 & 484406 & 421\\
\hline
89 & -19453.381 & 197223 & 332\\
\hline
90 & -19453.381 & 608460 & 244\\
\hline
91 & -19453.381 & 782821 & 272\\
\hline
92 & -19453.381 & 248742 & 556\\
\hline
93 & -19453.381 & 314034 & 513\\
\hline
94 & -19453.381 & 21132 & 351\\
\hline
95 & -19453.381 & 173440 & 328\\
\hline
96 & -19453.381 & 971693 & 470\\
\hline
97 & -19453.381 & 614009 & 317\\
\hline
98 & -19453.381 & 85734 & 411\\
\hline
99 & -19453.381 & 354208 & 196\\
\hline
100 & -19453.381 & 485483 & 498\\
\hline
101 & -19453.381 & 49221 & 254\\
\hline
102 & -19453.381 & 794236 & 127\\
\hline
103 & -19453.381 & 772131 & 407\\
\hline
104 & -19453.381 & 699554 & 427\\
\hline
105 & -19453.381 & 417035 & 149\\
\hline
106 & -19453.381 & 783110 & 72\\
\hline
107 & -19453.381 & 93468 & 3\\
\hline
108 & -19453.381 & 462953 & 7\\
\hline
109 & -19453.381 & 407108 & 366\\
\hline
110 & -19453.381 & 66276 & 217\\
\hline
111 & -19453.381 & 518828 & 432\\
\hline
112 & -19453.381 & 61587 & 400\\
\hline
113 & -19453.381 & 67009 & 564\\
\hline
114 & -19453.381 & 137305 & 379\\
\hline
115 & -19453.381 & 195763 & 358\\
\hline
116 & -19453.381 & 662718 & 460\\
\hline
117 & -19453.381 & 314757 & 345\\
\hline
118 & -19453.381 & 50887 & 389\\
\hline
119 & -19453.381 & 654136 & 167\\
\hline
120 & -19453.381 & 468036 & 131\\
\hline
\end{tabular}

\begin{center}\includegraphics[width=0.8\linewidth]{rosenberg-dissertation_files/figure-latex/spec-solutions-m1_4-1} \end{center}

\begin{tabular}{l|l|r|l}
\hline
  & LL & seed & m\_iterations\\
\hline
1 & -19196.328 & 415931.0000 & 10\\
\hline
2 & -19196.328 & 260953.0000 & 589\\
\hline
3 & -19196.328 & 576220.0000 & 115\\
\hline
4 & -19196.328 & 329127.0000 & 185\\
\hline
5 & -19196.328 & 391179.0000 & 78\\
\hline
6 & -19196.328 & 352277.0000 & 42\\
\hline
7 & -19196.328 & 443442.0000 & 380\\
\hline
8 & -19196.328 & 518828.0000 & 432\\
\hline
9 & -19196.328 & 36714.0000 & 201\\
\hline
10 & -19196.328 & 456213.0000 & 160\\
\hline
11 & -19196.328 & 399848.0000 & 220\\
\hline
12 & -19196.328 & 570908.0000 & 98\\
\hline
13 & -19196.328 & 335485.0000 & 496\\
\hline
14 & -19196.328 & 609185.0000 & 181\\
\hline
15 & -19196.328 & 150531.0000 & 154\\
\hline
16 & -19196.328 & 396795.0000 & 323\\
\hline
17 & -19196.328 & 68985.0000 & 17\\
\hline
18 & -19196.328 & 608460.0000 & 244\\
\hline
19 & -19196.328 & 113138.0000 & 585\\
\hline
20 & -19196.328 & 849670.0000 & 347\\
\hline
21 & -19196.328 & 699810.0000 & 571\\
\hline
22 & -19226.584 & 181293.0000 & 212\\
\hline
23 & -19226.584 & 512836.0000 & 289\\
\hline
24 & -19226.584 & 636396.0000 & 168\\
\hline
25 & -19226.584 & 369602.0000 & 146\\
\hline
26 & -19226.584 & 292884.0000 & 103\\
\hline
27 & -19226.584 & 392751.0000 & 480\\
\hline
28 & -19226.584 & 879211.0000 & 453\\
\hline
29 & -19226.584 & 207896.0000 & 25\\
\hline
30 & -19226.584 & 50887.0000 & 389\\
\hline
31 & -19226.584 & 97158.0000 & 205\\
\hline
32 & -19226.584 & 155622.0000 & 507\\
\hline
33 & -19226.584 & 188498.0000 & 258\\
\hline
34 & -19226.584 & 871851.0000 & 257\\
\hline
35 & -19226.584 & 349263.0000 & 263\\
\hline
36 & -19226.584 & 217744.0000 & 326\\
\hline
37 & -19226.584 & 568405.0000 & 233\\
\hline
38 & -19226.584 & 836066.0000 & 372\\
\hline
39 & -19226.584 & 137377.0000 & 397\\
\hline
40 & -19226.584 & 68850.0000 & 462\\
\hline
41 & -19226.584 & 508482.0000 & 446\\
\hline
42 & -19226.584 & 746978.0000 & 410\\
\hline
43 & -19226.584 & 602797.0000 & 336\\
\hline
44 & -19273.373 & 689529.0000 & 516\\
\hline
45 & -19273.373 & 782821.0000 & 272\\
\hline
46 & -19273.373 & 569131.0000 & 26\\
\hline
47 & -19273.373 & 349562.0000 & 359\\
\hline
48 & -19273.373 & 933578.0000 & 506\\
\hline
49 & -19273.373 & 21345.0000 & 199\\
\hline
50 & -19273.373 & 741888.0000 & 138\\
\hline
51 & -19273.373 & 314757.0000 & 345\\
\hline
52 & -19273.373 & 455617.0000 & 242\\
\hline
53 & -19273.373 & 669634.0000 & 335\\
\hline
54 & -19273.373 & 529496.0000 & 343\\
\hline
55 & -19273.373 & 860772.0000 & 174\\
\hline
56 & -19273.373 & 53621.0000 & 483\\
\hline
57 & -19273.373 & 608496.0000 & 4\\
\hline
58 & -19273.373 & 416463.0000 & 467\\
\hline
59 & -19273.373 & 848163.0000 & 47\\
\hline
60 & -19273.373 & 641794.0000 & 591\\
\hline
61 & -19273.373 & 582296.0000 & 452\\
\hline
62 & -19273.373 & 414828.0000 & 322\\
\hline
63 & -19273.373 & 947714.0000 & 573\\
\hline
64 & -19273.373 & 617243.0000 & 237\\
\hline
65 & -19273.373 & 232559.0000 & 136\\
\hline
66 & -19273.373 & 749635.0000 & 420\\
\hline
67 & -19273.373 & 533738.0000 & 11\\
\hline
68 & -19273.373 & 804104.0000 & 566\\
\hline
69 & -19273.373 & 783110.0000 & 72\\
\hline
70 & -19273.373 & 312754.0000 & 562\\
\hline
71 & -19273.373 & 985387.0000 & 381\\
\hline
72 & -19273.373 & 483369.0000 & 270\\
\hline
73 & -19273.373 & 170954.0000 & 86\\
\hline
74 & -19273.373 & 194143.0000 & 510\\
\hline
75 & -19273.373 & 960438.0000 & 116\\
\hline
76 & -19273.373 & 436460.0000 & 89\\
\hline
115 & 1 & 424.7493 & 0.14359\\
\hline
116 & 2 & 916.7557 & 0.30992\\
\hline
117 & 3 & 1203.9170 & 0.40700\\
\hline
118 & 4 & 412.5780 & 0.13948\\
\hline
\end{tabular}

\begin{center}\includegraphics[width=0.8\linewidth]{rosenberg-dissertation_files/figure-latex/spec-solutions-m1_5-1} \end{center}

\begin{tabular}{l|l|r|l}
\hline
  & LL & seed & m\_iterations\\
\hline
1 & -18817.934 & 152496.0000 & 123\\
\hline
2 & -18817.934 & 602797.0000 & 336\\
\hline
3 & -18817.934 & 432148.0000 & 30\\
\hline
4 & -18817.934 & 399848.0000 & 220\\
\hline
5 & -18837.053 & 387701.0000 & 275\\
\hline
6 & -18858.428 & 850545.0000 & 357\\
\hline
7 & -18858.428 & 298275.0000 & 418\\
\hline
8 & -18858.428 & 626891.0000 & 32\\
\hline
9 & -18944.968 & 823392.0000 & 479\\
\hline
10 & -18944.968 & 147440.0000 & 514\\
\hline
11 & -18944.968 & 84013.0000 & 598\\
\hline
12 & -18944.968 & 652266.0000 & 490\\
\hline
13 & -18944.968 & 76337.0000 & 76\\
\hline
14 & -18944.968 & 922042.0000 & 492\\
\hline
15 & -18944.968 & 519357.0000 & 559\\
\hline
16 & -18944.968 & 798839.0000 & 312\\
\hline
17 & -18944.968 & 399380.0000 & 436\\
\hline
18 & -18944.968 & 535804.0000 & 111\\
\hline
19 & -18944.968 & 595153.0000 & 230\\
\hline
20 & -18944.968 & 55115.0000 & 408\\
\hline
21 & -18944.968 & 399671.0000 & 13\\
\hline
22 & -18962.382 & 512836.0000 & 289\\
\hline
23 & -18962.382 & 714455.0000 & 476\\
\hline
24 & -18962.382 & 405079.0000 & 68\\
\hline
25 & -18962.382 & 359578.0000 & 458\\
\hline
26 & -18962.382 & 534864.0000 & 307\\
\hline
27 & -18962.382 & 545140.0000 & 278\\
\hline
28 & -18962.382 & 320494.0000 & 465\\
\hline
29 & -18962.382 & 127215.0000 & 9\\
\hline
30 & -18962.382 & 46437.0000 & 153\\
\hline
31 & -18962.382 & 377504.0000 & 294\\
\hline
32 & -18962.382 & 754100.0000 & 56\\
\hline
33 & -18962.382 & 163110.0000 & 584\\
\hline
34 & -18962.382 & 68850.0000 & 462\\
\hline
35 & -18962.382 & 857799.0000 & 315\\
\hline
36 & -18962.382 & 156536.0000 & 245\\
\hline
37 & -18962.382 & 153942.0000 & 31\\
\hline
38 & -18962.382 & 349360.0000 & 464\\
\hline
39 & -18962.382 & 648555.0000 & 113\\
\hline
40 & -18962.382 & 804104.0000 & 566\\
\hline
41 & -18962.382 & 68985.0000 & 17\\
\hline
42 & -18962.382 & 539751.0000 & 459\\
\hline
43 & -18962.382 & 902278.0000 & 21\\
\hline
44 & -18962.382 & 484687.0000 & 306\\
\hline
45 & -18962.382 & 220454.0000 & 288\\
\hline
46 & -18962.382 & 635245.0000 & 121\\
\hline
47 & -18962.382 & 301180.0000 & 236\\
\hline
48 & -18962.382 & 107446.0000 & 12\\
\hline
49 & -18962.382 & 195353.0000 & 225\\
\hline
50 & -18962.382 & 888905.0000 & 444\\
\hline
51 & -18973.040 & 584397.0000 & 428\\
\hline
52 & -18973.040 & 505244.0000 & 582\\
\hline
53 & -18973.040 & 232559.0000 & 136\\
\hline
54 & -18973.040 & 931874.0000 & 141\\
\hline
55 & -19008.215 & 802256.0000 & 477\\
\hline
56 & -19008.215 & 416463.0000 & 467\\
\hline
57 & -19008.215 & 614009.0000 & 317\\
\hline
58 & -19008.215 & 569833.0000 & 85\\
\hline
59 & -19008.215 & 292884.0000 & 103\\
\hline
60 & -19008.215 & 903633.0000 & 553\\
\hline
61 & -19008.215 & 605358.0000 & 321\\
\hline
62 & -19008.215 & 950604.0000 & 172\\
\hline
63 & -19008.215 & 629320.0000 & 222\\
\hline
64 & -19008.215 & 872743.0000 & 374\\
\hline
65 & -19008.215 & 726035.0000 & 191\\
\hline
66 & -19012.767 & 948615.0000 & 140\\
\hline
67 & -19026.931 & 579995.0000 & 183\\
\hline
68 & -19026.931 & 475420.0000 & 71\\
\hline
69 & -19026.931 & 742688.0000 & 594\\
\hline
70 & -19026.931 & 123985.0000 & 248\\
\hline
71 & -19026.931 & 206099.0000 & 363\\
\hline
72 & -19026.931 & 67009.0000 & 564\\
\hline
73 & -19026.931 & 891347.0000 & 504\\
\hline
74 & -19026.931 & 92689.0000 & 304\\
\hline
75 & -19055.988 & 294669.0000 & 501\\
\hline
76 & -19073.546 & 518828.0000 & 432\\
\hline
77 & -19073.546 & 641794.0000 & 591\\
\hline
78 & -19073.546 & 464179.0000 & 106\\
\hline
79 & -19081.251 & 126371.0000 & 526\\
\hline
80 & -19081.251 & 751153.0000 & 110\\
\hline
119 & 1 & 702.6533 & 0.23754\\
\hline
120 & 2 & 341.3386 & 0.11540\\
\hline
\end{tabular}

\begin{center}\includegraphics[width=0.8\linewidth]{rosenberg-dissertation_files/figure-latex/spec-solutions-m1_6-1} \end{center}

\begin{tabular}{l|l|r|l}
\hline
  & LL & seed & m\_iterations\\
\hline
1 & -18648.785 & 1548.0000 & 384\\
\hline
2 & -18648.785 & 282464.0000 & 283\\
\hline
3 & -18668.802 & 529496.0000 & 343\\
\hline
4 & -18695.729 & 49221.0000 & 254\\
\hline
5 & -18695.729 & 153394.0000 & 429\\
\hline
6 & -18695.729 & 741888.0000 & 138\\
\hline
7 & -18695.729 & 85114.0000 & 385\\
\hline
8 & -18695.729 & 173191.0000 & 422\\
\hline
9 & -18695.729 & 436460.0000 & 89\\
\hline
10 & -18695.729 & 153942.0000 & 31\\
\hline
11 & -18695.729 & 582296.0000 & 452\\
\hline
12 & -18699.595 & 898745.0000 & 466\\
\hline
13 & -18734.195 & 168762.0000 & 200\\
\hline
14 & -18734.195 & 107446.0000 & 12\\
\hline
15 & -18740.888 & 732596.0000 & 320\\
\hline
16 & -18740.888 & 292884.0000 & 103\\
\hline
17 & -18761.241 & 679832.0000 & 302\\
\hline
18 & -18761.241 & 491970.0000 & 563\\
\hline
19 & -18761.241 & 772131.0000 & 407\\
\hline
20 & -18761.241 & 809240.0000 & 543\\
\hline
21 & -18823.866 & 535804.0000 & 111\\
\hline
22 & -18829.855 & 475420.0000 & 71\\
\hline
23 & -18829.855 & 321390.0000 & 133\\
\hline
24 & -18830.313 & 22874.0000 & 588\\
\hline
25 & -18830.313 & 76337.0000 & 76\\
\hline
26 & -18830.313 & 294669.0000 & 501\\
\hline
27 & -18830.765 & 945065.0000 & 255\\
\hline
28 & -18830.765 & 371246.0000 & 101\\
\hline
29 & -18830.765 & 260601.0000 & 36\\
\hline
30 & -18865.480 & 484687.0000 & 306\\
\hline
31 & -18866.526 & 995875.0000 & 547\\
\hline
32 & -18871.995 & 392766.0000 & 331\\
\hline
33 & -18885.166 & 848163.0000 & 47\\
\hline
34 & -18909.485 & 794236.0000 & 127\\
\hline
35 & -18909.485 & 161421.0000 & 519\\
\hline
36 & -18952.268 & 752769.0000 & 253\\
\hline
37 & -18962.382 & 415931.0000 & 10\\
\hline
38 & -18962.382 & 937588.0000 & 293\\
\hline
39 & -18962.382 & 349360.0000 & 464\\
\hline
40 & -18962.382 & 57226.0000 & 208\\
\hline
41 & -18962.382 & 216565.0000 & 474\\
\hline
42 & -18962.382 & 801717.0000 & 364\\
\hline
43 & -18962.382 & 609089.0000 & 241\\
\hline
44 & -18962.382 & 347515.0000 & 24\\
\hline
45 & -18962.382 & 370957.0000 & 554\\
\hline
46 & -18973.040 & 606576.0000 & 151\\
\hline
85 & 1 & 337.1202 & 0.11397\\
\hline
86 & 2 & 660.9009 & 0.22343\\
\hline
87 & 3 & 437.6870 & 0.14797\\
\hline
88 & 4 & 326.4506 & 0.11036\\
\hline
89 & 5 & 706.4016 & 0.23881\\
\hline
90 & 6 & 489.4398 & 0.16546\\
\hline
99 & 1 & 337.1202 & 0.11397\\
\hline
100 & 2 & 660.9009 & 0.22343\\
\hline
101 & 3 & 437.6870 & 0.14797\\
\hline
102 & 4 & 326.4506 & 0.11036\\
\hline
103 & 5 & 706.4016 & 0.23881\\
\hline
104 & 6 & 489.4398 & 0.16546\\
\hline
115 & 1 & 370.0000 & 0.12508\\
\hline
116 & 2 & 667.0000 & 0.22549\\
\hline
117 & 3 & 450.0000 & 0.15213\\
\hline
118 & 4 & 345.0000 & 0.11663\\
\hline
119 & 5 & 638.0000 & 0.21569\\
\hline
120 & 6 & 488.0000 & 0.16498\\
\hline
\end{tabular}

\begin{center}\includegraphics[width=0.8\linewidth]{rosenberg-dissertation_files/figure-latex/spec-solutions-m1_7-1} \end{center}

\begin{tabular}{l|l|r|l}
\hline
  & LL & seed & m\_iterations\\
\hline
1 & -18407.232 & 475420.0000 & 71\\
\hline
2 & -18407.232 & 871438.0000 & 561\\
\hline
3 & -18469.834 & 597614.0000 & 284\\
\hline
4 & -18469.834 & 830570.0000 & 369\\
\hline
5 & -18469.834 & 283492.0000 & 435\\
\hline
6 & -18469.834 & 260953.0000 & 589\\
\hline
7 & -18518.118 & 153394.0000 & 429\\
\hline
8 & -18634.678 & 950604.0000 & 172\\
\hline
9 & -18660.958 & 922596.0000 & 456\\
\hline
10 & -18662.856 & 160326.0000 & 546\\
\hline
11 & -18668.802 & 529496.0000 & 343\\
\hline
12 & -18671.284 & 281558.0000 & 184\\
\hline
13 & -18672.116 & 987090.0000 & 70\\
\hline
14 & -18685.112 & 358074.0000 & 560\\
\hline
15 & -18704.013 & 414828.0000 & 322\\
\hline
16 & -18719.886 & 468036.0000 & 131\\
\hline
17 & -18719.886 & 714455.0000 & 476\\
\hline
18 & -18727.865 & 92564.0000 & 583\\
\hline
19 & -18734.195 & 985387.0000 & 381\\
\hline
20 & -18743.891 & 373505.0000 & 88\\
\hline
21 & -18761.241 & 320494.0000 & 465\\
\hline
22 & -18830.765 & 118421.0000 & 139\\
\hline
61 & 1 & 186.5303 & 0.06306\\
\hline
62 & 2 & 305.0320 & 0.10312\\
\hline
63 & 3 & 641.8389 & 0.21698\\
\hline
64 & 4 & 588.1502 & 0.19883\\
\hline
65 & 5 & 213.6503 & 0.07223\\
\hline
66 & 6 & 575.4683 & 0.19455\\
\hline
67 & 7 & 447.3301 & 0.15123\\
\hline
76 & 1 & 186.5303 & 0.06306\\
\hline
77 & 2 & 305.0320 & 0.10312\\
\hline
78 & 3 & 641.8389 & 0.21698\\
\hline
79 & 4 & 588.1502 & 0.19883\\
\hline
80 & 5 & 213.6503 & 0.07223\\
\hline
81 & 6 & 575.4683 & 0.19455\\
\hline
82 & 7 & 447.3301 & 0.15123\\
\hline
93 & 1 & 181.0000 & 0.06119\\
\hline
94 & 2 & 317.0000 & 0.10717\\
\hline
95 & 3 & 651.0000 & 0.22008\\
\hline
96 & 4 & 569.0000 & 0.19236\\
\hline
97 & 5 & 222.0000 & 0.07505\\
\hline
98 & 6 & 568.0000 & 0.19202\\
\hline
99 & 7 & 450.0000 & 0.15213\\
\hline
104 & Entropy & 0.8860 & NA\\
\hline
110 & 1 & 2.0000 & 3\\
\hline
112 & 1 & 0.9540 & 0.016\\
\hline
113 & 2 & 0.0160 & 0.889\\
\hline
114 & 3 & 0.0140 & 0.028\\
\hline
115 & 4 & 0.0000 & 0.000\\
\hline
116 & 5 & 0.0000 & 0.000\\
\hline
117 & 6 & 0.0000 & 0.004\\
\hline
118 & 7 & 0.0000 & 0.000\\
\hline
\end{tabular}

We can see that even for the solutions associated with other
log-likelihoods, the results for model 7 are the same.

\begin{center}\includegraphics[width=0.8\linewidth]{rosenberg-dissertation_files/figure-latex/spec-solutions-m1_7-other-LL-1} \end{center}

\begin{verbatim}
## Error in start:stop: argument of length 0
\end{verbatim}

\subsection{Model 2 candidate
solutions}\label{model-2-candidate-solutions}

Here are solutions for model 2.

\begin{center}\includegraphics[width=0.8\linewidth]{rosenberg-dissertation_files/figure-latex/spec-solutions-for-model2-1} \end{center}

\begin{tabular}{l|r|l}
\hline
LL & seed & m\_iterations\\
\hline
-18897.062 & 154575 & 539\\
\hline
-18897.062 & 606576 & 151\\
\hline
-18897.062 & 746978 & 410\\
\hline
-18897.062 & 107446 & 12\\
\hline
-18897.062 & 30098 & 209\\
\hline
-18897.062 & 871851 & 257\\
\hline
-18897.062 & 491970 & 563\\
\hline
-18897.062 & 76451 & 211\\
\hline
-18897.062 & 152496 & 123\\
\hline
-18897.062 & 458181 & 189\\
\hline
-18938.334 & 622860 & 259\\
\hline
-18946.513 & 736574 & 414\\
\hline
-18946.513 & 996231 & 310\\
\hline
-18946.513 & 165853 & 105\\
\hline
-18946.513 & 85114 & 385\\
\hline
-18946.513 & 415502 & 194\\
\hline
-18946.513 & 526324 & 178\\
\hline
-18946.513 & 55115 & 408\\
\hline
-18946.513 & 170118 & 238\\
\hline
-18946.513 & 68985 & 17\\
\hline
-18946.513 & 210870 & 383\\
\hline
-18946.513 & 370957 & 554\\
\hline
-18954.846 & 857799 & 315\\
\hline
-18954.846 & 440841 & 118\\
\hline
-18954.846 & 22874 & 588\\
\hline
-18954.846 & 212934 & 568\\
\hline
-18954.846 & 507154 & 387\\
\hline
-18954.846 & 930323 & 267\\
\hline
-18954.846 & 395754 & 388\\
\hline
-18963.453 & 124999 & 96\\
\hline
-18963.453 & 375590 & 438\\
\hline
-18963.453 & 745972 & 521\\
\hline
-18963.453 & 486646 & 586\\
\hline
-18963.453 & 783102 & 433\\
\hline
-18963.453 & 425929 & 508\\
\hline
-18963.453 & 285380 & 1\\
\hline
-18978.620 & 195763 & 358\\
\hline
-18978.620 & 193847 & 354\\
\hline
-18978.620 & 939021 & 8\\
\hline
-18981.651 & 112586 & 494\\
\hline
-18981.651 & 635245 & 121\\
\hline
-19001.597 & 76337 & 76\\
\hline
-19001.597 & 579995 & 183\\
\hline
-19001.597 & 301180 & 236\\
\hline
-19018.412 & 614009 & 317\\
\hline
-19018.412 & 320494 & 465\\
\hline
-19018.412 & 195873 & 6\\
\hline
-19018.412 & 823392 & 479\\
\hline
-19018.412 & 467339 & 66\\
\hline
-19018.412 & 948615 & 140\\
\hline
-19018.412 & 741484 & 441\\
\hline
-19018.992 & 217744 & 326\\
\hline
-19018.992 & 314034 & 513\\
\hline
-19018.992 & 509733 & 130\\
\hline
-19018.992 & 520177 & 262\\
\hline
-19018.992 & 783110 & 72\\
\hline
-19018.992 & 638611 & 524\\
\hline
-19018.992 & 23012 & 352\\
\hline
-19018.992 & 227563 & 63\\
\hline
-19018.992 & 358074 & 560\\
\hline
-19027.625 & 514326 & 325\\
\hline
-19027.625 & 194143 & 510\\
\hline
-19027.625 & 802682 & 419\\
\hline
-19027.625 & 92689 & 304\\
\hline
-19027.625 & 39136 & 226\\
\hline
-19027.625 & 637345 & 19\\
\hline
-19027.625 & 937885 & 426\\
\hline
-19027.625 & 163110 & 584\\
\hline
-19027.625 & 455617 & 242\\
\hline
-19027.625 & 489927 & 520\\
\hline
-19035.071 & 584397 & 428\\
\hline
-19035.817 & 263049 & 454\\
\hline
-19035.817 & 173440 & 328\\
\hline
-19035.817 & 798839 & 312\\
\hline
-19035.817 & 539389 & 544\\
\hline
-19035.817 & 691234 & 250\\
\hline
-19035.817 & 723775 & 97\\
\hline
-19035.817 & 279850 & 555\\
\hline
-19035.817 & 802256 & 477\\
\hline
-19035.817 & 416463 & 467\\
\hline
-19036.005 & 794236 & 127\\
\hline
-19036.005 & 636396 & 168\\
\hline
-19036.005 & 848163 & 47\\
\hline
-19036.005 & 804561 & 59\\
\hline
-19036.086 & 673496 & 218\\
\hline
-19036.591 & 945065 & 255\\
\hline
-19036.591 & 667250 & 318\\
\hline
-19036.591 & 354559 & 73\\
\hline
-19037.447 & 860102 & 495\\
\hline
-19037.447 & 505879 & 424\\
\hline
-19037.447 & 686482 & 215\\
\hline
-19052.042 & 922596 & 456\\
\hline
-19066.855 & 804660 & 260\\
\hline
-19066.855 & 605161 & 409\\
\hline
-19068.402 & 496881 & 192\\
\hline
-19069.430 & 913639 & 162\\
\hline
-19069.430 & 645664 & 39\\
\hline
-19071.839 & 404426 & 344\\
\hline
-19071.839 & 505244 & 582\\
\hline
-19071.839 & 521575 & 313\\
\hline
-19073.111 & 392407 & 221\\
\hline
-19073.111 & 377504 & 294\\
\hline
-19075.142 & 566687 & 597\\
\hline
-19075.142 & 267983 & 228\\
\hline
-19075.142 & 156536 & 245\\
\hline
-19075.142 & 960438 & 116\\
\hline
-19082.931 & 78862 & 529\\
\hline
-19082.931 & 437181 & 135\\
\hline
-19083.642 & 126371 & 526\\
\hline
-19083.642 & 464179 & 106\\
\hline
-19086.243 & 281558 & 184\\
\hline
-19086.243 & 97158 & 205\\
\hline
-19089.999 & 478421 & 311\\
\hline
-19089.999 & 207896 & 25\\
\hline
-19089.999 & 321390 & 133\\
\hline
-19090.588 & 434915 & 552\\
\hline
-19090.588 & 399671 & 13\\
\hline
-19090.588 & 294669 & 501\\
\hline
-19097.524 & 695155 & 150\\
\hline
-19113.316 & 232226 & 235\\
\hline
\end{tabular}

\begin{center}\includegraphics[width=0.8\linewidth]{rosenberg-dissertation_files/figure-latex/spec-solutions-model2-4-1} \end{center}

\begin{tabular}{l|r|l}
\hline
LL & seed & m\_iterations\\
\hline
-18659.676 & 286735 & 175\\
\hline
-18659.676 & 349562 & 359\\
\hline
-18659.676 & 568859 & 49\\
\hline
-18686.131 & 562716 & 300\\
\hline
-18690.761 & 475420 & 71\\
\hline
-18690.761 & 147440 & 514\\
\hline
-18690.761 & 279850 & 555\\
\hline
-18690.761 & 667250 & 318\\
\hline
-18690.761 & 153394 & 429\\
\hline
-18709.289 & 327475 & 518\\
\hline
-18709.289 & 68850 & 462\\
\hline
-18709.289 & 259507 & 53\\
\hline
-18709.289 & 212934 & 568\\
\hline
-18710.414 & 185071 & 370\\
\hline
-18710.414 & 930323 & 267\\
\hline
-18710.414 & 506886 & 576\\
\hline
-18710.414 & 436460 & 89\\
\hline
-18710.414 & 802779 & 122\\
\hline
-18714.435 & 206099 & 363\\
\hline
-18714.435 & 831410 & 567\\
\hline
-18719.126 & 137377 & 397\\
\hline
-18719.126 & 415931 & 10\\
\hline
-18719.893 & 65651 & 214\\
\hline
-18719.893 & 112586 & 494\\
\hline
-18719.893 & 340112 & 126\\
\hline
-18719.893 & 772131 & 407\\
\hline
-18722.755 & 285380 & 1\\
\hline
-18722.755 & 12477 & 155\\
\hline
-18722.755 & 745972 & 521\\
\hline
-18722.755 & 484687 & 306\\
\hline
-18722.755 & 17359 & 227\\
\hline
-18722.755 & 965639 & 463\\
\hline
-18727.719 & 533738 & 11\\
\hline
-18735.773 & 333082 & 578\\
\hline
-18735.773 & 366706 & 29\\
\hline
-18735.773 & 674171 & 195\\
\hline
-18735.773 & 276102 & 599\\
\hline
-18735.773 & 777045 & 377\\
\hline
-18739.843 & 823392 & 479\\
\hline
-18740.947 & 879338 & 309\\
\hline
-18741.773 & 760531 & 550\\
\hline
-18741.773 & 407168 & 44\\
\hline
-18744.857 & 848331 & 137\\
\hline
-18746.059 & 830292 & 527\\
\hline
-18746.059 & 443442 & 380\\
\hline
-18746.059 & 39136 & 226\\
\hline
-18746.059 & 903420 & 5\\
\hline
-18746.059 & 723775 & 97\\
\hline
-18746.059 & 582296 & 452\\
\hline
-18746.059 & 331681 & 549\\
\hline
-18752.869 & 231281 & 542\\
\hline
-18771.078 & 392766 & 331\\
\hline
-18774.443 & 871438 & 561\\
\hline
-18774.443 & 396795 & 323\\
\hline
-18774.443 & 928287 & 197\\
\hline
-18774.443 & 608849 & 224\\
\hline
-18774.443 & 154575 & 539\\
\hline
-18774.443 & 746978 & 410\\
\hline
-18785.908 & 107446 & 12\\
\hline
-18786.976 & 140442 & 500\\
\hline
-18786.976 & 636396 & 168\\
\hline
-18802.065 & 761633 & 50\\
\hline
-18802.065 & 387701 & 275\\
\hline
-18802.065 & 92689 & 304\\
\hline
-18805.612 & 509733 & 130\\
\hline
-18805.612 & 195873 & 6\\
\hline
-18805.612 & 213532 & 503\\
\hline
-18805.612 & 638611 & 524\\
\hline
-18810.228 & 51375 & 148\\
\hline
-18810.228 & 520177 & 262\\
\hline
-18810.228 & 937885 & 426\\
\hline
-18810.228 & 85114 & 385\\
\hline
-18810.228 & 783165 & 170\\
\hline
-18822.378 & 391949 & 295\\
\hline
-18822.394 & 210870 & 383\\
\hline
-18822.394 & 342019 & 301\\
\hline
-18822.394 & 399508 & 415\\
\hline
-18822.394 & 50887 & 389\\
\hline
-18822.394 & 313407 & 132\\
\hline
-18834.182 & 790059 & 469\\
\hline
-18834.182 & 563002 & 360\\
\hline
-18839.173 & 298275 & 418\\
\hline
-18840.332 & 153942 & 31\\
\hline
-18840.332 & 194143 & 510\\
\hline
-18840.332 & 714455 & 476\\
\hline
-18840.332 & 282464 & 283\\
\hline
-18840.332 & 871851 & 257\\
\hline
-18840.332 & 22362 & 365\\
\hline
-18841.603 & 484501 & 163\\
\hline
-18841.642 & 804660 & 260\\
\hline
-18857.472 & 791285 & 416\\
\hline
-18857.472 & 464179 & 106\\
\hline
-18861.156 & 22874 & 588\\
\hline
-18866.028 & 124999 & 96\\
\hline
-18866.028 & 526324 & 178\\
\hline
-18871.939 & 519357 & 559\\
\hline
-18871.939 & 43523 & 297\\
\hline
-18871.939 & 888905 & 444\\
\hline
-18874.805 & 321390 & 133\\
\hline
-18884.189 & 197223 & 332\\
\hline
-18890.843 & 933578 & 506\\
\hline
-18892.147 & 49221 & 254\\
\hline
-18896.265 & 939021 & 8\\
\hline
-18896.915 & 970689 & 266\\
\hline
-18911.649 & 602797 & 336\\
\hline
-18919.265 & 505879 & 424\\
\hline
-18919.265 & 458181 & 189\\
\hline
-18919.973 & 192071 & 142\\
\hline
-18919.973 & 473942 & 574\\
\hline
-18926.744 & 592219 & 119\\
\hline
-18929.852 & 281558 & 184\\
\hline
-18932.405 & 535804 & 111\\
\hline
-18933.889 & 182524 & 373\\
\hline
-18940.568 & 848969 & 173\\
\hline
-18944.038 & 36714 & 201\\
\hline
-18947.565 & 481835 & 57\\
\hline
-18953.784 & 371246 & 101\\
\hline
-18955.999 & 15715 & 274\\
\hline
-19003.629 & 377504 & 294\\
\hline
\end{tabular}

\begin{center}\includegraphics[width=0.8\linewidth]{rosenberg-dissertation_files/figure-latex/spec-solutions-model2-5-1} \end{center}

\begin{tabular}{l|r|l}
\hline
LL & seed & m\_iterations\\
\hline
-18474.834 & 154575 & 539\\
\hline
-18474.834 & 436460 & 89\\
\hline
-18474.834 & 746978 & 410\\
\hline
-18474.834 & 85114 & 385\\
\hline
-18479.167 & 217130 & 443\\
\hline
-18479.167 & 539389 & 544\\
\hline
-18481.815 & 407108 & 366\\
\hline
-18481.815 & 165853 & 105\\
\hline
-18481.815 & 73576 & 213\\
\hline
-18481.815 & 471398 & 74\\
\hline
-18487.173 & 153942 & 31\\
\hline
-18492.782 & 392407 & 221\\
\hline
-18509.457 & 644297 & 340\\
\hline
-18539.422 & 850545 & 357\\
\hline
-18540.968 & 848969 & 173\\
\hline
-18549.013 & 416463 & 467\\
\hline
-18556.413 & 551639 & 55\\
\hline
-18557.749 & 331681 & 549\\
\hline
-18560.331 & 484687 & 306\\
\hline
-18568.774 & 354395 & 486\\
\hline
-18568.774 & 617243 & 237\\
\hline
-18569.499 & 851945 & 18\\
\hline
-18572.837 & 278692 & 342\\
\hline
-18572.837 & 780698 & 337\\
\hline
-18576.617 & 913639 & 162\\
\hline
-18585.655 & 751153 & 110\\
\hline
-18585.655 & 766903 & 505\\
\hline
-18588.405 & 210870 & 383\\
\hline
-18588.405 & 966014 & 37\\
\hline
-18590.065 & 923437 & 398\\
\hline
-18591.769 & 568859 & 49\\
\hline
-18594.202 & 790452 & 303\\
\hline
-18594.202 & 848163 & 47\\
\hline
-18605.815 & 126371 & 526\\
\hline
-18610.709 & 436892 & 565\\
\hline
-18610.709 & 76337 & 76\\
\hline
-18610.709 & 804561 & 59\\
\hline
-18610.709 & 473942 & 574\\
\hline
-18610.709 & 215353 & 164\\
\hline
-18611.947 & 760531 & 550\\
\hline
-18613.289 & 584397 & 428\\
\hline
-18613.289 & 313407 & 132\\
\hline
-18613.333 & 65651 & 214\\
\hline
-18614.460 & 153394 & 429\\
\hline
-18616.139 & 972873 & 157\\
\hline
-18617.816 & 440841 & 118\\
\hline
-18618.751 & 7959 & 256\\
\hline
-18620.397 & 17896 & 592\\
\hline
-18620.397 & 140849 & 515\\
\hline
-18620.397 & 971853 & 402\\
\hline
-18621.671 & 742609 & 531\\
\hline
-18624.013 & 188498 & 258\\
\hline
-18627.303 & 988761 & 475\\
\hline
-18627.462 & 963053 & 43\\
\hline
-18628.188 & 830570 & 369\\
\hline
-18629.568 & 69413 & 472\\
\hline
-18632.321 & 25127 & 107\\
\hline
-18635.892 & 579995 & 183\\
\hline
-18642.163 & 415931 & 10\\
\hline
-18642.163 & 973369 & 202\\
\hline
-18643.551 & 414828 & 322\\
\hline
-18643.929 & 939709 & 112\\
\hline
-18646.488 & 875667 & 367\\
\hline
-18651.435 & 57226 & 208\\
\hline
-18652.908 & 438144 & 271\\
\hline
-18654.588 & 319144 & 176\\
\hline
-18655.603 & 714455 & 476\\
\hline
-18656.401 & 173440 & 328\\
\hline
-18656.953 & 282464 & 283\\
\hline
-18662.580 & 903633 & 553\\
\hline
-18662.889 & 835767 & 210\\
\hline
-18662.889 & 43523 & 297\\
\hline
-18665.009 & 783110 & 72\\
\hline
-18668.469 & 789985 & 67\\
\hline
-18669.668 & 392751 & 480\\
\hline
-18676.047 & 68850 & 462\\
\hline
-18677.367 & 351622 & 551\\
\hline
-18678.466 & 340112 & 126\\
\hline
-18678.466 & 714997 & 399\\
\hline
-18680.137 & 853195 & 431\\
\hline
-18680.369 & 238906 & 430\\
\hline
-18680.369 & 321390 & 133\\
\hline
-18690.832 & 61587 & 400\\
\hline
-18691.782 & 1548 & 384\\
\hline
-18693.122 & 967902 & 52\\
\hline
-18700.745 & 694303 & 282\\
\hline
-18700.835 & 879211 & 453\\
\hline
-18700.835 & 51375 & 148\\
\hline
-18709.284 & 137377 & 397\\
\hline
-18710.302 & 476498 & 179\\
\hline
-18712.567 & 23012 & 352\\
\hline
-18713.084 & 704798 & 530\\
\hline
-18714.989 & 888905 & 444\\
\hline
-18714.989 & 790059 & 469\\
\hline
-18717.764 & 970689 & 266\\
\hline
-18719.173 & 521575 & 313\\
\hline
-18719.173 & 788796 & 145\\
\hline
-18734.282 & 802779 & 122\\
\hline
-18740.491 & 933578 & 506\\
\hline
-18740.491 & 211281 & 292\\
\hline
-18742.902 & 595153 & 230\\
\hline
-18746.059 & 172913 & 557\\
\hline
-18758.302 & 509733 & 130\\
\hline
-18773.621 & 285380 & 1\\
\hline
-18777.303 & 213532 & 503\\
\hline
-18784.247 & 327475 & 518\\
\hline
-18788.600 & 156536 & 245\\
\hline
-18792.351 & 497522 & 502\\
\hline
-18800.560 & 170118 & 238\\
\hline
-18804.554 & 464179 & 106\\
\hline
-18807.643 & 311214 & 64\\
\hline
-18822.394 & 576726 & 280\\
\hline
-18889.029 & 182524 & 373\\
\hline
-18906.043 & 264935 & 281\\
\hline
\end{tabular}

\begin{tabular}{l|r|l}
\hline
LL & seed & m\_iterations\\
\hline
-17098.434 & 344422 & 296\\
\hline
-17216.914 & 226322 & 478\\
\hline
-17714.856 & 853195 & 431\\
\hline
-18285.363 & 153053 & 378\\
\hline
-18304.150 & 211281 & 292\\
\hline
-18304.150 & 529496 & 343\\
\hline
-18320.492 & 350608 & 334\\
\hline
-18323.206 & 691234 & 250\\
\hline
-18337.703 & 425929 & 508\\
\hline
-18337.703 & 153394 & 429\\
\hline
-18338.421 & 68985 & 17\\
\hline
-18340.574 & 73576 & 213\\
\hline
-18345.377 & 575700 & 100\\
\hline
-18368.234 & 830392 & 35\\
\hline
-18371.468 & 407168 & 44\\
\hline
-18371.468 & 165853 & 105\\
\hline
-18378.197 & 370957 & 554\\
\hline
-18387.165 & 372176 & 23\\
\hline
-18393.205 & 355674 & 540\\
\hline
-18400.150 & 263268 & 165\\
\hline
-18403.549 & 253358 & 2\\
\hline
-18418.580 & 987090 & 70\\
\hline
-18421.113 & 789985 & 67\\
\hline
-18421.220 & 804561 & 59\\
\hline
-18425.035 & 15715 & 274\\
\hline
-18425.977 & 745972 & 521\\
\hline
-18431.713 & 644297 & 340\\
\hline
-18435.391 & 846194 & 93\\
\hline
-18451.974 & 194143 & 510\\
\hline
-18453.115 & 34346 & 330\\
\hline
-18454.109 & 561664 & 392\\
\hline
-18457.189 & 945065 & 255\\
\hline
-18460.060 & 967902 & 52\\
\hline
-18460.487 & 760531 & 550\\
\hline
-18460.487 & 714455 & 476\\
\hline
-18463.595 & 603842 & 61\\
\hline
-18467.842 & 903369 & 134\\
\hline
-18467.842 & 699810 & 571\\
\hline
-18482.213 & 137377 & 397\\
\hline
-18482.242 & 650371 & 14\\
\hline
-18482.699 & 441191 & 361\\
\hline
-18490.916 & 404510 & 442\\
\hline
-18493.050 & 788796 & 145\\
\hline
-18498.857 & 349263 & 263\\
\hline
-18499.853 & 851945 & 18\\
\hline
-18507.512 & 840078 & 203\\
\hline
-18507.949 & 85734 & 411\\
\hline
-18509.102 & 605358 & 321\\
\hline
-18509.460 & 937885 & 426\\
\hline
-18509.772 & 939709 & 112\\
\hline
-18510.632 & 377504 & 294\\
\hline
-18510.632 & 217744 & 326\\
\hline
-18511.430 & 333082 & 578\\
\hline
-18511.623 & 473942 & 574\\
\hline
-18512.092 & 595153 & 230\\
\hline
-18512.810 & 314084 & 81\\
\hline
-18514.055 & 57226 & 208\\
\hline
-18514.379 & 809240 & 543\\
\hline
-18516.024 & 535804 & 111\\
\hline
-18516.705 & 43523 & 297\\
\hline
-18518.585 & 910224 & 580\\
\hline
-18519.276 & 278692 & 342\\
\hline
-18525.109 & 507154 & 387\\
\hline
-18525.204 & 53621 & 483\\
\hline
-18531.309 & 173191 & 422\\
\hline
-18531.340 & 625191 & 350\\
\hline
-18531.719 & 217130 & 443\\
\hline
-18533.259 & 126371 & 526\\
\hline
-18533.892 & 576596 & 99\\
\hline
-18536.230 & 608496 & 4\\
\hline
-18539.996 & 349562 & 359\\
\hline
-18540.596 & 988761 & 475\\
\hline
-18541.029 & 584397 & 428\\
\hline
-18541.662 & 766903 & 505\\
\hline
-18542.372 & 478421 & 311\\
\hline
-18546.367 & 923437 & 398\\
\hline
-18546.716 & 565819 & 65\\
\hline
-18547.155 & 25127 & 107\\
\hline
-18551.742 & 692169 & 308\\
\hline
-18559.752 & 391949 & 295\\
\hline
-18566.107 & 314034 & 513\\
\hline
-18567.622 & 440841 & 118\\
\hline
-18568.395 & 84013 & 598\\
\hline
-18575.206 & 529455 & 268\\
\hline
-18580.753 & 992389 & 77\\
\hline
-18581.898 & 215353 & 164\\
\hline
-18588.791 & 508482 & 446\\
\hline
-18590.065 & 840031 & 276\\
\hline
-18593.301 & 636396 & 168\\
\hline
-18595.417 & 629320 & 222\\
\hline
-18597.570 & 396795 & 323\\
\hline
-18601.539 & 973369 & 202\\
\hline
-18607.314 & 995249 & 525\\
\hline
-18610.709 & 291149 & 536\\
\hline
-18618.751 & 972873 & 157\\
\hline
-18618.791 & 147440 & 514\\
\hline
-18618.791 & 313407 & 132\\
\hline
-18621.189 & 123985 & 248\\
\hline
-18654.438 & 438144 & 271\\
\hline
-18656.067 & 212934 & 568\\
\hline
-18660.737 & 638611 & 524\\
\hline
-18662.889 & 329127 & 185\\
\hline
-18687.183 & 359578 & 458\\
\hline
-18690.110 & 476498 & 179\\
\hline
\end{tabular}

\begin{center}\includegraphics[width=0.8\linewidth]{rosenberg-dissertation_files/figure-latex/spec-solutions-model2-7-1} \end{center}

\begin{tabular}{l|r|l}
\hline
LL & seed & m\_iterations\\
\hline
-17035.006 & 85734 & 411\\
\hline
-17035.006 & 344422 & 296\\
\hline
-18213.406 & 939021 & 8\\
\hline
-18214.792 & 458181 & 189\\
\hline
-18217.063 & 715255 & 523\\
\hline
-18227.574 & 126371 & 526\\
\hline
-18227.574 & 391949 & 295\\
\hline
-18234.603 & 30098 & 209\\
\hline
-18234.603 & 150531 & 154\\
\hline
-18234.603 & 790452 & 303\\
\hline
-18243.088 & 863691 & 481\\
\hline
-18249.303 & 823392 & 479\\
\hline
-18251.021 & 415502 & 194\\
\hline
-18252.559 & 863094 & 147\\
\hline
-18254.567 & 579995 & 183\\
\hline
-18255.084 & 751054 & 117\\
\hline
-18256.248 & 802256 & 477\\
\hline
-18256.586 & 535063 & 329\\
\hline
-18260.574 & 497522 & 502\\
\hline
-18262.825 & 414284 & 158\\
\hline
-18277.047 & 285380 & 1\\
\hline
-18281.407 & 846194 & 93\\
\hline
-18292.320 & 378393 & 509\\
\hline
-18302.227 & 608460 & 244\\
\hline
-18304.806 & 67009 & 564\\
\hline
-18323.206 & 802682 & 419\\
\hline
-18323.309 & 584397 & 428\\
\hline
-18327.896 & 533738 & 11\\
\hline
-18331.795 & 679832 & 302\\
\hline
-18331.795 & 605358 & 321\\
\hline
-18339.546 & 192071 & 142\\
\hline
-18339.549 & 848969 & 173\\
\hline
-18340.103 & 840031 & 276\\
\hline
-18345.784 & 473942 & 574\\
\hline
-18346.929 & 535804 & 111\\
\hline
-18347.305 & 84013 & 598\\
\hline
-18347.733 & 496710 & 386\\
\hline
-18348.790 & 575700 & 100\\
\hline
-18349.865 & 551639 & 55\\
\hline
-18354.367 & 850545 & 357\\
\hline
-18362.423 & 140849 & 515\\
\hline
-18363.008 & 902278 & 21\\
\hline
-18363.035 & 508482 & 446\\
\hline
-18363.056 & 788796 & 145\\
\hline
-18364.003 & 745972 & 521\\
\hline
-18364.003 & 396795 & 323\\
\hline
-18365.401 & 105435 & 265\\
\hline
-18369.099 & 928287 & 197\\
\hline
-18371.367 & 655497 & 376\\
\hline
-18372.372 & 351622 & 551\\
\hline
-18373.311 & 691234 & 250\\
\hline
-18373.728 & 791285 & 416\\
\hline
-18377.907 & 506886 & 576\\
\hline
-18379.072 & 567165 & 319\\
\hline
-18380.065 & 481835 & 57\\
\hline
-18381.203 & 404510 & 442\\
\hline
-18394.235 & 622860 & 259\\
\hline
-18397.920 & 879211 & 453\\
\hline
-18400.368 & 425929 & 508\\
\hline
-18401.340 & 714455 & 476\\
\hline
-18404.744 & 782821 & 272\\
\hline
-18409.271 & 349263 & 263\\
\hline
-18412.286 & 312754 & 562\\
\hline
-18417.806 & 922042 & 492\\
\hline
-18423.588 & 635245 & 121\\
\hline
-18424.106 & 499150 & 216\\
\hline
-18431.262 & 872743 & 374\\
\hline
-18434.814 & 7959 & 256\\
\hline
-18438.915 & 561664 & 392\\
\hline
-18444.381 & 25127 & 107\\
\hline
-18446.050 & 278692 & 342\\
\hline
-18447.972 & 418686 & 338\\
\hline
-18450.645 & 939709 & 112\\
\hline
-18459.869 & 172913 & 557\\
\hline
-18460.737 & 507154 & 387\\
\hline
-18461.328 & 217744 & 326\\
\hline
-18463.930 & 855760 & 593\\
\hline
-18464.873 & 903420 & 5\\
\hline
-18465.502 & 371737 & 532\\
\hline
-18465.917 & 27071 & 15\\
\hline
-18467.119 & 669634 & 335\\
\hline
-18467.840 & 923437 & 398\\
\hline
-18469.553 & 76337 & 76\\
\hline
-18477.481 & 714997 & 399\\
\hline
-18492.761 & 416463 & 467\\
\hline
-18493.050 & 789985 & 67\\
\hline
-18500.147 & 263268 & 165\\
\hline
-18511.046 & 383986 & 159\\
\hline
-18524.976 & 468036 & 131\\
\hline
-18528.015 & 978061 & 488\\
\hline
-18530.377 & 749635 & 420\\
\hline
-18538.510 & 260953 & 589\\
\hline
-18540.786 & 232559 & 136\\
\hline
-18547.639 & 165853 & 105\\
\hline
-18567.886 & 476498 & 179\\
\hline
-18579.855 & 471040 & 403\\
\hline
-18598.696 & 650371 & 14\\
\hline
\end{tabular}

\section{Research Question \#2}\label{research-question-2}

Research question \#2 is focused on the relations between each of the
profiles and the aspects of work with data.

\section{Research Question \#3}\label{research-question-3}

Research question \#3 is focused on

\section{Research Question \#4}\label{research-question-4}

Research question \#4 is focused on

\chapter{Discussion}\label{discussion}

\chapter{References}\label{references}

Akiva, T. (2005). Turning training into results: The new youth program
quality assessment. High/Scope Resource, 24(2), 21-24.\\
Bergman, L. R., \& Magnusson, D. (1997). A person-oriented approach in
research on developmental psychopathology. Development and
psychopathology, 9(2), 291-319.\\
Bergman, L. R., Magnusson, D., \& El Khouri, B. M. (2003). Studying
individual development in an interindividual context: A person-oriented
approach. Psychology Press.\\
Berland, L. K., Schwarz, C. V., Krist, C., Kenyon, L., Lo, A. S., \&
Reiser, B. J. (2016). Epistemologies in practice: Making scientific
practices meaningful for students. Journal of Research in Science
Teaching, 53(7), 1082-1112.\\
Bielik, T., \& Yarden, A. (2016). Promoting the asking of research
questions in a high-school biotechnology inquiry-oriented program.
International Journal of STEM Education, 3(1), 15.\\
Breckenridge, J. N. (2000). Validating cluster analysis: Consistent
replication and symmetry. Multivariate Behavioral Research, 35(2),
261-285.\\
Bystydzienski, J. M., Eisenhart, M., \& Bruning, M. (2015). High school
is not too late: Developing girls' interest and engagement in
engineering careers. Career Development Quarterly, 63(1), 88--95.
\url{http://doi.org/10.1002/j.2161-0045.2015.00097.x} Cohen, J. (1992).
A power primer. Psychological Bulletin, 112(1), 155.\\
National Governors Association Center for Best Practices, Council of
Chief State School Officers. (2010). Common Core State Standards for
Mathematics. Washington, DC: National Governors Association Center for
Best Practices and the Council of Chief State School Officers.\\
Corpus, J. H., \& Wormington, S. V. (2014). Profiles of intrinsic and
extrinsic motivations in elementary school: A longitudinal analysis. The
Journal of Experimental Education, 82(4), 480-501.\\
Csikszentmihalyi, M. (1990). Flow: The psychology of optimal
performance. Cambridge, England: Cambridge University Press.\\
Csikszentmihalyi, M. (1997). Finding flow: The psychology of engagement
with everyday life. New York, NY: Basic Books.\\
Creswell, J. W., Plano Clark, V. L., Gutmann, M. L., \& Hanson, W. E.
(2003). Advanced mixed methods research designs. In A. Tashakkori \& C.
Teddlie (Eds.), Handbook of mixed methods in social and behavioral
research (pp.~209--240). Thousand Oaks, CA: Sage.\\
English, L. D. (2012). Data modelling with first-grade students.
Educational Studies in Mathematics, 81(1), 15-30.\\
Finzer, W. (2013). The data science education dilemma. Technology
Innovations in Statistics Education, 7(2), p.~1-9.\\
Franklin, C., Kader, G., Mewborn, D., Moreno, J., Peck, R., Perry, M.,
\& Scheaffer, R. (2007). Guidelines for assessment and instruction in
statistics education (GAISE) report. Alexandria, VA: American
Statistical Association.\\
Fredricks, J. A., \& McColskey, W. (2012). The measurement of student
engagement: A comparative analysis of various methods and student
self-report instruments. In S. L. Christenson, A. L. Reschly, \& C.
Wylie (Eds.), The handbook of research on student engagement
(pp.~763--782). New York: Springer Science.
\url{https://doi.org/10.1007/978-1-4614-2018-7_37}\\
Fredricks, J. A., Blumenfeld, P. C., \& Paris, A. H. (2004). School
engagement: Potential of the concept, state of the evidence. Review of
Educational Research, 74(1), 59-109.\\
Fredricks, J. A., Filsecker, M., \& Lawson, M. A. (2016). Student
engagement, context, and adjustment: Addressing definitional,
measurement, and methodological issues. Learning \& Instruction, 43,
1-4.\\
Gelman, S. A., \& Markman, E. M. (1987). Young children's inductions
from natural kinds: The role of categories and appearances. Child
Development, 58(6), 1532-1541.\\
Gopnik, A., \& Sobel, D. M. (2000). Detecting blickets: How young
children use information about novel causal powers in categorization and
induction. Child Development, 71(5), 1205-1222.\\
Gopnik, A., Sobel, D. M., Schulz, L. E., \& Glymour, C. (2001). Causal
learning mechanisms in very young children: two-, three-, and
four-year-olds infer causal relations from patterns of variation and
covariation. Developmental Psychology, 37(5), 620.\\
Greene, B. A. (2015). Measuring cognitive engagement with self-report
scales: Reflections from over 20 years of research. Educational
Psychologist, 50(1), 14-30.\\
Greene, K. M., Lee, B., Constance, N., \& Hynes, K. (2013). Examining
youth and program predictors of engagement in out-of-school time
programs. Journal of Youth and Adolescence, 42(10), 1557-1572.\\
Hancock, C., Kaput, J. J., \& Goldsmith, L. T. (1992). Authentic inquiry
with data: Critical barriers to classroom implementation. Educational
Psychologist, 27(3), 337-364.\\
Harring, J. R., \& Hodis, F. A. (2016). Mixture modeling: Applications
in educational psychology. Educational Psychologist, 51(3-4), 354-367.\\
Hasson, E., \& Yarden, A. (2012). Separating the research question from
the laboratory techniques: Advancing high‐school biology teachers'
ability to ask research questions. Journal of Research in Science
Teaching, 49(10), 1296-1320.\\
Hayenga, A. O., \& Corpus, J. H. (2010). Profiles of intrinsic and
extrinsic motivations: A person-centered approach to motivation and
achievement in middle school. Motivation and Emotion, 34(4), 371-383.\\
Hektner, J. M., Schmidt, J. A., \& Csikszentmihalyi, M. (2007).
Experience sampling method: Measuring the quality of everyday life.
Sage.\\
Jahnukainen, M. (2010). Extreme cases. Encyclopedia of Case Study
Research. Thousand Oaks, CA: Sage.\\
Konold, C., \& Pollatsek, A. (2002). Data analysis as the search for
signals in noisy processes. Journal for Research in Mathematics
Education, 33(4), 259-289.\\
Lauer, P. A., Akiba, M., Wilkerson, S. B., Apthorp, H. S., Snow, D., \&
Martin-Glenn, M. L. (2006). Out-of-school-time programs: A meta-analysis
of effects for at-risk students. Review of educational research, 76(2),
275-313.\\
Lee, H. S., Angotti, R. L., \& Tarr, J. E. (2010). Making comparisons
between observed data and expected outcomes: students' informal
hypothesis testing with probability simulation tools. Statistics
Education Research Journal, 9(1), 68-96.\\
Lee, H., \& Hollebrands, K. (2008). Preparing to teach mathematics with
technology: An integrated approach to developing technological
pedagogical content knowledge. Contemporary Issues in Technology and
Teacher Education, 8(4), 326-341.\\
Lehrer, R., \& Romberg, T. (1996). Exploring children's data modeling.
Cognition and Instruction, 14(1), 69-108.\\
Lehrer, R., \& Schauble, L. (2004). Modeling natural variation through
distribution. American Educational Research Journal, 41(3), 635-679.\\
Lehrer, R. \& Schauble, L. (2015). Developing scientific thinking. In L.
S. Liben \& U. Müller (Eds.), Cognitive processes. Handbook of child
psychology and developmental science (Vol. 2, 7th ed., pp.~671-174).
Hoboken, NJ: Wiley.\\
Lehrer, R., Kim, M. J., \& Jones, R. S. (2011). Developing conceptions
of statistics by designing measures of distribution. ZDM, 43(5),
723-736.\\
Lehrer, R., Kim, M. J., \& Schauble, L. (2007). Supporting the
development of conceptions of statistics by engaging students in
measuring and modeling variability. International Journal of Computers
for Mathematical Learning, 12(3), 195-216.\\
Lesh, R., Middleton, J. A., Caylor, E., \& Gupta, S. (2008). A science
need: Designing tasks to engage students in modeling complex data.
Educational Studies in Mathematics, 68(2), 113-130.\\
Linnansaari, J., Viljaranta, J., Lavonen, J., Schneider, B., \&
Salmela-Aro, K. (2015). Finnish Students Engagement in Science Lessons.
NorDiNa: Nordic Studies in Science Education, 11(2), 192-206. Retrieved
from
\url{https://www.journals.uio.no/index.php/nordina/article/view/2047}\\
Lovett, M. C., \& Shah, P. (2007). Preface. In M. C. Lovett \& P. Shah
(Eds.), Thinking with data (pp.~x-xx {[}requested book through ILL to
confirm page \#s{]}). New York, NY: Lawrence Erlbaum.\\
Magnusson, D., \& Cairns, R. B. (1996). Developmental science: Toward a
unified framework. Cambridge, England: Cambridge University Press.\\
McNeill, K. L., \& Berland, L. (2017). What is (or should be) scientific
evidence use in k‐12 classrooms? Journal of Research in Science
Teaching, 54(5), 672-689.\\
Muthén, B. (2004). Latent variable analysis. The Sage handbook of
quantitative methodology for the social sciences. Thousand Oaks, CA:
Sage Publications, 345-68.\\
Muthén, L. K., \& Muthén, B. O. (1998-2017). Mplus User's Guide. Los
Angeles, CA: Muthén \& Muthén. NGSS Lead States. (2013). Next generation
science standards: For states, by states. Washington, DC: National
Academies Press.\\
Nolen, S. B., Horn, I. S., \& Ward, C. J. (2015). Situating motivation.
Educational Psychologist, 50(3), 234-247. Patall, E. A., Vasquez, A. C.,
Steingut, R. R., Trimble, S. S., \& Pituch, K. A. (2016). Daily
interest, engagement, and autonomy support in the high school science
classroom. Contemporary Educational Psychology, 46, 180-194.\\
Patall, E. A., Steingut, R. R., Vasquez, A. C., Trimble, S. S., Pituch,
K. A., \& Freeman, J. L. (2017). Daily Autonomy Supporting or Thwarting
and Students' Motivation and Engagement in the High School Science
Classroom. Journal of Educational Psychology. Advance online
publication. \url{http://dx.doi.org/10.1037/edu0000214}\\
Pekrun, R., \& Linnenbrink-Garcia, L. (2012). Academic emotions and
student engagement. In S. L. Christenson, A. L. Reschly, \& C. Wylie
(Eds.), Handbook of research on student engagement (pp.~259-292). New
York, NY: Springer.\\
Petrosino, A., Lehrer, R., \& Schauble, L. (2003). Structuring error and
experimental variation as distribution in the fourth grade. Mathematical
Thinking and Learning, 5 (2\&3), 131-156.\\
Piaget, J., \& Inhelder, B. (1969). The psychology of the child. New
York, NY: Basic Books.\\
Pöysä, S., Vasalampi, K., Muotka, J., Lerkkanen, M. K., Poikkeus, A. M.,
\& Nurmi, J. E. (2017). Variation in situation-specific engagement among
lower secondary school students. Learning and Instruction.
\url{http://dx.doi.org/10.1016/j.learninstruc.2017.07.007}\\
Salmela-Aro, K., Moeller, J., Schneider, B., Spicer, J., \& Lavonen, J.
(2016). Integrating the light and dark sides of student engagement using
person-oriented and situation-specific approaches. Learning and
Instruction, 43, 61-70.\\
Salmela-Aro, K., Muotka, J., Alho, K., Hakkarainen, K., \& Lonka, K.
(2016). School burnout and engagement profiles among digital natives in
Finland: A person-oriented approach. European Journal of Developmental
Psychology, 13(6), 704-718.\\
Schneider, B., Krajcik, J., Lavonen, J., Salmela‐Aro, K., Broda, M.,
Spicer, J., \ldots{} \& Viljaranta, J. (2016). Investigating optimal
learning moments in US and Finnish science classes. Journal of Research
in Science Teaching, 53(3), 400-421.\\
Schmidt, J. A., Rosenberg, J. M., Beymer, P. (advance online
publication). A person-in-context approach to student engagement in
science: Examining learning activities and choice. Journal of Research
in Science Teaching. \url{https://dx.doi.org/10.1002/tea.21409}\\
Schwarz, N., Kahneman, D., \& Xu, J. (2009). Global and episodic reports
of hedonic experience. In R. Belli, D. Alwen, \& F. Stafford (Eds.),
Using calendar and diary methods in life events research (pp.~157-174).
Newbury Park, CA: Sage.\\
Sfard, A. (1998). On two metaphors for learning and the dangers of
choosing just one. Educational Researcher, 27(2), 4-13.\\
Shernoff, D. J., Csikszentmihalyi, M., Schneider, B., \& Shernoff, E. S.
(2003). Student engagement in high school classrooms from the
perspective of flow theory. School Psychology Quarterly, 18(2),
158-176.\\
Shernoff, D. J., Kelly, S., Tonks, S. M., Anderson, B., Cavanagh, R. F.,
Sinha, S., \& Abdi, B. (2016). Student engagement as a function of
environmental complexity in high school classrooms. Learning and
Instruction, 43, 52-60.\\
Shumow, L., \& Schmidt, J. A. (2013). STEM interest and engagement (STEM
I.E.). National Science Foundation proposal for award number 1421198.\\
Sinatra, G. M., Heddy, B. C., \& Lombardi, D. (2015). The challenges of
defining and measuring student engagement in science. Educational
Psychologist, 50(1), 1-13. \url{doi:10.1080/00461520.2014.1002924}\\
Singh, K., Granville, M., \& Dika, S. (2002). Mathematics and science
achievement: Effects of motivation, interest, and academic engagement.
The Journal of Educational Research, 95(6), 323-332.\\
Shernoff, D. J., \& Schmidt, J. A. (2008). Further Evidence of an
Engagement--Achievement Paradox Among U.S. High School Students. Journal
of Youth and Adolescence, 37(5), 564--580.
\url{http://doi.org/10.1007/s10964-007-9241-z}\\
Shumow, L., Schmidt, J. A., \& Zaleski, D. J. (2013). Multiple
perspectives on student learning, engagement, and motivation in high
school biology labs. The High School Journal, 96(3), 232-252.\\
Skinner, E. A., \& Pitzer, J. (2012). Developmental dynamics of
engagement, coping, and everyday resilience. In S. Christenson, A.
Reschly, \& C. Wylie (Eds.), Handbook of Research on Student Engagement
(pp.~21-45). New York: Springer Science.\\
Skinner, E. A., Kindermann, T. A., \& Furrer, C. J. (2009). A
motivational perspective on engagement and disaffection:
Conceptualization and assessment of children's behavioral and emotional
participation in academic activities in the classroom. Educational and
Psychological Measurement, 69(3), 493-525.\\
Skinner, E., Furrer, C., Marchand, G., \& Kindermann, T. (2008).
Engagement and disaffection in the classroom: Part of a larger
motivational dynamic? Journal of Educational Psychology, 100(4), 765.\\
Steinley, D., \& Brusco, M. J. (2011). Evaluating mixture modeling for
clustering: recommendations and cautions. Psychological Methods, 16(1),
63.\\
Stohl, H., \& Tarr, J. E. (2002). Developing notions of inference using
probability simulation tools. The Journal of Mathematical Behavior,
21(3), 319-337.\\
Stroupe, D. (2014). Examining classroom science practice communities:
How teachers and students negotiate epistemic agency and learn
science‐as‐practice. Science Education, 98(3), 487-516.\\
Strati, A. D., Schmidt, J. A., \& Maier, K. S. (2017). Perceived
challenge, teacher support, and teacher obstruction as predictors of
student engagement. Journal of Educational Psychology, 109(1),
131-147.\\
Trevors, G. J., Kendeou, P., Bråten, I., \& Braasch, J. L. (2017).
Adolescents' epistemic profiles in the service of knowledge revision.
Contemporary Educational Psychology, 49, 107-120.\\
Turner, J. C., \& Meyer, D. K. (2000). Studying and understanding the
instructional contexts of classrooms: Using our past to forge our
future. Educational Psychologist, 35(2), 69-85.\\
van Rooij, E. C., Jansen, E. P., \& van de Grift, W. J. (2017).
Secondary school students' engagement profiles and their relationship
with academic adjustment and achievement in university. Learning and
Individual Differences, 54, 9-19.\\
Vandell, D. L., Hall, V., O'Cadiz, P., \& Karsh, A. (2012). Piloting
outcome measures for summer learning initiative programs. Final report
to the David and Lucile Packard Foundation, Children, Families, and
Communities Program. Retrieved from
\url{http://faculty.sites.uci.edu/childcare/files/2013/07/SL-Outcomes-2011-Pilot_Edited_8.19.pdf}\\
Wang, M. T., \& Eccles, J. S. (2012). Social support matters:
Longitudinal effects of social support on three dimensions of school
engagement from middle to high school. Child Development, 83(3),
877-895.\\
Wang, M. T., \& Holcombe, R. (2010). Adolescents' perceptions of school
environment, engagement, and academic achievement in middle school.
American Educational Research Journal, 47(3), 633-662.\\
Westfall, J., Kenny, D. A., \& Judd, C. M. (2014). Statistical power and
optimal design in experiments in which samples of participants respond
to samples of stimuli. Journal of Experimental Psychology: General,
143(5), 2020-2045.\\
Westfall, J. (2016). PANGEA: Power Analysis for General Anova designs.
Retrieved from \url{https://jakewestfall.shinyapps.io/pangea/}\\
Wild, C. J., \& Pfannkuch, M. (1999). Statistical thinking in empirical
enquiry. International Statistical Review, 67(3), 223-248.\\
Wilkerson, M. H., Andrews, C., Shaban, Y., Laina, V., \& Gravel, B. E.
(2016). What's the technology for? Teacher attention and pedagogical
goals in a modeling-focused professional development workshop. Journal
of Science Teacher Education, 27(1), 11-33.\\
Wilkerson, M. H. \& Fenwick, M. (2017). The practice of using
mathematics and computational thinking. In C. V. Schwarz, C. Passmore,
\& B. J. Reiser (Eds.), Helping Students Make Sense of the World Using
Next Generation Science and Engineering Practices. Arlington, VA:
National Science Teachers' Association Press. pp.~181-204.\\
Witherington, D. C. (2015). Dynamic systems in developmental science. In
W. F. Overton \& P. C. M. Molenaar (Vol. Eds.) \& R. M. Lerner (Ed.),
Handbook of child psychology and developmental science. Vol. 1: Theory
\& method (7th ed., pp.~63-112). Hoboken, NJ: Wiley.\\
Wormington, S. V., \& Linnenbrink-Garcia, L. (advance online
publication). A new look at multiple goal pursuit: The promise of a
person-centered approach. Educational Psychology Review.
\url{doi:10.1007/s10648-016-9358-2}

\bibliography{book.bib,packages.bib}


\end{document}
