# Literature Review

What is data analysis and what has past research taught us about it? This section defines data analysis as a key practice across STEM domains, with a focus on work with data as activities that are both very specific to work with data (i.e., constructing measures and data modeling) and activities that are more general across STEM domains (i.e., asking questions and interpreting findings). This section also reviews gaps in the literature and introduces engagement and “influencers” of engagement, or factors that past research indicates can impact learners’ engagement, to establish the conceptual framework used in the present study. 

## Defining Work With Data

As described in the introduction to this section, some scholars have focused on a few key pieces of data analysis connected through the use of “data to solve real problems and to answer authentic questions” (Hancock et al., 1992, p. 337). This approach is commonly described as including two goals: 1) creating data through constructing measures and collecting data and 2) accounting for variability in data through models, or data modeling (English, 2012; Hancock et al., 1992; Lehrer & Romberg, 1996; Lesh et al., 2008). This approach has primarily been taken up by mathematics educators and is reflected in statistics curriculum documents (Franklin et al., 2007). In science settings, where answering questions about phenomena serve as the focus of activities, it shares features of the process of engaging in scientific and engineering practices but has been less often studied. 

Scholars have conceived of working with data in different ways, but some core components have emerged. For instance, Wild and Pfannkuch (1999) consider the process in terms of identifying a problem, generating a measurement system and sampling plan, collecting and cleaning the data, exploring the data and carrying out planned analyses, and interpreting the findings from the analysis. Such a process is common in STEM content areas, particularly across statistics education research and is instantiated in standards for curricula: Franklin et al.’s guidelines for the American Statistical Association focus on the Framework for statistical problem solving: formulating questions, collecting data, analyzing data, and interpreting results (2007). The goals of this framework and its components are similar to Hancock et al.’s (1992) description of “using data to solve real problems and to answer authentic questions” (p. 337). Scholars have subsequently expanded Hancock et al.’s definition of to include six components: asking questions, generating measures, collecting data, structuring data, visualizing data, and making inferences in light of variability (see Lehrer & Schauble, 2004). The last of these components is crucial across all of the visions of work with data reviewed here and distinguishes these processes from other aspects of data analysis: Accounting for variability (or uncertainty) is central to solving real-world problems with data and the process of data modeling.

The five aspects of work with data. The definition of working with data used in the present study represents a synthesis across these existing accounts of this process and focuses on five aspects that are common to them. Engagement in work with data, then, includes five processes that are part of a cycle (Franklin et al., 2007; Lee & Tran, 2015; Wild & Pfannkuch, 1999). Those processes are: asking questions or identifying problems, making observations,  generating data, data modeling (to account for variability or uncertainty), and interpreting and communicating findings. 
The five practices depicted in Figure 1, are a cycle because not only does each part follow that before it, but also because the overall process is iterative: interpreting findings commonly leads to new questions and subsequent engagement in work with data. The first process, asking questions, is about generating questions that can be answered with empirical evidence. The next, making observations is about watching phenomena and noticing what is happening with respect to the phenomena or problem being investigated. This is followed by generating data, the process of figuring out how or why to inscribe an observation as data about a phenomena, as well as generating coding frames or tools for measuring. Next, because data are often messy, data modeling is a necessary step follows from its creation or collection. Data models include simple statistics, such as the mean and variance, as well as more complicated models, such as linear models and extensions of the linear model. Finally, the last step is to interpret and communicate findings regarding the phenomena that the question is about. 

**Figure 1. Work with data in STEM education settings.**
 
Also, as depicted in Figure 1, scholars have pointed out some key features of how work with data is carried out that impact their effectiveness as a pedagogical approach. These key features include an emphasis on making sense of real-world phenomena and iterative cycles of engaging in work with data and collaboration and dialogue, through which ideas and intermediate findings are critiqued and subject to critique, and revised over time (McNeill & Berland, 2017). As we will discuss later, these factors might have the potential to impact engagement through the proximal conditions of challenge and competence.

The role of work with data in the curriculum. Scholars argue that work with data can serve as an organizing set of practices for engaging in inquiry in STEM settings (Lehrer & Schauble, 2015). Data are both encountered and generated by learners, and so opportunities for STEM students to work with data provide many opportunities to leverage students’ curiosity because processes of inquiry can be grounded in phenomena that learners themselves can see and manipulate or phenomena that learners are interested in. Also important, becoming proficient in work with data can provide learners with an in-demand capability in society, owing to the number of occupations, from education to entrepreneurship, that demand or involve taking action based on data (Wilkerson & Fenwick, 2017). Furthermore, becoming proficient in work with data can be personally empowering because of the parts of our lives—from paying energy bills to interpreting news articles—that use data.

Recent reform efforts emphasize work with data (i.e., the scientific and engineering practices in the NGSS and the standards for mathematical practice in the Common Core State Standards). However, work with data is uncommon in many classroom settings (McNeill & Berland, 2017), and so learning environments suited to engaging in work with data, but not explicitly designed to support it, may be valuable to study because they may serve as incubators of these rare and challenging learning activities.

Work with data is related to what is commonly described as data analysis in K-12 settings, though data analysis as described in curricular standards and policy documents can take many forms: from learning about what we already know to systematic efforts to measure large, small, or hard to study phenomena. Data analysis includes both individual cognitive processes, such as reasoning about what counts as a good source of data and coordinated social processes, like sharing what is found with others (Lovett & Shah, 2007). Many policy and curricular documents characterize data analysis as using data to explain or predict phenomena (i.e., National Governors Association Center for Best Practices, Council of Chief State School Officers, 2010; NGSS Lead States, 2013). The range of capabilities included within data analysis is large, ranging from collecting insufficient data to construct an answer to a question, interpreting already-created figures or analyzing already-collected data, and seeking to develop answers to questions that are already known. In addition, teachers and other stakeholders do data analysis in very different ways, with greater or lesser veracity to the aims of data analysis (McNeill & Berland, 2017). Thus, work with data as defined in this study include both more specific aspects of data analysis (constructing measures and data modeling) and more general aspects, such as asking questions and interpreting findings.

Outside-of-school programs are a potentially valuable setting to explore engagement in work with data because of the combined pedagogical and technical expertise of their staff and the activities learners do during their participation in them. Staff for these programs includes educators and scientists, engineers, and others with the technical experience. Additionally, the programs were designed to involve learners in the types of real-world practices experienced by experts in STEM disciplines. Attendance in such programs is associated with many benefits to learners (Green, Lee, Constance, & Hynes, 2013; see Lauer, Akiba, Wilkerson, Apthorp, Snow, & Martin-Glenn, 2006, for a comprehensive review). These programs are also selected because little research has examined how data are part of the experiences of youth in out-of-school-time programs, despite its place as one of a few core practices in STEM. While these reasons to study work with data focus on outside-of-school programs, they are also germane to more formal learning environments, such as classrooms, in which teachers want to design opportunities for their learners to work with data. This is important even for those teachers who themselves have technical expertise, but who have experienced limited training and support for engaging learners in work with data. Therefore, these programs can provide insight into whether engaging in work with data is associated with more optimal forms of engagement in the conditions like those for classrooms in which engaging in work with data is a novel and potentially promising approach to doing and learning about STEM.

## What We Know (And Do Not Know) About Engagement in Work with Data

Research related to engagement in work with data has been carried out by developmental and educational psychologists as well as by mathematics and science educators (see Lehrer and Schauble, 2015, for a review). This research has been carried out in laboratories and classroom settings. For this study, key findings from past studies are organized around three themes:
1. Specific cognitive outcomes
2. Learners’ capability to participate in each of the aspects of work with data
3. Strategies to address key challenges of engaging in each of the aspects of work with data

First, scholars have researched cognitive capabilities related to work with data. Much of this laboratory-based research has focused on how children develop the capability to inductively reason from observations (Gelman & Markman, 1987). Other research has focused on the development of causal, or mechanistic, reasoning, among young children (Gopnik et al., 2001; Gopnik & Sobel, 2000), often from a Piagetian, individual-development focused tradition (i.e., Piaget & Inhelder, 1969). A key outcome of engaging in work with data has to do with how learners account for variability (Lehrer, Kim, & Schauble, 2007; Petrosino, Lehrer, & Schauble, 2003; Lesh, Middleton, Caylor, & Gupta, 2008; Lee, Angotti, & Tarr, 2010), arguably the main goal of engaging in work with data (Konold & Pollatsek, 2002). From this research, we know that learners can develop the capacity to reason about variability (and covariability).

Second, we know that different aspects of work with data pose unique opportunities and challenges. Asking empirical questions requires experience and ample time to ask a question that is both able to be answered with data and which is sustaining and worth investigating (Bielik, 2016; Hasson & Yarden, 2012). Constructing measures, such as of the height of the school’s flagpole, requires negotiation not only of what to measure, but how and how many times to measure it (Lehrer, Kim, & Schauble, 2007). Regarding modeling, not only teaching students about models, such as that of the mean, but also asking them to create them, are valuable and practical (Lehrer & Schauble, 2004; Lehrer, Kim, & Jones, 2011), but also time-intensive. Interpreting findings, especially in light of variability through models, and communicating answers to questions, means not only identifying error but understanding its sources, and can be supported through exploring models that deliberately represent the data poorly, but can be instructive for probing the benefits and weaknesses of models (Lee & Hollebrands, 2008; Lehrer, Kim, & Schauble, 2007). 
In the context of these opportunities and challenges, how learners participate in different aspects of work with data in terms of engagement theory has not been a focus of research. Consider the process of structuring data, commonly described as a—or the—key part of many applied data analyses, that is also under-emphasized in students’ use of data in science settings in which students are provided already-processed, or plotted, data (McNeill & Berland, 2017). How challenging do students perceive these activities to be? How to they perceive their competence regarding this activity? More importantly, how do they engage—cognitively, behaviorally, and affectively—during these experiences? Knowing more about these processes could help us to develop informed recommendations for teachers and designers intending to bring about opportunities for learners to engage in work with data in a better-supported way that is sustained over time.

Third, strategies to support engagement in work with data have included design of curricula, development of instructional strategies supported through collaborations between researchers and teachers, and often, technological tools. At present, opportunities for students to engage in work with data, or analyze data to solve real problems and to answer authentic questions, are limited in K-12 STEM settings. Much of the research in science settings focuses on evidence use, which can include data, but also includes other forms of evidence, such as those from authoritative sources (McNeill & Berland, 2016). Furthermore, creating and constructing models of primary data takes ample time (Dickes, Sengupta, Farris, & Basu, 2016), and doing so even in mathematics settings is uncommon (Lehrer & Schauble, 2015). Furthermore, providing opportunities for students to engage in work with data requires a shift in educational norms and curricular resources, aligned standards and assessments, and teacher professional development (McNeill & Berland, 2017; Wilkerson-Jerde, Andrews, Shaban, Laina, & Gravel, 2016). From this research, we know about specific strategies and learning progressions for learners to develop this capability, such as the role of measurement in exposing learners in a direct way to sources of variability (Petrosino et al., 2003), role of simulation to learn about sampling distributions (Stohl & Tarr, 2002), and use of relevant phenomena, such as manufacturing processes, such as the size of metallic bolts, which can help learners to focus on “tracking a process by looking at its output” (Konold & Pollatsek, 2002, p. 282). 
 
## Engagement in STEM Domains

The nature of engagement is discussed in terms of general features that have been identified across content area domains, conditions that support engagement, and differences between engagement in general and in STEM settings. This is followed by a discussion of two key features of engagement: its dynamic characteristics and what a person-oriented approach to its study can add to research about engagement and its impact on learning and other outcomes. 

General characteristics of engagement. Engagement is defined in this study as active involvement, or investment, in activities (Blumenfeld et al., 2004). Explaining how learners are involved in activities and tasks is especially important if we want to know about what aspects of work with data are most engaging (and in what ways), and therefore can serve as exemplary for others advancing work with data as well as those calling for greater support for engagement. Apart from being focused on involvement, engagement is often thought of as a meta-construct, that is, one that is made up of other constructs (Skinner & Pitzer, 2012; Skinner, Kindermann, & Furrer, 2009). By defining engagement as a meta-construct, scholars characterize it in terms of cognitive, behavioral, and affective dimensions that are distinct yet interrelated (Fredricks, 2016). We know from past research that the cognitive, behavioral, and affective dimensions of engagement can be distinguished (Wang & Eccles, 2012; Wang & Holcombe, 2012) and that while there are long-standing concerns about the conceptual breadth of engagement (Fredricks et al., 2016), careful justification and thoughtful use of multidimensional engagement constructs and measures is warranted based on past research. 

Recent scholarship has summarized key characteristics of engagement and outcomes from being engaged at school and in other learning environments (Fredricks, 2016), defined for STEM domains in the next section. Engagement is also considered to be dynamic and changing in response to individual, situation or moment, and broader contextual factors, such as the family, classroom, or outside-of-school programs. Many conceptualizations of engagement include cognitive, behavioral, and affective dimensions, but the contents of these dimensions can vary across domains, as discussed in the next section about STEM content areas.

Characteristics of engagement in STEM domains. Engagement in STEM settings shares characteristics with engagement across disciplines, yet there are some distinct aspects of it (Greene, 2015). While one type of engagement—behavioral—is associated with positive outcomes, many STEM practices call for engagement in additional ways (Sinatra et al., 2015), especially around epistemic and agency-related dimensions. For example, many scholars have defined scientific and engineering practices as epistemic practices, which involve applying epistemic considerations around sources of evidence and the nature of explanatory processes (Berland et al., 2016; Stroupe, 2014). The emphasis on developing new knowledge and capabilities through engaging in STEM practices is a potentially important aspect. This is important because measures of engagement might need to be modified for use in STEM domains. Because of the importance of constructing knowledge to engagement in STEM practices, then, cognitive engagement is defined for this study in terms of learning something new or getting better at something. 

The behavioral and affective aspects of engagement in STEM settings are arguably more similar to engagement in general than cognitive engagement. While sometimes defined in terms of extra-curricular involvement or following directions, behavioral engagement is defined in this study as working hard at and concentrating on learning-related activities (Fredricks et al., 2004; Singh, Granville, & Dika, 2002). Finally, affective engagement is defined as affective responses to activities, such as being excited, angry, or relaxed (Pekrun & Linnenbrink-Garcia, 2012). 

Key conditions that support engagement. In particular for engagement—about involvement in activities—past research has shown that ESM can help us to find out what conditions support it. Past research suggests that not only learner-level characteristics, such as learners’ interest in the domain of study, but also dynamic, changing moment-to-moment conditions are also important (Shernoff et al., 2003; Shernoff et al., 2016; Shumow, Schmidt, & Zaleski, 2013). Focusing on dynamic conditions, Emergent Motivation Theory (EMT; Csikszentmihalyi, 1990), provides a useful lens. From EMT, a key momentary influencer of engagement is how difficult individuals perceive an activity to be, or its perceived challenge. Another key influencer is how good at an activity individuals perceive themselves to be, or their perceived competence. Most important, from the perspective of EMT, being challenged by and good at an activity are especially engaging experienced when together. Past research has supported this contention. Shernoff et al. (2016), for example, demonstrated that while challenge and skill with high levels of one but low levels on the other (i.e., high challenge and low skill) were not broadly associated with positive forms of engagement, their interaction was, suggesting that learners’ perceptions of the challenge of the activity, and their perceptions of how skillful they are, are important for explaining why learners engage. 

Other key conditions that support engagement concern teacher support (Strati, Schmidt, & Maier, 2017). Particularly concerning work with data, which is demanding not only for learners but also teachers, sustained support from teachers is an essential component of learners being able to work with data (Lehrer & Schauble, 2015; Wilkerson, Andrews, Shaban, Laina, & Gravel, 2016). Consequently, this study considers not only profiles of engagement, but also the conditions of engagement as part in terms of both learners’ subjective experiences and support from the instructors. The conditions included in the PECs relate to learners’ subjective perceptions of two key factors suggested by past research and theory, in particular, how challenging they perceive the activity to be and how good at it they perceive themselves to be (Csikszentmihalyi, 1990). In recognition of differences among learners in their tendency to engage in different (higher or lower) ways in specific activities based in part on individual differences (Hidi & Renninger, 2006), learners’ interest in STEM before the start of the programs is also considered as a factor that can impact engagement. Instructional support for work with data is also considered through the creation of codes for activities in which students are involved with data and the instructors are providing support for the activity in which they are engaged. Finally, gender and the racial and ethnic group of students is added, as past research has indicated these as factors that influence engagement in STEM (Bystydzienski, Eisenhart, & Bruning; Shernoff & Schmidt, 2008). These conditions are different from those discussed in the section on the five aspects of work with data in that they are teacher-related factors (with respect to instructional support), subjective factors (with respect to perceptions of challenge and competence), and demographic characteristics, whereas a focus on real-world phenomena, iterative cycles, and collaboration and dialogue may potentially impact engagement through learners’ perceiving the activity to be supported by the subjective contextual conditions of challenge and competence. 

## Using ESM to Study the Dynamics of Engagement

A number of scholars, in recognition of the dynamic nature of engagement, have explored the use of Experience Sampling Method (ESM) to understand engagement (e.g., Strati et al., 2017)—or have recommended it is as a valuable approach for doing so (Turner & Meyer, 2000; Sinatra et al., 2015). ESM involves asking—usually using a digital tool and occasionally a diary—to ask participants short questions about their experiences. ESM is particularly well-suited to understanding the dynamic nature of engagement because students answered brief surveys about their experience when they were signaled, minimally interrupting them from the activity they are engaged in and also seeking to collect measures about learners’ experience when signaled (Hektner, et al., 2007). 

Research how shown us how the use of ESM can lead to distinct research contributions. Shernoff, Csikszentmihalyi, Schneider, and Shernoff (2003) examined engagement through the use of measures aligned with flow theory, namely, using measures of concentration, interest, and enjoyment (Csikszentmihalyi, 1997). In a study using the same measures of engagement (concentration, interest, and enjoyment) Shernoff et al. (2016) used an observational measure of challenge and control (or environmental complexity) and found that it significantly predicted engagement, as well as self-esteem, intrinsic motivation, and academic intensity. Schneider et al. (2016) and Linnansaari et al. (2015) examined features of optimal learning moments or moments in which students report high levels of interest, skill, and challenge, as well as their antecedents and consequences. Similar to ESM in that through its use engagement can be studied in a more context-sensitive, still other scholars have used daily diary studies to examine engagement as a function of autonomy-supportive classroom practices (Patall, Vasquez, Steingut, Trimble, & Pituch, 2015; Patall, Steingut, Vasquez, Trimble, & Freeman, 2017). This past research that used ESM (or daily diary studies) to study engagement has shown us that the methodological approach can be used to answer questions that were hard to answer using the more-traditional pre- or post-survey measures. 

Other research shows us that there are newer approaches to analyzing ESM data that can contribute insights into the dynamics of engagement in a more fine-grained way. For example, Strati et al. (2017) explored the relations between engagement to measures of teacher support, finding associations between instrumental support and engagement and powerfully demonstrating the capacity of ESM to understand some of the dynamics of engagement. Similarly, Poysa et al. (2017) used a similar data analytic approach as Strati et al. (2017), that is, use of crossed effects models for variation within both students and time points, both within and between days. These studies establish the value of the use of ESM to understand the dynamics of engagement and that such an approach may be able to be used to understand engaging in work with data. Additionally, these studies show that how effects at different levels are treated, namely, how variability at these levels is accounted for through random effects as part of mixed effects models, is a key practical consideration for analysts of ESM data.

## A Person-Oriented Approach to Engagement

One powerful and increasingly widely used way to examine dynamic constructs holistically is a person-oriented approach, which can be used to consider the way in which psychological constructs are experienced together and at once in the experiences of learners. In the context of the present study, this approach can help us to identify naturally occurring profiles of engagement and its conditions that capture both the cognitive, behavioral, and affective dimensions of engagement and the subjective conditions of challenge and competence to understand how students experience engagement and its conditions in a more holistic way. The person-oriented view, developed within developmental science, emphasizes these groups of constructs in light of the dynamic nature of learning and development, and the importance of both person-level and contextual factors upon these dynamics (Bergman & El-Khouri, 1997; Magnusson & Cairns, 1996), though recent conceptions of the developmental science approach sometimes differ in the extent to which they acknowledge these contextual factors (Witherington, 2015). Though studies examining learning from a person-oriented perspective are not very common, some examples include studies of intrinsic and extrinsic motivation (Corpus & Wormington, 2014; Hayenga & Corpus, 2010), profiles of achievement goals (see Wormington & Linnenbrink-Garcia, advance online publication, for a review), and epistemic cognition (Trevors, Kendeou, Braten, & Braasch, 2017). 

There are some recent studies taking a person-oriented approach to the study of engagement (i.e., Salmela-Aro, Moeller, Schneider, Spicer, & Lavonen, 2016a; Salmela-Aro, Muotka, Alho, Hakkarainen, & Lonka, 2016b; Van Rooij, Jansen, & van de Grift, 2017; Schmidt, Rosenberg, & Beymer, advance online publication). Van Rooij et al. (2017) identified five secondary school student profiles, derived from three dimensions of student engagement: behavioral engagement, cognitive engagement, and intellectual engagement. Salmela-Aro et al. (2016b) examined burnout and engagement using a person-oriented approach. While not using ESM, this study demonstrated the use of a person-oriented approach including (although not focused on profiles comprised exclusively of) engagement. Examining the same variables (engagement and the three aspects of school burn-out) and others, Salmela-Aro et al. (2016b) demonstrated substantial differences in student momentary resources, demands, and engagement across the four profiles and contributes to a rich understanding of engagement in situ yet does not conduct profiles of engagement at the momentary level. 

Using profiles to account for the dynamics of a multidimensional construct. The person-oriented approach has an important implication for how we consider engagement, in particular when we consider how to understand engagement as a meta-construct (Skinner, Kindermann, & Furrer, 2009) and how to account for its dynamic nature (Csikszentmihalyi, 1990). Regarding engagement as a meta-construct, we know from both engagement and person-oriented research that engagement can be explained in terms of different patterns among its individual components (Bergman & Magnusson, 1997), in the present case its cognitive, behavioral, and affective components. Because learners’ engagement includes cognitive, behavioral, and affective aspects experienced together at the same time, it can be experienced as a combined effect that is categorically distinct from the effects of the individual dimensions of engagement. This combined effect can be considered as profiles of engagement. Past studies have considered profiles of cognitive, behavioral, and affective aspects of engagement. For example, Schmidt et al. (advance online publication) demonstrated how ESM and the person-oriented approach can be combined to learn about engagement in terms of how cognitive, behavioral, and affective engagement are experienced at once, and how they exhibit differences across activities and learners’ reports of the choices related to the activity that they were able to make. Note that while the person-oriented approach considers the relations among variables together and at once in the experience of learners, they can also be used as part of variable-oriented analyses, and in particular analyses that account for how responses are nested within students, as in repeated measures and longitudinal sources of data.

To account for the dynamic nature of engagement, some past studies have used other measures to predict engagement, such as use of in-the-moment resources and demands (Salmela-Aro et al., 2016b) or, in the case of the study reviewed in the previous section, use of instructional activities and choice (Schmidt et al., advance online publication). For example, Schmidt et al. explored how in the case of laboratory-related activities—especially those that learners perceived as offering them greater choice in the goals of the activity—were associated with more optimal profiles of momentary engagement. Using a person-oriented approach and the use of profiles of cognitive, behavioral, and affective engagement, this study suggests that laboratory related activities akin to those characterized by work with data in which learners have to make choices about how to carry out the analysis may be important predictors of engagement. Another potential way to account for the dynamics of engagement is to consider both engagement and its conditions at once. Since a person-oriented approach emphasizes the dynamic nature of development and the impact of not only external but also intra-individual factors, momentary factors such as resources and demands, could be used along with the measures of engagement to construct momentary profiles.

## Need for the Present Study

While many scholars have argued that work with data can be understood in terms of the capabilities learners develop and the outcome learners achieve, there is a need to better understand learners’ experience in terms of contemporary engagement theory. Doing so can help us to understand work with data in terms of learner's experience, which we know from past research impacts what and how students learn (Sinatra et al., 2015), yet which has not been brought to bear on the topic of engagement in work with data. In particular, the use of ESM and a person-oriented approach allow us to study engage in a way aligned with how scholars have recently considered engagement, namely, as something that is dynamic and as something that is multifaceted, including multiple dimensions of engagement and the (subjective and instruction-related) conditions that support engagement. Knowing more about students’ engagement can help us to design activities and interventions focused around work with data that are more engaging and which provide more support to learners in terms of their perceptions of challenge and their own competence. While other lenses can be brought to bear to better understand—and support—engagement in work with data, contemporary engagement theory not only has the power to explain differences in how students engage in data modeling, but it also aligns with how both teachers and recent curricular standards consider engagement. 

In addition to this general need to study engagement in work with data from the perspective of contemporary engagement theory, no research that I am aware of has examined work with data or data analysis more generally in the context of outside-of-school programs. These settings are potentially rich with opportunities for highly engaged learners to analyze authentic data sources. Third, little research has examined how data is part of the experiences of youth in out-of-school-time programs, despite its place as one of a few core practices in STEM. Fourth, this study employs a data analytic approach that allows for accounting for student, program, and momentary impacts on engagement, at this time an approach that has only been conducted as part of two studies, Strati et al. (2017) and Poysa et al. (2017). Fifth, most studies of engagement have considered it in terms of the individual components of engagement, rather than in terms of profiles of engagement.

## Conceptual Framework

The present study is about how engagement can be used to understand how learners are involved in work with data and how characteristics of activities and learners impact the relationships between work with data and engagement. Its context is out-of-school-time STEM enrichment programs designed to meet guidelines for best practices. The conceptual framework in the present study is presented in Figure 2 and is unpacked in the remainder of this section. 
 
**Figure 2. A conceptual framework for this study with research questions labeled.**

There are five aspects of work with data synthesized from past research (i.e., Hancock et al., 1992; Lehrer & Romberg, 1996; Wild & Pfannkuch, 1999):
1. Asking questions or identifying problems
2. Making observations
3. Generating data
4. Data modeling
5. Interpreting and communicating findings

In addition to these five aspects of work with data, two activities that are not part of work with data will be coded so engagement in each aspect of work with data can be compared to other during other times. Other instructional activities, such as listening to a lecture by an instructor, and other activities, such as activities characterized by students being not focused on STEM, off-task, or unfocused.

In this figure, engagement in work with data is associated with different profiles of engagement and its conditions (PECs). The theoretical framework for the person-oriented approach suggests that while the dynamics among the individual aspects of engagement emerge in complex and situation-specific ways, it is possible to consider engagement in terms of patterns among its components. In most settings, a relatively small number of these patterns can be identified in most developmental (and learning-related) settings (Bergman & Magnusson, 1997) and these patterns can be considered in terms of profiles of engagement (Schmidt et al., 2017). 

In addition, a pre-program measure of learners’ individual interest in STEM is hypothesized to be associated with both the relationship between learners’ perception of the activity and themselves and the relationship between the aspects of work with data and engagement because some learners may be inclined from the start to be more engaged. This inclination could explain some of the variability in relations between engaging in work with data and the PECs. ESM responses are associated with students, moments, and program effects that must be accounted for (Strati et al., 2017). Each student in the same program was signaled at the same time, so that each student will have a response associated with each moment (within the same program), and each moment will have a response associated with each student (again, within the same program).

## Research Questions

The four research questions are as follows:
1. What profiles of engagement and its conditions (PECs) emerge from the participants’ responses?
2. How does work with data relate to each PEC?
    a. How does work with data, in general, relate to PEC?
    b. How do the specific aspects of work with data (i.e., asking questions or identifying problems, constructing measures, accounting for variability or uncertainty, and interpreting and communicating findings), and other activities that are not work with data, relate to each PEC?
3. How do the relationships identified as part of answering research question #2 differ depending on whether or not instructional support for work with data was provided?
    a. How do the relationships between work with data, in general, and PECs differ on the basis of instructional support for work with data?
    b. How do the relationships between the specific aspects of work with data and PECs differ on the basis of instructional support for work with data?
4. Do the relationships between work with data and the PECs vary depending on students’ pre-program interest in STEM? 
    a. How do these relations differ for work with data on its own?
    b. How do these relations differ for work with data with support?
5. What are the common characteristics of potentially adaptive PECs beyond the presence of the aspects of work with data and other activities or the characteristics of learners?